### ISSUE TITLE
Repair on a single DC triggers "Segment is faulty"

### ISSUE THREAD

**Issue by lapo-luchini** [thelastpickle/cassandra-reaper#1037]
I have a table in sync across two DCs, since the second one (a single node disaster-recovery site) is very slow I tried scheduling a repair only on the main DC (which should be much faster) but all my repairs ended up in "Segment # is faulty, replica set changed since repair was started:" (as per [RepairRunner:508](https://github.com/thelastpickle/cassandra-reaper/blob/26c710b2a32bea6add9a0ab25807c28ef942e490/src/server/src/main/java/io/cassandrareaper/service/RepairRunner.java#L508)).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-227) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-227

**Comment by adejanovski** [comment]
Oh right, we're not applying the dc filter when performing this check.
Definitely a bug that needs fixing.

**Comment by adejanovski** [comment]
This was fixed by [this commit](https://github.com/thelastpickle/cassandra-reaper/commit/93c041080a429129dcae98d41a8625ac066373c5).
