### ISSUE TITLE
Issues in running reaper with sidecar mode

### ISSUE THREAD

**Issue by Payal147** [thelastpickle/cassandra-reaper#1043]
Repairs are getting failed continuously, logs from system.log file.
`Failed creating a merkle tree for [repair #39838950-9005-11eb-b7d6-1dd4209ac66d on KS.table, [(-656672693882185934,-630256599731596978]]], /<IP> (see log for details)
ERROR [ValidationExecutor:39631] 2021-03-28 20:36:12,342 CassandraDaemon.java:235 - Exception in thread Thread[ValidationExecutor:39631,1,main]
java.lang.RuntimeException: Parent repair session with id = 3978daf0-9005-11eb-b7d6-1dd4209ac66d has failed.
ERROR [AntiEntropyStage:1] 2021-03-28 20:36:12,335 RepairMessageVerbHandler.java:168 - Got error, removing parent repair session
ERROR [AntiEntropyStage:1] 2021-03-28 20:36:12,335 CassandraDaemon.java:235 - Exception in thread Thread[AntiEntropyStage:1,5,main]
java.lang.RuntimeException: java.lang.RuntimeException: Parent repair session with id = 3978daf0-9005-11eb-b7d6-1dd4209ac66d has failed.`

while checking the status of running repair, getting below error

`systemctl status cassandra-reaper -l 
Apr 01 14:04:10 10-2-9-180.node.nw000.com cassandra-reaper[68446]: WARN   [2021-04-01 14:04:10,815] [us:25b068e0-65bb-11eb-9971-d3ef67d827c3:25b0de21-65bb-11eb-9971-d3ef67d827c3] i.c.s.SegmentRunner - A host (<IP>) reported that it is involved in a repair, but there is no record of any ongoing repair involving the host. Sending command to abort all repairs on the host.
Apr 01 14:04:11 10-2-9-180.node.nw000.com cassandra-reaper[68446]: WARN   [2021-04-01 14:04:11,140] [us:08a0b900-6c26-11eb-9d27-6bddc33ea874:08a15553-6c26-11eb-9d27-6bddc33ea874] i.c.s.SegmentRunner - A host (<IP>) reported that it is involved in a repair, but there is no record of any ongoing repair involving the host. Sending command to abort all repairs on the host.`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-221) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-221

**Comment by Payal147** [comment]
I see the below log but incremental repair is set to false, then why it is trying to do anticompaction.
`Got anticompaction request AnticompactionRequest{parentRepairSession=85d62900-934a-11eb-84e2-0d871478d39f} org.apache.cassandra.repair.messages.AnticompactionRequest@5f0be972`

**Comment by adejanovski** [comment]
Hi @Payal147,

is there by any chance someone still running `nodetool repair` commands on the cluster?
It looks like there are rogue repairs running that indeed trigger anticompaction (full repair with nodetool does that as well), which then conflict with Reaper's repairs.

The messages you're getting suggest that you're still on Reaper 2.1.x, right? 
If you're using the SIDECAR mode, I'd strongly recommend to upgrade to the latest 2.2.x which dramatically improves Reaper overall and SIDECAR in particular.

**Comment by Payal147** [comment]
I don't think so any repair was triggered manually but I with the help of spreaper I have found some hanging repairs like below

> "creation_time": "2021-02-11T05:00:17Z",
      "current_time": "2021-04-02T06:09:20Z",
      "datacenters": [],
      "duration": "50 days 1 hour 9 minutes 3 seconds",
      "end_time": null,
      "estimated_time_of_arrival": "2064-05-31T08:41:07Z",
      "id": "08a0b900-6c26-11eb-9d27-6bddc33ea874",
      "incremental_repair": false,
      "intensity": 0.900,
      "keyspace_name": "KS",
      "last_event": "postponed repair segment 08a0b910-6c26-11eb-9d27-6bddc33ea874 because one of the hosts (IP) was already involved in a repair",
      "nodes": [],
      "owner": "name",
      "pause_time": null,
      "repair_parallelism": "PARALLEL",
      "repair_thread_count": 3,
      "repair_unit_id": "08a8e100-a702-11ea-864f-29fdda9b726b",
      "segments_repaired": 1,
      "start_time": "2021-02-11T05:00:17Z",
      "state": "RUNNING",
      "total_segments": 316

**Comment by Payal147** [comment]
Below logs are confusing me, it's running anticompaction or not?

> DEBUG [AntiEntropyStage:1] 2021-04-02 06:29:45,511 RepairMessageVerbHandler.java:142 - Got anticompaction request AnticompactionRequest{parentRepairSession=c883a2f0-937c-11eb-aa6b-2f086c1f2571} org.apache.cassandra.repair.messages.AnticompactionRequest@543f35db
INFO  [RepairJobTask:8] 2021-04-02 06:29:58,732 ActiveRepairService.java:452 - [repair #d7e3f240-937c-11eb-aa53-47f50766dc9a] Not a global repair, will not do anticompaction

**Comment by adejanovski** [comment]
> Below logs are confusing me, it's running anticompaction or not?

No, it is not.

Again, I'd recommend upgrading to 2.2 if you haven't already. The segment orchestration is much more efficient and will protect you from this kind of behavior.
And wow, 50 days is a lot :)

Here's what I'd do to clean things up: 

- Stop Reaper instances
- Roll restart the Cassandra cluster
- Upgrade Reaper to 2.2.3 and restart it

You should see much better progress with lower load on the cluster and the issues you're seeing should go away naturally.

**Comment by Payal147** [comment]
Thanks.
I have restarted reaper and Cassandra multiple times but hanging repairs were always there and on top of that, I did not see an abort option in WebUI.
However, I will upgrade it soon.

**Comment by Payal147** [comment]
I have restarted reaper instances and cassandra and once the repair was triggered from reaper, it gave the below error.

>  "last_event": "postponed repair segment 6f5f7bb8-9399-11eb-bb16-81c2dd0ead60 because segment 6f5c6e60-9399-11eb-bb16-81c2dd0ead60 is running on host 127.0.0.1".

Just wondering why "127.0.0.1", did I misconfigure something.

**Comment by adejanovski** [comment]
No you did nothing wrong, it's just how Reaper 2.1.x reports nodes in sidecar mode. I think I changed this behavior in 2.2.

**Comment by adejanovski** [comment]
Closing inactive issue.
