### ISSUE TITLE
What happened to 2.2.4 release?

### ISSUE THREAD

**Issue by maikzumstrull** [thelastpickle/cassandra-reaper#1047]
I have an email notification from April 9 of a 2.2.4 release with two changes, but see no trace of it now. Did it have to be withdrawn because of a serious bug?

**Comment by adejanovski** [comment]
CI is now failing consistently (but on random workflows) and I'm investigating the issue. In the meantime I can't publish new releases safely...

The clusters created with CCM are randomly unaccessible through JMX, even preventing nodetool commands from running.
I still don't understand what change could have caused this and it's clearly unrelated to Reaper itself.

**Comment by maikzumstrull** [comment]
Thanks for the explanation. FWIW 2.2.3 is mostly stable in our environment and we don't desperately need what was to be in 2.2.4, just wanted to clear up what's happening with the new release.
