### ISSUE TITLE
Make incremental schedules trigger on %unrepaired threshold

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1058]
Incremental repair schedules should trigger based on a percentage of unrepaired data rather than using fixed interval.
The interval field could be repurposed to store the threshold instead of creating a new field.
The UI would need to change the label of the interval text input when the user switches from full to incremental and vice versa.

The scheduler would leverage %repaired metrics collected to trigger incremental repairs (#1057).

**Comment by jdonenine** [comment]
Move to issue #1079
