### ISSUE TITLE
Segment count per node is 0 when I create it manually.

### ISSUE THREAD

**Issue by afsanchez83** [thelastpickle/cassandra-reaper#1065]
**Spotted on 2.1.3 (da70e93)**
Hi,

When I create a new schedule repair this mark 0 in "segment count per node"but when it´s created by auto-scheduling the number is reflected as configuration file is.

![image](https://user-images.githubusercontent.com/79571496/117793736-837f8b80-b21a-11eb-9a56-cb8f35febf50.png)

Here you can see how it is 16 when the repair is schedule by auto-scheduling

![image](https://user-images.githubusercontent.com/79571496/117793968-c3df0980-b21a-11eb-9170-28f5dc972c8e.png)

Thanks in advance.

**Comment by adejanovski** [comment]
Hi @afsanchez83,

this bug was fixed in 2.2.3. See #1030 for more info.
