### ISSUE TITLE
reaper_db.cluster seed_hosts doesn't automatically update when IPs change

### ISSUE THREAD

**Issue by cin** [thelastpickle/cassandra-reaper#1067]
This is happening more often to us because we're running on kubernetes and the C* pod IPs change every time they are restarted. This would happen in other environments as well but IPs typically only change when a node has to be replaced. We have `enableDynamicSeedList` enabled but from the docs it doesn't sound like it would help us in this case.

I used an update query like the one below to get around this issue after a rolling restart.
`update reaper_db.cluster set seed_hosts = {'x.x.x.x', 'x.x.x.y', ...} where name = 'foo';`

However, it would be nice if this was done automatically. Am I missing a setting or is this by design? If not, is this a desired feature?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-204) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-204

**Comment by ReillyBrogan** [comment]
Yeah we've seen this one as well. Unfortunately k8s doesn't have a way to use static IPs for pods.

**Comment by adejanovski** [comment]
In the context of Kubernetes you'll need to set `enableDynamicSeedList` to `false` and use a service that exposes the Cassandra pods internally as seed.
This is what we do in K8ssandra and it's working nicely.
