### ISSUE TITLE
When running repair for the same keyspace - prometheusMetrics are not updated

### ISSUE THREAD

**Issue by DzeryCZ** [thelastpickle/cassandra-reaper#1071]
I have scheduled repairs on multile keyspaces to run every week. 
The first run of every keyspace can be montored via `/prometheusMetrics` (grafana), but when the run finishes and a new schedule takes place, the metrics shows the previous run => `io_cassandrareaper_service_RepairRunner_repairProgress=1`.
When I restart `cassandra-reaper` container the `/prometheusMetrics` picks up the new runs.

I've tried to run version `2.2.4` and also `master` of `cassandra-reaper`.

Any tips, how to resolve this issue?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-200) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-200

**Comment by shaotingcheng** [comment]
I have the same problem with V2.2.3
It seems the same as #959 with V2.0.5

**Comment by lapo-luchini** [comment]
Will this be in 2.3.2, thus?
Is current trunk "stable"?
(I could consider building it myself)

**Comment by adejanovski** [comment]
It will be in 3.0 actually, which will be released within a few days. Current `master` is considered as working... until bugs are found :) Right now it should be in a solid state as we approach release time.
You do not need to build it yourself as it is built automatically for each push to the `master` branch. You can find beta packages [here](https://cloudsmith.io/~thelastpickle/repos/reaper-beta/packages/), and can use the `master` tag of [the docker image](https://hub.docker.com/layers/thelastpickle/cassandra-reaper/master/images/sha256-90ca0361b42e4c636705983d43a906e1e6602bfa5601a955576f95eab7dd3c64?context=repo).

**Comment by lapo-luchini** [comment]
Ohhh, cool, I didn't notice that. I extracted `cassandra-reaper-3.0.0-BETA-20211015.jar` from the DEB file and am testing it on FreeBSD. Thanks.

**Comment by lapo-luchini** [comment]
@DzeryCZ this should be closed, I think?
(it is on my own tests)

**Comment by DzeryCZ** [comment]
Yes, the functionality works as expected. 

Many thanks.
