### ISSUE TITLE
Make incremental schedules trigger on %unrepaired threshold

### ISSUE THREAD

**Issue by jdonenine** [thelastpickle/cassandra-reaper#1079]
Incremental repair schedules should trigger either based on a percentage of unrepaired data or using fixed intervals.
A new field would be added to store the percent repaired threshold.
The UI would need to accomodate for both possibilities, allowing only one trigger out of the two and restricting the use of the percent based threshold to incremental repairs.

The scheduler would leverage %repaired metrics collected to trigger incremental repairs (#1057).

Recreation of original issue #1058

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-475) by [Unito](https://www.unito.io)
┆Epic: Incremental Repair
┆Fix Versions: reaper-2.3.0,k8ssandra-1.4.0
┆Issue Number: K8SSAND-475
┆Priority: Medium

**Comment by michaelsembwever** [comment]
> Incremental repair schedules should trigger based on a percentage of unrepaired data rather than using fixed interval.

There are valid scenarios where incremental repairs will still want to be scheduled by fixed intervals.

For example data that is written (in batch jobs) during the night with reads during the day. Scheduling a daily (early morning) incremental repair makes more sense than trying to guess a percentage value. (Furthermore, if the writes are via a batch job, a percentage based job is going to get in the way. Akin to how tombstone ratio gets in the way the day before dropping expired TWCS sstables.)

**Comment by adejanovski** [comment]
You're right, I realized recently the description went too far here and we need to allow both types of triggers. Moreover, the percent repaired metric only appeared in the the 3.x branch and users will still want to run incremental repairs on older versions (even if they should not...).

I'll update that description accordingly 👍
