### ISSUE TITLE
Missing cryptograph option in 2.2.5 image

### ISSUE THREAD

**Issue by ducnm0711** [thelastpickle/cassandra-reaper#1093]
Hi
First of all thank you for keep the reaper alive.
I just updated to version 2.2.5 in my k8s system and seems that this part is missing in `casssandra-reaper.yaml`
```
#cryptograph:
#  type: symmetric
#  systemPropertySecret: SOME_SYSTEM_PROPERTY
```
So yes, the WebUI keeps complaining about enable encryption before adding JMX Credential.
The workaround is to mount a pre-defined yaml file as ConfigMap but it's not ideal to do it.
Would be nice if you can make a HF update.
Thanks !

**Comment by adejanovski** [comment]
Hi @fiery06,

I've created a PR that fixes your issue and pushed a Docker tag based off it: thelastpickle/cassandra-reaper:d005d8e

Could you test it to see if it works as expected? The docker variable you'll need to set is `CRYPTO_SYSTEM_PROPERTY_SECRET`, which should contain the name of an env variable which must contain your encryption secret.

**Comment by rss04** [comment]
Hi @adejanovski  /usr/local/bin/configure-jmx-credentials.sh: line 59: syntax error: unexpected end of file (expecting "fi") | grep

**Comment by rss04** [comment]
Hi @adejanovski  .... It did not fix the issue of encrypting JMX credentials.  I still see the same error

**Comment by ducnm0711** [comment]
@rss04 Let's just wait, new image not ready yet :)
https://github.com/thelastpickle/cassandra-reaper/pull/1095

**Comment by rss04** [comment]
hi @fiery06 thank you. If possible, can you please share the config map workaround.

**Comment by ducnm0711** [comment]
Create your own cassandra-reaper.yaml file with all configs and replace the container `/etc/cassandra-reaper.yaml` with volumeMount. The container will run, but will throw error about read-only `cassandra-reaper.yaml`
The downside is that you can't use any Environment Variables => No flexibility.

**Comment by rss04** [comment]
Hi @fiery06 ...thank you. I will wait for the new image. I agree with you on not using env variables. I will stick to 2.0.5 for now.

**Comment by adejanovski** [comment]
doh 🤦  Sorry about that folks.
I've fixed it and pushed another tag: `thelastpickle/cassandra-reaper:87c0c2b`

I've also re-added Docker tests to catch this kind of problem early in CI.

**Comment by rss04** [comment]
Hi @adejanovski  ...thank you for the fix and it is working.

**Comment by adejanovski** [comment]
Thanks for the feedback @rss04 !

**Comment by ducnm0711** [comment]
Thank you @adejanovski ;)

**Comment by rss04** [comment]
@adejanovski @fiery06 can you see if snapshots are working through GUI. Earlier when I used to create a snapshot, I can see the snapshot details below. Now I am not seeing them.

**Comment by rss04** [comment]
![image](https://user-images.githubusercontent.com/18092009/122540013-3602f500-cff6-11eb-8d15-20e6406cb4ae.png)
