### ISSUE TITLE
Cassandra-reaper lost schedule list when shot down

### ISSUE THREAD

**Issue by MGulerce** [thelastpickle/cassandra-reaper#1102]
Hi,
We use cassandra 3.11.10 and reaper 2.2.4.
I started the cluster and reaper Then I schedule my keyspaces but after some days  I checked reaper ıt killed but ı cant find why killed in the log file.
Then I started it again and there is no schedule. Is it normal or it is a bug.
And why might be reaper is down?

Thanks.

**Comment by mikelitka** [comment]
Log detail from /var/log/cassandra-reaper/reaper.log during the time of the reaper failure would be helpful to diagnose why it was killed. 
Are you using the in memory backend? If so all schedules would be held in memory and lost during a restart.

http://cassandra-reaper.io/docs/backends/memory/

You'll want to move to a backend that can persist data like the Cassandra backend:
http://cassandra-reaper.io/docs/backends/cassandra/

**Comment by MGulerce** [comment]
There is no log that I can examine.
But I will check the link 
Thanks for helping

**Comment by adejanovski** [comment]
@MGulerce, I'll close this ticket as it's been inactive for a while.
Please reopen if you're still experiencing this issue.
