### ISSUE TITLE
Read-only configurations & non-root user

### ISSUE THREAD

**Issue by jeffbanks** [thelastpickle/cassandra-reaper#1114]
For improved security, the Reaper image should be configured to use a `non-root` user with `read-only` permissions for configuration files (shiro.ini and cassandra-reaper.yml). Ensure Reaper image is updated as necessary to use a non-root user. 

Related to security additions and hardening for k8ssandra:
* [k8ssand-700](https://k8ssandra.atlassian.net/browse/K8SSAND-700) 
* [k8ssand-701](https://k8ssandra.atlassian.net/browse/K8SSAND-701)

**Comment by adejanovski** [comment]
@jeffbanks, I assume this ticket can be closed. Right?

**Comment by jeffbanks** [comment]
Completed root user restrictions as part of initial security changes in k8ssandra.

* [k8ssand-705](https://k8ssandra.atlassian.net/browse/K8SSAND-705)

The initial set of efforts did not include `read-only root filesystem` restrictions that are scoped as part of a phase 2 security epic.

* [k8ssand-977](https://k8ssandra.atlassian.net/browse/K8SSAND-977)
