### ISSUE TITLE
The current running repair can not be listed from web ui

### ISSUE THREAD

**Issue by qinjin** [thelastpickle/cassandra-reaper#1124]
**Spotted on 2.1.3 (da70e93)**

When there is a relatively long running repair, which we can see its progress bar on the _cluster_ tab but going to the repairs tab and it is not in the running repairs even when selecting list 100 repairs.

Could it be that when listing 100 repairs, it is taken all finished and running repairs? So if there are more than 100 finished after the current running one, the running repair would not be shown. A desired outcome is to always have the current repair showing from the repair tab.

Also, without listing the current running repair, we're not able to stop/pause it.

**Comment by adejanovski** [comment]
The ordering of the repair by cluster table was wrong in 2.1 and has been modified since then.
It's highly probable that this issue doesn't exist anymore in later versions.
Let us know if it's still the case.

**Comment by lapo-luchini** [comment]
This is happening to me too, even after upgrading to 3.2.0: three repairs are showing up in "Cluster" and zero under "Repairs".

**Comment by lapo-luchini** [comment]
At least in my case, this is because of the `LIMIT 10` as explained in #1203 and #1080.

**Comment by adejanovski** [comment]
This was fixed in v3.3.0
