### ISSUE TITLE
table repair fails when limited on one DC 

### ISSUE THREAD

**Issue by marjana23** [thelastpickle/cassandra-reaper#1128]
I am using reaper 2.3.1, OSS 3.11.10.
If I schedule a repair on a table which is replicated to 2 DCs, rf 3, and limit it to be run in one DC only, the repair fails with:
"`Replica set changed for segment 3d13c51f-283b-11ec-af04-a9ec581eeeb8 on range io.cassandrareaper.core.Segment@28d0f9f0`"

I've tried a different table, same error. No issues running repairs without limiting to a DC.
Thanks!

**Comment by JerryKwan** [comment]
@adejanovski I encountered this problem too, the version of cassandra-reaper is reaper-3.1.1-1.x86_64. Any suggestions how to fix it?
