### ISSUE TITLE
Repair schedules don't keep adaptive setting

### ISSUE THREAD

**Issue by eriksw** [thelastpickle/cassandra-reaper#1137]
After creating a repair schedule in the UI in which I enable adaptive repair, if I go to edit the repair it shows that Adaptive is `false`!

**Spotted on 3.0.0 (ae0c6af)**

https://user-images.githubusercontent.com/24530198/140812330-0f1380fb-cc51-48a4-8be5-1274b14f4538.mov

**Comment by eriksw** [comment]
Following up, this appears to be an issue with the Edit view. Clicking on the schedule row in the UI shows the details in which Adaptive is indeed true.

**Comment by adejanovski** [comment]
This was fixed and released in 3.0/3.1
