### ISSUE TITLE
cassandra-reaper-3.1.0-SNAPSHOT.jar does not exist

### ISSUE THREAD

**Issue by Isabella95** [thelastpickle/cassandra-reaper#1140]
**When i tried to build the docker image with the following command:**

mvn -pl src/server/ docker:build -Ddocker.directory=src/server/src/main/docker

**cassandra-reaper image wasn't build because dockerfile can't find cassandra-reaper-3.1.0-SNAPSHOT.JAR, it does not exist.**

**Did i do something wrong?, I'd appreciate your help. Thank you.**

[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE

[INFO] ------------------------------------------------------------------------

[INFO] Total time:  1.928 s

[INFO] Finished at: 2021-11-07T09:31:32-05:00

[INFO] ------------------------------------------------------------------------

[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:1.2.0:build (default-cli) on project cassandra-reaper: Exception caught: ADD failed: file not found in build context or excluded by .dockerignore: stat cassandra-reaper-3.1.0-SNAPSHOT.jar: file does not exist -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by zencircle** [comment]
Build fails for me as well and errors out on Google application default credentials, any way to bypass this >
```
mvn -X -pl src/server/ docker:build -Ddocker.directory=src/server/src/main/docker
...
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@6c518474
[DEBUG] -- end configuration --
[DEBUG] /Users/test1/.docker/ca.pem, /Users/test1/.docker/key.pem or /Users/test1/.docker/cert.pem does not exist, not using SSL
[DEBUG] Using configfile: /Users/test1/.docker/config.json
[DEBUG] Failed to load Google application default credentials
java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '/Users/test1/.docker/config.json': Error reading credentials from stream, 'type' field not specified.
    at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentialsUnsynchronized (DefaultCredentialsProvider.java:139)
```

**Comment by adejanovski** [comment]
@Isabella95, you first need to build Reaper itself before creating the docker image. For that, run: `mvn clean package -DskipTests`
Only then can you run `mvn -pl src/server/ docker:build -Ddocker.directory=src/server/src/main/docker`.

@zencircle, the problem seems related to your local docker configuration which seems to have some elements from Google's gcr maybe? Not sure where to go from here, but I don't think that's related to Reaper.

**Comment by zencircle** [comment]
https://github.com/spotify/docker-maven-plugin
`The plugin gives priority to any credentials in the docker-cli config file before explicitly configured credentials` . This seems to be main issue
```
cp settings.xml ~/.m2/
<servers>
  <server>
    <id>dtr</id>
    <username>test1</username>
    <password>pass123</password>
    <configuration>
      <email>test1@exampl.com</email>
    </configuration>
  </server>
</servers>

grep -n2 dtr src/server/pom.xml 
479-                        </resource>
480-                    </resources>
481:                        <serverId>private</serverId>
482:                        <registryUrl>https://private.example.com</registryUrl>               
483-                </configuration>
484-            </plugin>
```
Since I am having hard time, is it possible to compile the jar without using maven docker plugin ?

**Comment by adejanovski** [comment]
@zencircle, the jar file can be generated without interacting with the docker plugin. `mvn clean package` will do just that.

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket. Feel free to reopen if needed.
