### ISSUE TITLE
Differente Stargate nodes within the UI

### ISSUE THREAD

**Issue by jdonenine** [thelastpickle/cassandra-reaper#1145]
As described in https://github.com/k8ssandra/k8ssandra/issues/1171 Stargate nodes appear in an unknown and confusing state within the Reaper UI:

![image](https://user-images.githubusercontent.com/7901615/141803573-409eec80-2685-4f00-af8a-b508c70a6946.png)

We should identify the Stargate nodes and differentiate the way they are displayed within the UI here in Reaper to reduce confusion and false-positive indications that there is a problem with those nodes in the cluster.

**Comment by adejanovski** [comment]
@jdonenine, assigning the ticket to you since you seem to be working on it ;)
