### ISSUE TITLE
Snapshots not being removed

### ISSUE THREAD

**Issue by TheTomahawk** [thelastpickle/cassandra-reaper#115]
I've had cassandra-reaper running quite successfully now for a few months.  I logged into a node today to check something and noticed that the disk usage was much higher than I would have expected.  When I checked the snapshots I found several months worth of snapshots there -- it appears for as long as cassandra-reaper has been running.

I'm now manually logging into each node to clear the snapshots, but why isn't reaper cleaning them up itself after a period of time?  Is there a setting I'm missing?

**Comment by TheTomahawk** [comment]
Hmm, strangely not all nodes were affected.  In one DC, all nodes were affected.  In the other DC, no nodes were affected.

**Comment by adejanovski** [comment]
Hi, 

Someone mentioned this in a discussion recently but I've never experienced it.
Reaper doesn't perform snapshots by itself, they are part of the repair process when using SEQUENTIAL mode, so it cannot purge them afterwards.
What could be happening is that some segments failed to be processed within the timeout (30mn by default), in which case Reaper kills the repair through `forceTerminateAllRepairSessions`, and then reschedules them.

My best guess is that forceTerminateAllRepairSessions doesn't clean up repair snapshots (which I'll verify ASAP).

Reaper cannot forcefully delete snapshots as it could conflict with backup schedules, so if my theory is verified we need to check what could be done in Cassandra.
Then Reaper could possibly list snapshots and issue a warning when old ones clutter the disks.

**Comment by TheTomahawk** [comment]
Thanks for the reply.  I'll try to put something in place on all of the servers to clean up the snapshots periodically.  "nodetool clearsnapshot" allows to specify only by name or keyspace, but not by date, which is unfortunate.

What's interesting is that only servers in one DC on our Dev cluster were affected by this (the other DC, and both DCs in Prod appear to be fine).  So it's not a cassandra-reaper issue, but a cassandra issue itself.  The oldest snapshot I'm seeing on my Production cluster is May 23rd (Just over 2 weeks ago).

I'll keep an eye on it over the coming weeks, but it appears to be a false alarm for reaper.

(maybe a feature request, though?!  To delete snapshots over x weeks/days old...)

Thanks

**Comment by samuelbenhamou** [comment]
got the same behavior on my cluster...which is a bit annoying: I have to regularly check for remaining snapshots to free up some space

**Comment by eriksw** [comment]
@adejanovski This is still an issue. Can this be reopened?

In the past couple weeks I've had ~55 repair-related snapshots pile up in my cluster.

**Comment by adejanovski** [comment]
cf #666 for more explanations
