### ISSUE TITLE
spreaper compatibility with reaper 3.0, adaptive and percent_unrepaired_threshold arguments

### ISSUE THREAD

**Issue by jojo-dc** [thelastpickle/cassandra-reaper#1167]
Reaper 3.0 introduced added the adaptive and percent_unrepaired_threshold arguments for scheduling repairs. However the packaged spreaper cannot handle these new arguments. 
Is spreaper defunct or are there plans to update it? 
Thanks

**Comment by adejanovski** [comment]
Hi @jojo-dc,

spreaper isn't defunct in any way, we just forgot to update it when adding those new features.
I'll try to handle that shortly.
