### ISSUE TITLE
About the schedule setting that changed only Nodes.

### ISSUE THREAD

**Issue by taku333** [thelastpickle/cassandra-reaper#1175]
I would like to check on the schedule settings that have been changed only for Node.

I have created multiple schedules using the following steps.

1. Using CassamdraReaper 3.1.1.
2. Scheduels > Add a new shedule  > Various values added. > Add Schedule
3. A schedule was created.
4. Advanced settings > Change "Nodes" > Add Schedule
5. Warning.

![Scheduling conflict detected](https://user-images.githubusercontent.com/16697482/159472470-a1def3ee-f16c-4753-96c2-69b3ff532e89.png)

If I set "Nodes", do you know which is which?

### full
`
nodetool repair -full
`

### primary
`
nodetool repair -pr
`
 
I would like to confirm this because multiple schedules are not required for FULL.

**Comment by adejanovski** [comment]
What's precisely the list of schedules you're trying to create and for which use case do you want to create a schedule for specific nodes?

You cannot distinguish repair settings for specific nodes if that's what you're trying to do. Also, you shouldn't try to reason against nodetool repair, it processes repairs per node while Reaper processes them per token range.

So creating a single repair schedule for your keyspace should be enough, and Reaper will take care of repairing each token range just once.

**Comment by taku333** [comment]
> You cannot distinguish repair settings for specific nodes if that's what you're trying to do.

→Thanks for your answer!
I apologize for the ISSUE place.
The above answer clears my doubts.
