### ISSUE TITLE
provide means of migrating from postgres backend to C* backend

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#118]
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-272) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-272

**Comment by zznate** [comment]
Could be as stupid as a script that did pgdump to CSV and import via cqlsh?

**Comment by rustyrazorblade** [comment]
Absolutely. Love the idea of a trivial export / import process.

**Comment by adejanovski** [comment]
Well, the data models are pretty different between Postgres and Cassandra so it might take a little more than this if we want to transfer the whole history. For example, Postgres uses integers to store the repairs/schedule/segment ids, while the new C* model uses UUIDs.

**Comment by adejanovski** [comment]
There doesn't seem to be much interest for this feature and I would favor a more generic import/export feature, which could also help back up a Reaper install.
