### ISSUE TITLE
Nodes Field in Repair UI doesn't wrap

### ISSUE THREAD

**Issue by Rooks103** [thelastpickle/cassandra-reaper#1187]
Very similar to the issue in #1183, the nodes field on the Repair screen doesn't wrap when you include a load of nodes. Picture included (with IPs blocked out for security reasons). jdonenine perhaps another super easy fix for you?

![Nodes!UNITO-UNDERSCORE!Dont!UNITO-UNDERSCORE!Wrap](https://user-images.githubusercontent.com/12748729/163452892-d976a1ed-05b5-495f-9ba7-f23fa15d7035.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1459) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1459
┆priority: Medium

**Comment by jdonenine** [comment]
Bah, I bet we find more of these as well 😔 

@Rooks103 @adejanovski I'll take this one real quick.

**Comment by jdonenine** [comment]
I don't see this problem testing it out locally (although I do not have as many nodes in my test at the moment, only 8), the display of the nodes actually shares the same component as the display of the tables, so the changes from #1185 should also apply here.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/7901615/163697749-3784e71e-b55a-4481-9219-9dd5baea69c6.png">

What version are you running @Rooks103 ?

**Comment by Rooks103** [comment]
We are running version 3.1.1 of Reaper at the moment, which I don't believe has the fix #1185 yet. I'll wait until the next release and re-test this.

**Comment by jdonenine** [comment]
> We are running version 3.1.1 of Reaper at the moment, which I don't believe has the fix #1185 yet. I'll wait until the next release and re-test this.

Sounds good, I think #1185 will do the trick for this as well 🤞

**Comment by adejanovski** [comment]
Since we didn't get an update, I assume #1185 fixed it 😉 
Feel free to reopen if not.
