### ISSUE TITLE
Reaper crashes when tables in keyspace are empty

### ISSUE THREAD

**Issue by xgerman** [thelastpickle/cassandra-reaper#1188]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13951830)

We have been seeing:
`i.c.s.SchedulingManager - catch exception 
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:121)
	at io.cassandrareaper.service.RepairRunService.computeGlobalSegmentCount(RepairRunService.java:243)
	at io.cassandrareaper.service.RepairRunService.generateSegments(RepairRunService.java:177)
	at io.cassandrareaper.service.RepairRunService.registerRepairRun(RepairRunService.java:108)
	at io.cassandrareaper.service.SchedulingManager.createNewRunForUnit(SchedulingManager.java:301)
	at io.cassandrareaper.service.SchedulingManager.manageSchedule(SchedulingManager.java:151)
	at io.cassandrareaper.service.SchedulingManager.run(SchedulingManager.java:101)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`

Looking at the keyspace being repaired we noticed 
`
Command:  nodetool describering example
Schema Version:eb3065eb-2232-3abb-827a-599a1c88dee1

TokenRange:

```
    TokenRange(start_token:-7944953496064016005, end_token:-7629285993860306682, endpoints:[], rpc_endpoints:[], endpoint_details:[])
```

```
    TokenRange(start_token:1823877555085617768, end_token:2628581258427417601, endpoints:[], rpc_endpoints:[], endpoint_details:[])
```

```
    TokenRange(start_token:-817222685367755172, end_token:-170518143685128414, endpoints:[], rpc_endpoints:[], endpoint_details:[])
```

...
`

Since there are no endpoints we think that the `endpointToRange` map is empty and the check in https://github.com/thelastpickle/cassandra-reaper/blob/4624485e46f9610ca146c328e3fd8a24d9639ef8/src/server/src/main/java/io/cassandrareaper/service/RepairRunService.java#L245 should be replaced with a ReaperEcxception similar to https://github.com/thelastpickle/cassandra-reaper/blob/4624485e46f9610ca146c328e3fd8a24d9639ef8/src/server/src/main/java/io/cassandrareaper/service/RepairRunService.java#L187-L191 -- instead of exiting the JVM.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1462) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1462
┆priority: Medium

**Comment by xgerman** [comment]
Happy to submit a PR if I am on the right track.

**Comment by adejanovski** [comment]
Hi @xgerman,

I know it's been a while but I'm trying to catch up on our grooming 😅 
Do you mean here that there are no tables in the keyspace or that some tables are empty in this keyspace?

Even then, I'm not sure how this would lead to an empty endpoint to range mapping 🤔 
That should only involve keyspace replication information, table content shouldn't have an impact.
Could you describe how to reproduce this and which version of Cassandra you're using?
Thanks!

**Comment by xgerman** [comment]
I submitted the PR. IT got merged - so this can be closed.
Sorry for the confusion.
