### ISSUE TITLE
Improve Prometheus metrics

### ISSUE THREAD

**Issue by colltoaction** [thelastpickle/cassandra-reaper#1198]
According to the [Prometheus best practices](https://prometheus.io/docs/practices/naming/#labels):

> Use labels to differentiate the characteristics of the thing that is being measured. Do not put the label names in the metric name, as this introduces redundancy and will cause confusion if the respective labels are aggregated away.

In the case of reaper, this best practice is ignored. See:

https://github.com/thelastpickle/cassandra-reaper/blob/ac58595266ea426bc52c7abef969fb5a189b72a7/src/server/src/main/java/io/cassandrareaper/service/RepairRunner.java#L751

My team owns a reaper instance but we can't easily relabel metrics. We don't host Prometheus but rely on another team that provides it as a service for the whole company.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1531) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1531
┆priority: Medium

**Comment by adejanovski** [comment]
Hi @colltoaction,

we're very close to merging a PR that will expose native Prometheus metrics: https://github.com/thelastpickle/cassandra-reaper/pull/974

Things should get much better with it.

**Comment by colltoaction** [comment]
I see it is merged :). Is there any pre release version I can use to test?

**Comment by adejanovski** [comment]
Yes, the latest beta was built off master: https://cloudsmith.io/~thelastpickle/repos/reaper-beta/packages/

**Comment by adejanovski** [comment]
Also, the docker images are available: https://hub.docker.com/repository/docker/thelastpickle/cassandra-reaper/tags?page=1&ordering=last_updated

**Comment by adejanovski** [comment]
Fixed and released through https://github.com/thelastpickle/cassandra-reaper/pull/974
