### ISSUE TITLE
discuss setting up mailing list

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#12]
We will probably want to set up a dedicated mailing list in the near future for Reaper.  My personal preference is Google Groups.  Thoughts?

**Comment by zznate** [comment]
+1 on googlegroups. Path of least resistance, that.

**Comment by neogenix** [comment]
+1 on google groups, but I'd also not be opposed to a public slack too :)

**Comment by adejanovski** [comment]
Google group created : https://groups.google.com/forum/#!forum/tlp-cassandra-reaper-users

@rustyrazorblade : can you write the welcome message and communicate about it ?

Thanks

**Comment by rustyrazorblade** [comment]
Yep, I'll take care of that today

**Comment by zznate** [comment]
@adejanovski sorry to be the trademark police, but can we do something like 'reaper-for-apache-cassandra'? Basically anything but prefixing the ASF trademark, ie. `*tlp-cassandra-*` ...

**Comment by zznate** [comment]
https://www.apache.org/foundation/marks/

"TLP Cassandra (anything)" skirts the edge of "nominative use." I don't want anything *even remotely* likely to be an issue given where we are headed.

**Comment by adejanovski** [comment]
Right, I've fixed that by adding "Apache" in front of Cassandra where needed.

**Comment by adejanovski** [comment]
FYI, ML moved to https://groups.google.com/forum/#!forum/tlp-apache-cassandra-reaper-users
