### ISSUE TITLE
Running repair showing in clusters page but in running repairs page

### ISSUE THREAD

**Issue by mhmdar** [thelastpickle/cassandra-reaper#1203]
Hi,
I have one Reaper deployment that shows 7 running repairs in the "Clusters" page, but in the "Repairs" Running section it's empty, even when selecting showing 100 records.
I'm attaching 2 snapshots.
Muhammad

![image](https://user-images.githubusercontent.com/24410407/173228589-e4121239-cc7d-4d1d-8666-f1c84aef8661.png)

![image](https://user-images.githubusercontent.com/24410407/173228604-29268c75-afd4-4b4f-a48b-0b88f08b5d4e.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1555) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1555
┆priority: Medium

**Comment by rjb1971** [comment]
We have run into the same problem, but we did see the jobs when we increased the display to 100.
Looks like only the last repair jobs are retrieved and then sorted into the active or done lists.
This behavior isn't as expected and when there are 100 newer repair jobs you can't see the running repairs at all

**Comment by adejanovski** [comment]
This was fixed in v3.3.0
