### ISSUE TITLE
Force running repairs to always show up in Running on Repairs page

### ISSUE THREAD

**Issue by nathanielgw** [thelastpickle/cassandra-reaper#1217]
Sometimes I have repair segements that will hang and need to be aborted and retried (almost always completing successfully on the second try) but with the default display set to 10, it can hide running repairs that are stuck until changing the `Display:`.. is there a way to force repairs in State: RUNNING to always show up in the Repairs tab?

## Depends upon

- [x] #1253 

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1719) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1719
┆priority: Medium

**Comment by adejanovski** [comment]
This is definitely something that we need to address as it's not currently possible. It's been reported in other issues as well.
We could implement a two steps lookup which would rely on a secondary index to get the RUNNING and PAUSED repairs first, and then the DONE/ERROR/ABORTED ones by applying the requested limits on both and prioritizing the display of the former.
