### ISSUE TITLE
ERROR as the state

### ISSUE THREAD

**Issue by yvester** [thelastpickle/cassandra-reaper#1218]
Hi,
I am trying to use reaperr. I have started a repair on a keyspace of my cluster. After a few minutes, it ends with ERROR as the state.  I have looked in the system logs of my nodes and i don't see anything significant in there. Could you please tell me how i go about debugging this issue? Is there a log where I could see some details about this error?
Thanks & regards,  Yves
![image](https://user-images.githubusercontent.com/8357107/183633349-0aece068-076b-47fd-81b3-2e5f0bd72b7e.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1721) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1721
┆priority: Medium

**Comment by adejanovski** [comment]
Hi,
you can click on the repair in the UI to open the detail panel and see what was the last event.
You can also check Reaper's logs directly to see the error traces there. It should be under `/var/log/cassandra-reaper`.

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket.
Feel free to reopen if you have more questions.
