### ISSUE TITLE
Can autoSchedule be configured to exclude tables?

### ISSUE THREAD

**Issue by TheTomahawk** [thelastpickle/cassandra-reaper#122]
The autoScheduling has an excludeKeyspaces option.  I'm wonder if it also has an excludeTables or excludeColumnFamily (or similar) option?

In reading http://thelastpickle.com/blog/2016/12/08/TWCS-part1.html it is suggested that out-of-window repairs should be disabled for any tables configured to use TimeWindowedCompaction, hence the questions/request.

Thanks

**Comment by adejanovski** [comment]
Not yet, but we have an upcoming improvement to add an excludedTables option to repairs. 
We would then be able to add this to the auto scheduling as well.

**Comment by TheTomahawk** [comment]
Excellent news.  Thanks.  I'll look out for that.
