### ISSUE TITLE
Cassandra Reaper is not starting

### ISSUE THREAD

**Issue by pradyunk** [thelastpickle/cassandra-reaper#1226]
Hello,
I am using 
Cassandra Version : 3.11.10
Reaper version : 2.3.1
JDK : ibm-java-x86_64-80-sr7-fp15
When I am trying to start the cassandra reaper it is not starting.
Error in the logs is like this:
Connection error: ('Unable to connect to any servers', {'1.1.1.1': error(1, u"Tried connecting to [('1.1.1.1', 9042)]. Last error: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:618)")})

Note: Cassandra is using TLS1.2 because TLS1 and TLS1.1 is disabled in the jdk that I am using.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1796) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1796
┆priority: Medium

**Comment by adejanovski** [comment]
Did you manage to fix this issue?
Reaper doesn't explicitly pick a specific TLS version to communicate with Cassandra, so I can only assume the version of the JDK you're using isn't fit for the Cassandra version you're using (or the JDK with which it's running).

**Comment by adejanovski** [comment]
I'll go ahead and close this issue. Feel free to reopen if you're still experiencing this.
