### ISSUE TITLE
Segments per node missunderstanding

### ISSUE THREAD

**Issue by rkozlo** [thelastpickle/cassandra-reaper#1229]
Hi,
version 3.2.0 and incremental repair.

When 'segmentCountPerNode' is documented and i know what it is doing, then creating new repair/schedule there is "segments per node" is confusing me. Basing on name it is really obvious what it is doing, but changing it seems not taking effect at all. Every time it creates job with segments count equal to node count. One segment to one node.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1822) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1822
┆priority: Medium

**Comment by rkozlo** [comment]
Same weird case with non-incremental(full). 7 nodes, set 8 segments per node and it created repair with 93 segments, another job with 1 segment per node and created job with 42 segments to proceed. This option is doing something but it is not clear way it calculates those segments with nodes.

**Comment by MyckeTap** [comment]
I am also a bit confused with segment count. 
A single cluster having 4 keyspaces. 
Keyspace1 - 168 tables, repair starts with 874 segments and takes day to repair.
Keyspace2 and 3 - about 14 tables, repair starts with 874 segments and takes about a single day
Keyspace4 - 1 table only with a single line inside. One line, repair starts as well with 874 segments and it takes 7 hours for a single table. 
Could someone please bring some clarification on this behavior?

**Comment by byeter** [comment]
Hi,
I also cannot understand this segment count confusion.

How the reaper calculate segment count:
I have 17 cassandra nodes in my cluster.
"segments per node"  =64  for reaper
num_token(vnodes)=256 for each cassandra nodes
 
During the repair job , reaper starts with 1998 segments .

Could you explain what the calculating method for reaper segment counts?

**Comment by adejanovski** [comment]
Incremental repair cannot be performed in a subrange fashion, so Reaper creates a single segment per node for that type of repair (regardless of the number of requested segments per node).

For full repairs:

- Reaper computes the total number of segments that you are requesting: `desired_total_number_of_segments = number_of_nodes*segmentCountPerNode`
- It computes the ideal size of segments based on that number of segments: `ideal_segment_size = total_number_of_tokens/ desired_total_number_of_segments`
- If the `desired_total_number_of_segments` is higher than the total number of vnodes, existing token ranges will be split to match the `ideal_segment_size` (there will be some overhead as some token ranges can be smaller than the `ideal_segment_size`, leading to more segments than requested)
- If the `desired_total_number_of_segments` is lower than the total number of vnodes, existing token ranges will be grouped together in a way that the resulting segments are sized as close as possible to the `ideal_segment_size`. The constraint is that token ranges can only be part of the same segment if they have the same replicas. These combined constraints can lead to much more segments than requested. The more nodes there are in a DC, the less likely token ranges will share the same replicas, preventing efficient grouping.

**Comment by rkozlo** [comment]
@adejanovski thanks for explaining. Now it is clear what is going on in background.
I have few old cluster with version 2.1.20 and behavior is weird there. Of cource non-incremental repairs. Tons of keyspaces, some are small, few GiB other larger. I scheduled repairs, and repairs even for those small keyspaces took hours. Other thing it creates jobs with thousands of segment to repair even for those keyspeces with 500MiB size on single node.
For example 2 DC 22 nodes(11 nodes per DC) and every job is created with 5632 segments(22*256 i guess). No matter what "segments count per node" i set
`{
  "cause": "scheduled run (schedule id 7d75b2f0-9283-11ed-ad3a-eb451210853d)",
  "owner": "owner",
  "id": "dd1ed5b0-9283-11ed-ad3a-eb451210853d",
  "state": "DONE",
  "intensity": 1,
  "duration": "16 hours 44 minutes 3 seconds",
  "cluster_name": "cluster",
  "column_families": [
    "fam"
  ],
  "keyspace_name": "kespace",
  "incremental_repair": false,
  "total_segments": 5632,
  "repair_parallelism": "DATACENTER_AWARE",
  "segments_repaired": 5632,
  "last_event": "All done",
  "nodes": [],
  "datacenters": [],
  "blacklisted_tables": [],
  "repair_thread_count": 1,
  "repair_unit_id": "bbcfd090-926e-11ed-ad3a-eb451210853d",
  "segment_timeout": 30,
  "adaptive_schedule": false,
  "creation_time": "2023-01-12T14:17:36Z",
  "start_time": "2023-01-12T14:17:36Z",
  "end_time": "2023-01-13T07:01:39Z",
  "pause_time": null,
  "current_time": "2023-01-13T08:00:58Z",
  "estimated_time_of_arrival": "2023-01-13T08:00:58Z"
}`
One nodetool cfstats
`Keyspace: keyspace
      Read Count: 21732796538
      Read Latency: 0.18755832536267406 ms.
      Write Count: 1053184
      Write Latency: 0.019743449387761302 ms.
      Pending Flushes: 0
              Table: table
              SSTable count: 9
              Space used (live): 428868868
              Space used (total): 428868868
              Space used by snapshots (total): 0
              Off heap memory used (total): 4549960
              SSTable Compression Ratio: 0.4574173157851545
              Number of keys (estimate): 1605232
              Memtable cell count: 442
              Memtable data size: 5921
              Memtable off heap memory used: 0
              Memtable switch count: 6179
              Local read count: 21732796545
              Local read latency: 0.188 ms
              Local write count: 1053184
              Local write latency: 0.020 ms
              Pending flushes: 0
              Bloom filter false positives: 112067
              Bloom filter false ratio: 0.00000
              Bloom filter space used: 3962896
              Bloom filter off heap memory used: 3962824
              Index summary off heap memory used: 480144
              Compression metadata off heap memory used: 106992
              Compacted partition minimum bytes: 61
              Compacted partition maximum bytes: 24601
              Compacted partition mean bytes: 438
              Average live cells per slice (last five minutes): 6.6955143847891545
              Maximum live cells per slice (last five minutes): 100.0
              Average tombstones per slice (last five minutes): 0.0010733555766859638
              Maximum tombstones per slice (last five minutes): 97.0
`
Tried also with parallel instead of DC_AWARE but same thing. I see there were huge changes since cassandra 2.2 version, but can i do something about that? 16 hours for such small keyspace is too much

**Comment by adejanovski** [comment]
You can reduce `repairManagerSchedulingIntervalSeconds` to a very low value and raise the number of threads with `repairRunThreadCount`.
You can also raise the `maxParallelRepairs` as that'll allow multiple keyspaces to be repaired concurrently.
Sadly you're paying the overhead of the number of segments and with 2.1, there's no way to reduce this number.

**Comment by rkozlo** [comment]
maxParallelRepairs: 15
repairManagerSchedulingIntervalSeconds: 10
repairRunThreadCount: 15
Going lower than 10 seconds interval is safe? On doc i can see default is 30
Seems like i can't cut it off to reasonable duration. One more reason to update cassandra on this clusters. I'll try to schedule repairs in those cluster to maximize probability not executing too much repairs in same time.
Thanks for quick help. I consider this topic as well answered so have a nice weekend and closing this "issue" ;)
