### ISSUE TITLE
Add repair finished log line

### ISSUE THREAD

**Issue by richardchesse** [thelastpickle/cassandra-reaper#1233]
This is a feature request for a log event when a repair finishes. The Reaper logs when a repair job starts, but not when one finishes. Adding an end event log would help those of us that use "door opened/door closed"-style monitoring. Thanks!

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1852) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1852
┆priority: Medium

**Comment by adejanovski** [comment]
Hi,

it looks like we already have a log output for the end of a repair run [here](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/service/RepairRunner.java#L307).

Aren't you seeing `Repairs for repair run #***** done` log messages?

**Comment by richardchesse** [comment]
Ah, yeah there it is. Sorry I was assuming it would be the last line in the log and wasn't seeing it there. Was seeing a line like this about extended segments:
`extendedSegments = 4, total segments = 637, percent extended = 0.6279435008764267`

All good here, thanks!
