### ISSUE TITLE
reaper_db clusters table: seed_hosts to list dns names, instead of real ip addresses of nodes

### ISSUE THREAD

**Issue by MyckeTap** [thelastpickle/cassandra-reaper#1239]
Currently reaper_db.cluster.seed_hosts list IP addresses of all nodes in the cluster. 
However on restart some of those IPs change. So it's better to find nodes on DNS, not IPs.
When IP changes, Reaper starts logging that it could not connect to that node.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1865) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1865
┆Priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1865

**Comment by adejanovski** [comment]
You can disable the seed host refresh with [this setting](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/packaging/resource/cassandra-reaper.yaml#L29).

This is what we do in Kubernetes so that the seed list survives nodes restarting.

**Comment by MyckeTap** [comment]
Hello @adejanovski ,

I have set REAPER_ENABLE_DYNAMIC_SEED_LIST=true
Still DNS records are translated in cluster.seed_hosts column to real IP addresses, which are dynamic on Cassandra restart.
So if all cassandra nodes are restarted, cluster appears as unreachable in UI - wheel is spinning forever under Cluster page.
Result for ongoing repairs for that cluster is that they do not progress with time.

Am I doing something wrong?

Thanks!
Cheers,
OvivO

**Comment by adejanovski** [comment]
you need to set REAPER_ENABLE_DYNAMIC_SEED_LIST to false, not true.
Setting it to true lets Reaper update the cluster seed hosts with the actual IPs of nodes in the cluster.
Setting it to false will prevent that from happening and retain the value you put when registering the cluster.

**Comment by MyckeTap** [comment]
Now with REAPER_ENABLE_DYNAMIC_SEED_LIST set to false it works as expected. Reaper keeps DNS names in cluster.seed_hosts. Great, thanks! 

I would say description to that variable is a bit misleading and not comprehensive enough :) 
By the name of the variable I also assumed - enable dynamic seed list should be TRUE in case IP addresses are dynamic, but it's the opposite :) 

`enableDynamicSeedList
Type: Boolean
Default: true
Allow Reaper to add all nodes in the cluster as contact points when adding a new cluster, instead of just adding the provided node.`
