### ISSUE TITLE
Reaper error

### ISSUE THREAD

**Issue by satishsoma** [thelastpickle/cassandra-reaper#1241]
ERROR  [2022-11-10 22:49:05,771] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly...
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /x.x.x.x:9042 (com.datastax.driver.core.exceptions.TransportException: [/x.x.x.x:9042] Channel has been closed))

reaper version: 3.2
cassandra version : 2.2.9

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1887) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1887
┆Priority: Medium

**Comment by MyckeTap** [comment]
Hi @satishsoma ,
Can you connect to Cassandra using csql client?
Do you have dynamic IPs for Cassandra or they are static?

**Comment by adejanovski** [comment]
@satishsoma, is your cluster using client to node encryption?

**Comment by adejanovski** [comment]
I'll close this ticket as stale.
Feel free to reopen if you're still experiencing this issue.
