### ISSUE TITLE
What's the efficient repair method with reaper for multi-DC cluster?

### ISSUE THREAD

**Issue by byeter** [thelastpickle/cassandra-reaper#1242]
Hi,
My cassandra cluster run on 3 different DC.Each DC has 6 cassandra nodes.
I want to specify most efficient repair strategy for my multi-DC cluster.
rarely , we encounter problems on all nodes in one of these DC at the same time.
So Full-DC repair is required,isn't it? 

-What should the most efficient repair strategy be?What is your advice?

-Does Full-DC repair with reaper cause performance bottleneck?

-also I think creating multiple reaper job splitting keyspace's  large tables   from advanced settings-tables.Is this method efficient?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1889) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1889
┆Priority: Medium

**Comment by adejanovski** [comment]
> Full-DC repair is required,isn't it?

If you're not running Cassandra 4.0 anyways, yes. After that, it depends which problems you're referring to.

> What should the most efficient repair strategy be?What is your advice?

The defaults are conservative and efficient. They try to maximize repair speed without overloading the cluster.
You can set parallelism to PARALLEL, set intensity to 1 and threads to 4 if you need more speed and if your cluster can handle the load.

> Does Full-DC repair with reaper cause performance bottleneck?

Repair has an overhead, and how it affects the cluster will depend on several factors (current load, how much entropy there is between nodes, repair settings). So yes it can, but it's impossible to tell you how much.

> also I think creating multiple reaper job splitting keyspace's large tables from advanced settings-tables.Is this method efficient?

that wouldn't be efficient as Reaper will limit the concurrency of repairs per node. Better off repairing many tables in a single repair run than one by one in multiple runs.

**Comment by adejanovski** [comment]
I'll close this issue now.
Feel free to reopen if you have more questions.
