### ISSUE TITLE
When is first repair run on keyspace added with autoScheduling enabled?

### ISSUE THREAD

**Issue by mortenjoenby** [thelastpickle/cassandra-reaper#1246]
Setup:
Cassandra 3.11.14
Reaper 2.3.0 (yes, old. Will update soon)

We use the following autoSchedule:
autoScheduling:
  enabled: true
  initialDelayPeriod: PT15S
  periodBetweenPolls: PT10M
  timeBeforeFirstSchedule: PT5M
  scheduleSpreadPeriod: PT6H

Perhaps it's me, but I can't find the property that controls how often Reaper is running "discovery" of newly added or deleted keyspaces.
Is this a hardcoded setting?
As I read the documentation, it's none of the above.

Thanks,
Morten

**Comment by mortenjoenby** [comment]
And the real question as indicated in the title.
When a keyspace is discovered and a schedule is added, is a repair run immediately? Or not until the scheduled time is reached?

**Comment by adejanovski** [comment]
> not until the scheduled time is reached
that, yes ☝️ 

This is how it's computed: https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/service/ClusterRepairScheduler.java#L81-L90
which invoked here: https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/service/ClusterRepairScheduler.java#L78

**Comment by adejanovski** [comment]
I'll close this ticket now.
Feel free to reopen if you have more questions.

**Comment by mortenjoenby** [comment]
Hi @adejanovski .
Sorry for not getting back any sooner.
If I understand the code correctly you're adding the scheduleSpreadPeriod to the timeBeforeFirstSchedule, but it's my observation that whenever a new keyspace is created, Reaper will discover it (after ??? min or sec), and a repair is then always run after timeBeforeFirstSchedule - no matter what scheduleSpreadPeriod is set to.
The reason for bringing this up is due to a "corner-case" we have where we autodeploy a keyspace and load data. 5 minutes passes and the first repair is run. Then the application is deployed which will upgrade the keyspace. In a certain case we are dropping some tables and columns.
Then when next repair is run, it fails and blocks Reaper as it thinks these tables/columns are unknown.

**Comment by adejanovski** [comment]
Maybe a simple solution is to set the timeBeforeFirstSchedule to a day, so that you avoid the race condition you're getting into.
It doesn't seem to me like it's necessary anyway to start repairing newly created keyspaces straight away, knowing that we advise running repair once every week or so.
I think we should adjust the default there.
wdyt?

**Comment by mortenjoenby** [comment]
Hi @adejanovski .
Thanks for quick response. Yes, I agree. That was our thought as well, setting timeBeforeFirstSchedule to e.g. one day as it doesn't make sense to run immediately.
But is my observation correct, that first run should be (timeBeforeFirstSchedule + scheduleSpreadPeriod)? That's how I read the code, but it's not what we observe. And it seems that his code hasn't changed since 2.3.0.

**Comment by adejanovski** [comment]
yes, but it looks like it's only taking into account the keyspaces without schedule to compute the scheduleIndex.
So, even if you had pre-existing keyspaces with schedules, the newly added schedules will have the index starting from 0, and the first keyspace to be autoscheduled will indeed start after `timeBeforeFirstSchedule`. If you have a second one that's added in the same loop, it'll get properly delayed.

Check [here](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/service/ClusterRepairScheduler.java#L69-L79).

**Comment by mortenjoenby** [comment]
Not a developer, but I am trying to understand that logic :)
But I am not sure I understand what the scheduleIndex is in the first place?
As soon as our automation adds a new keyspace, won't it it get a repairSchedule "immediately" (how often does the discovery run?) ?
We don't create/add more keyspaces in the same automation task. We deploy our application using Terraform, and part of this is creating a keyspace. One environment = one keyspace.

**Comment by mortenjoenby** [comment]
BTW ... sligthly different topic. I posted a question for advice on Reaper on the ASF slack channel. I would really appreciate if you could point me in some direction :) I don't find the Reaper documentation "complete" on this topic.
