### ISSUE TITLE
Removal "allow filtering" from CassandraStorage.java

### ISSUE THREAD

**Issue by 18ab21** [thelastpickle/cassandra-reaper#1253]
Hi.
I would like to suggest to remove allow filtering from  CassandraStorage.java.
Reason: if you disable allow filtering in cassandra 4.1 or later(use guardtrails), cassandra-reaper will not work correctly.

Imho simple way:
1. CREATE INDEX IF NOT ESIXTS on reaper_db.repair_run (segment_state) 
2. Add index creation in java.io.cassandrareaper.storage.cassandra.MigrationXXX
3. Remove allow filtering from queries in CassandraStorage.java

**Comment by adejanovski** [comment]
This was merged in [this commit](https://github.com/thelastpickle/cassandra-reaper/commit/ed9c4da54a66547b9d8baa50a2f01fa9035f7a14)
