### ISSUE TITLE
What happens post a full repair on a particular table?

### ISSUE THREAD

**Issue by ankit-agarwal-E1304** [thelastpickle/cassandra-reaper#1268]
When running a full repair using nodetool, there is an anti-compaction at the end to segregate SStables into repaired and unrepaired sections. But when using reaper for a full repair of a table, I get this in cassandra logs - 
`Not a global repair, will not do anticompaction`

I want to understand how incremental repairs will work if no anticompaction is happening post a full repair.

Edit: I'm running repairs on apache cassandra 3.11 cluster

**Comment by adejanovski** [comment]
> When running a full repair using nodetool, there is an anti-compaction at the end

It should not be the case anymore in Cassandra 4.x as it caused a lot of performance problems.

> I want to understand how incremental repairs will work if no anticompaction is happening post a full repair.

Incremental will run on data that hasn't been repaired yet by another previous incremental repair.

**Comment by ankit-agarwal-E1304** [comment]
@adejanovski Thanks for the response.
I'm sorry, should have mentioned this in my query. I'm running this on apache cassandra 3.11 
Does that change your response?

**Comment by adejanovski** [comment]
It does not. I'd advise against mixing nodetool repairs and reaper to avoid anticompaction since it will prevent repaired data from being compacted with unrepaired data.
Also incremental repairs are buggy in 3.x and are only recommended starting with 4.0, and anticompaction is only interesting in the context of incremental repairs.

**Comment by ankit-agarwal-E1304** [comment]
@adejanovski Thanks for clarifying.
I've been working with nodetool till now and am exploring reaper for large sized clusters and scheduling auto-repairs.
Are you suggesting I use full repairs all the time for my apache cassandra 3.11.x cluster?

**Comment by ankit-agarwal-E1304** [comment]
@adejanovski With repairs using reaper, since cassandra does not perform anti-compactions, will the "percent repaired" metric in nodetool info never get updated?

**Comment by adejanovski** [comment]
It won't, that metric is only updated after anticompactions.

**Comment by ankit-agarwal-E1304** [comment]
> It won't, that metric is only updated after anticompactions.

How can i check and confirm repairs in that case?

**Comment by adejanovski** [comment]
If Reaper says repair went through without a problem, you're safe.

**Comment by burmanm** [comment]
Closing this ticket as answered. If you have further questions, please reopen.
