### ISSUE TITLE
Reaper web not displaying all running repairs

### ISSUE THREAD

**Issue by rkozlo** [thelastpickle/cassandra-reaper#1272]
For some reason webpage of reaper not displaying all of running jobs. In this example. Default 10 row displaying 4 jobs only, extending pagination to 25 and  2 more jobs on list. Missing 2 jobs which stuck(issue reported in different task #1271).
Cassandra Reaper 3.2.1 version
![reaper less](https://user-images.githubusercontent.com/44550015/216916279-0f32c538-f67f-4ae2-86de-3be745e3e8c7.png)
![reaper_more](https://user-images.githubusercontent.com/44550015/216916300-4f046fb3-f7e7-4fb8-894b-52aec6a3af30.png)

**Comment by Miles-Garnsey** [comment]
Hi @rkozlo, we did recently make some changes to status reporting in the Reaper web UI. Can you try upgrading to the latest version and let us know if you're still encountering the same issues?

**Comment by rkozlo** [comment]
@Miles-Garnsey updated reaper. I'll wait or maybe try to simulate this. Will close this if will not be any problems.

**Comment by carrouet-ipsos** [comment]
Hi, we are encountering a very similar case on 3.3.1, so this issue might not be limited to running repairs:
depending on the amount of repair displayed on a page (here 10 vs 100), we see or don't see past repairs (we were previously running on version 3.2.1 without this issue):
![image](https://github.com/thelastpickle/cassandra-reaper/assets/107992126/3f048789-c349-4e09-8545-fd03b005333e)
vs
![image](https://github.com/thelastpickle/cassandra-reaper/assets/107992126/12bc7986-9d8e-458b-801c-b1d43aa8d5e9)
(for the first screenshot, with 10 repairs displayed: on some clusters we will have a few repairs displayed, but with "gaps" in the chronological order. Then by raising the amount of repairs displayed, it will "fill in the gaps" in repairs)

**Comment by adejanovski** [comment]
@Miles-Garnsey, I think this is due to the presence of multiple clusters.
We'd need to apply the requested limit on each query (for each cluster), then merge and order the result and then apply the limit again.

**Comment by adejanovski** [comment]
@carrouet, we just merged a fix for your issue.
A beta release should be issued shortly once CI finishes that will allow you to test this. In any case, we'll release v3.3.2 with the fix tomorrow.
