### ISSUE TITLE
Schedule full repair for every keyspace

### ISSUE THREAD

**Issue by carlo4002** [thelastpickle/cassandra-reaper#1281]
Hello team,

Is there any way to schedule a full repair with POST /repair_run but instead of specifying a keyspace, can we just run it without it ?

it will be then just nodetool repair -st -tr 

Cheers,

Jean Carlo

**Comment by carlo4002** [comment]
oh I see that probably the option autoScheduling make work for me.

If I set it to true, every time I add a cluster with POST /cluster then reaper will schedule a repair for it?

**Comment by adejanovski** [comment]
Yes, autoscheduling will do that for you.
Any newly added keyspace will get a repair schedule created automatically.

Note that in Reaper each repair is just for a single keyspace, we don't support multi keyspace repairs.

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket. Feel free to reopen if you need more help.
