### ISSUE TITLE
Unable to create snapshot with spreaper

### ISSUE THREAD

**Issue by tomas-corej** [thelastpickle/cassandra-reaper#1282]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=22086141)

Hi,
I'm unable to overcome this issue when I try to create snapshot with a spreaper from CLI in a reaper POD  (**image cassandra-reaper:latest sha256:09bf27ed1bcd28494389444d1c4be8123eff276fc48f846fbe32dfee90cceab8** )

Help says:

```
usage: spreaper [-h] [--reaper-host REAPER_HOST] [--reaper-port REAPER_PORT] [--reaper-use-ssl] [-v] [-vv] [-q] [--jwt JWT] [--node NODE] [--keyspace KEYSPACE] [--name NAME] [--owner OWNER] [--cause CAUSE] take-snapshot [cluster_name]

Take a snapshot. You need to register a cluster into Reaper (add-cluster) before calling this.

positional arguments:
  take-snapshot
  cluster_name          the cluster name
```
I have a cluster registered, so when I try to create snapshot I get this error:

```
bash-5.1$ spreaper take-snapshot <cluster-name>
# Taking a snapshot on cluster '{0}', 
Traceback (most recent call last):
  File "/usr/local/bin/spreaper", line 920, in <module>
    ReaperCLI()
  File "/usr/local/bin/spreaper", line 426, in __init__
    getattr(self, command)()
  File "/usr/local/bin/spreaper", line 618, in take_snapshot
    print ("# Taking a snapshot on cluster '{0}', " 
AttributeError: 'NoneType' object has no attribute 'format'
```
python version is 3.9.15 .

Do you have  idea what is wrong ? I have tried multiple variants of spreaper calls and parameters. 

Thanks!

**Comment by adejanovski** [comment]
Hi @tomas-corej,

this is definitely a bug.
I can see that the print commands aren't correctly built [here](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/packaging/bin/spreaper#L596-L620).

I've pushed [a PR](https://github.com/thelastpickle/cassandra-reaper/pull/1299) to fix this.
