### ISSUE TITLE
Different types of repair errors posted in the Cassander Reaper logs

### ISSUE THREAD

**Issue by vchauhan81** [thelastpickle/cassandra-reaper#1292]
We are using reaper version 3.2.0 and one of our customer is seeing following errors in reaper logs. However, on reaper UI, it's showing that all reapir are completed successfully for all schema.
Is this something we need to worry about ?

Errors seen in logs - 

1.) ERROR  [2023-04-26 06:22:34,807] [ForkJoinPool-1-worker-36] i.c.j.MetricsProxy - Fail getting mbeanInfo or grabbing attributes for mbean org.apache.cassandra.metrics:type=ThreadPools,path=internal,scope=Repair#8756,name=MaxPoolSize
 .
2.) ERROR  [2023-04-26 06:23:25,919] [mailboxcluster:c875cc10-e416-11ed-8688-e5d724619861] i.c.s.RepairRunner - Executing SegmentRunner failed 
 .
3.) ERROR  [2023-04-26 07:18:45,936] [mailboxcluster:36942460-e423-11ed-8688-e5d724619861] i.c.s.RepairRunner - handleResult called with a segment state (RUNNING) that it should not have after segmentRunner has tried a repair 
.

**Comment by adejanovski** [comment]
Hi, 

such errors can happen for a variety of reasons and segments get rescheduled afterwards with a timeout extension. As long as the repairs are progressing and finishing as expected, then there's nothing to worry about.

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket. Feel free to re-open if you still have questions.
