### ISSUE TITLE
Reaper URL not accessing - 

### ISSUE THREAD

**Issue by nagcassandra** [thelastpickle/cassandra-reaper#1303]
Hi Team,

I have installed Reaper on an AWS EC2 node located in the private zone. To access the Reaper Web Interface, I am using tunnelling. However, after successfully Reaper installation, when I attempted to perform a curl request on port 8080 on the host where Reaper is installed, I received a "Forbidden access" error message.

For your reference, here is the curl command I used:
**# curl http://127.0.0.1:8080/
Forbidden access. Please login to access this page**

I would greatly appreciate any assistance in resolving this issue.

**Comment by adejanovski** [comment]
Try accessing `http://127.0.0.1:8080/webui`.
It should redirect you to the login page.

**Comment by nagcassandra** [comment]
Hi @adejanovski 

I have attempted to access "curl http://127.0.0.1:8080/webui" but did not receive a response from the server. Here is an example of the command I used:

[root@centos]# curl http://127.0.0.1:8080/webui/ 
[root@centos]# 
I also tried opening the link in a browser, but it did not work. The page took some time to load and eventually timed out.

**Comment by adejanovski** [comment]
And did you try to access http://127.0.0.1:8080 in the browser instead of curling it? Could you try http://127.0.0.1:8080/login.html as well?

**Comment by nagcassandra** [comment]
Hi @adejanovski 

Yes, I attempted to access "http://127.0.0.1:8080/" through the browser, but it took a long time and eventually timed out. I also tried "http://127.0.0.1:8080/login.html" but it did not work.

Thanks
Nagendra

**Comment by Miles-Garnsey** [comment]
> Yes, I attempted to access "http://127.0.0.1:8080/" through the browser, but it took a long time and eventually timed out. I also tried "http://127.0.0.1:8080/login.html" but it did not work.

Did you have an SSH tunnel up to allow access to your remote server? 

Can you please provide the output of the command `# curl -v http://127.0.0.1:8080/` and confirm that you are running this from your EC2 instance and not your local machine?

**Comment by mjshariati98** [comment]
I had the same problem and /webui/login.html works for me. Hope it helps you too but I believe this should get fixed.

**Comment by Miles-Garnsey** [comment]
We do have a ticket open to redirect the root URL back to /webui [here](https://github.com/thelastpickle/cassandra-reaper/issues/1261). 

@nagcassandra, we haven't heard back on this, so I will close the ticket for now, please comment and we will re-open it if you are still experiencing issues.
