### ISSUE TITLE
Ensure Reaper can call the new Management API async notifications endpoints

### ISSUE THREAD

**Issue by Miles-Garnsey** [thelastpickle/cassandra-reaper#1325]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=34006288)

We are attempting to provide an alternative to JMX using the HTTP API in the management API project. 

As a part of this work, we need to ensure that notification based logic has non-JMX equivalents. The new logic should be implemented in the [HttpCassandraManagementProxy](https://github.com/thelastpickle/cassandra-reaper/blob/84a742ae50fac1751556b0ceebb1413f65308e58/src/server/src/main/java/io/cassandrareaper/management/http/HttpCassandraManagementProxy.java#L60).

We want to ignore diagnostic events as a part of this work. As a result, the only functions we want to touch are related to the `NotificationListener` interface, which has a single method - 

```
  public void handleNotification(Notification notification, Object handback);
```

When the `connect` method is called in the JmxCassandraManagementProxy, it calls `mbeanServerConn.addNotificationListener(ObjectNames.STORAGE_SERVICE, proxy, null, null);` which sets up a listener for events from the storage service.

When those events are received, they are processed by handleNotification` [here](https://github.com/thelastpickle/cassandra-reaper/blob/56394b3eddc59cebb6b14d945032a1926d8f44f2/src/server/src/main/java/io/cassandrareaper/management/jmx/JmxCassandraManagementProxy.java#L778), which filters them down to just those of type "progress". These are progress notifications for repairs.

The only notifications we need to provide via management API are those from the storage service with `type == "repair"`. Others relate to diagnostic events. The listeners for the storage service are added [here](https://github.com/thelastpickle/cassandra-reaper/blob/56394b3eddc59cebb6b14d945032a1926d8f44f2/src/server/src/main/java/io/cassandrareaper/management/jmx/JmxCassandraManagementProxy.java#L284-L288) in the JMX implementation. They are handled [here](https://github.com/thelastpickle/cassandra-reaper/blob/56394b3eddc59cebb6b14d945032a1926d8f44f2/src/server/src/main/java/io/cassandrareaper/management/jmx/JmxCassandraManagementProxy.java#L778) in the JMX implementation, so the HTTP impl will need to basically shim things out to that point so that arguments to `SegmentRunner.handle()` ([here](https://github.com/thelastpickle/cassandra-reaper/blob/56394b3eddc59cebb6b14d945032a1926d8f44f2/src/server/src/main/java/io/cassandrareaper/service/SegmentRunner.java#L469)) appear to `SegmentRunner.handle()` as though they come from JMX, not HTTP.

**Definition of done**

- [ ] We have an HTTP equivalent for `addNotificationListener`, which needs to set up a new thread to poll the repairs endpoint on management API.
- [ ] We have a new `handleNotification` method in the HttpCassandraManagementProxy, which needs to eventually trigger a callback to the `SegmentRunner`s as implementors of the `repairStatusHandler` interface. (see e.g. `processNewApiNotification` in the JMX implementation.) 
- [ ] The relevant HTTP endpoints are called using the new Management API Java client (which should be auto-generated by the management api release process).
- [ ] When the state of a watched object changes, the state change is added to the history of the object. This ensures that all state changes (even for states which last for only ms in between polls) are propagated down the wire.

**Note**

Because we are ignoring the diagnostic events here, we do not need to look at any other instances of `addNotificationListener` for other mbean/event types.

**Comment by burmanm** [comment]
Some background first, the current method of submitting a repair does:

``ShimLoader.instance.get().getStorageService().repairAsync(keyspace, repairSpec);``

The way we want to invoke these if of course doing it in the async fashion, which requires us to create a Runnable and submit it as async, something along the lines of:

``return submitJob("repair", repairOperation, async);`` (the last async is bool which just joins the thread if we want a blocking operation).

This executes it through the ``JobExecutor``, which then keeps a track of jobs that have been executed (currently with a cache size of 1000 items). One can query the status of these jobs as they update their status to ``ERROR, COMPLETED, WAITING`` and there's a REST API that allows to fetch these. Each job has unique ID which was provided to the caller when they invoked the job. That is the way for job submitters to verify if the job has been completed, by polling the endpoint.  For example, cass-operator task controller polls them and updates their status this way:

https://github.com/k8ssandra/cass-operator/blob/master/internal/controllers/control/cassandratask_controller.go#L617

Now, there's no limitation of those job statuses (there just wasn't any need for other than COMPLETED/ERROR/..). If we wish to add more and more details, feel free. I know Reaper currently accepts more, but I have no idea if it actually needs all those progress reports from Cassandra.

Now to the notification part. There are two things to build here, one is on the Reaper side and one on the management-api side. On the reaper side, there needs to be a polling method that checks for the status of the job until it has finished (or make a thread until all the current jobs that are running are finished, by keeping some internal state of the submitted jobs). That would then write to the ``processNewApiNotification(Notification notification)`` or similar method as currently (thus not requiring more work on the Reaper side). 

On the management-api side, we can just subscribe with the ``addNotificationListener()`` to JMX events if we wish. Something like this patch (you need to make it prettier / more general, but it'll work for now, there's no other ProgressEvents emitted by Cassandra than these repair ones):

```patch
diff --git a/management-api-agent-common/src/main/java/com/datastax/mgmtapi/NodeOpsProvider.java b/management-api-agent-common/src/main/java/com/datastax/mgmtapi/NodeOpsProvider.java
index fe0d9ab..461f861 100644
--- a/management-api-agent-common/src/main/java/com/datastax/mgmtapi/NodeOpsProvider.java
+++ b/management-api-agent-common/src/main/java/com/datastax/mgmtapi/NodeOpsProvider.java
@@ -38,6 +38,9 @@ import java.util.Set;
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.ExecutionException;
 import java.util.stream.Collectors;
+import javax.management.Notification;
+import javax.management.NotificationFilter;
+import javax.management.NotificationListener;
 import javax.management.openmbean.CompositeDataSupport;
 import javax.management.openmbean.TabularData;
 import org.apache.cassandra.auth.AuthenticatedUser;
@@ -52,6 +55,7 @@ import org.apache.cassandra.repair.RepairParallelism;
 import org.apache.cassandra.repair.messages.RepairOption;
 import org.apache.cassandra.service.StorageProxy;
 import org.apache.cassandra.utils.Pair;
+import org.apache.cassandra.utils.progress.ProgressEventType;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
@@ -733,7 +737,7 @@ public class NodeOpsProvider {
   }
 
   @Rpc(name = "repair")
-  public void repair(
+  public String repair(
       @RpcParam(name = "keyspaceName") String keyspace,
       @RpcParam(name = "tables") List<String> tables,
       @RpcParam(name = "full") Boolean full)
@@ -756,7 +760,47 @@ public class NodeOpsProvider {
         // incremental repairs will fail if parallelism is not set
         repairSpec.put(RepairOption.PARALLELISM_KEY, RepairParallelism.PARALLEL.getName());
       }
-      ShimLoader.instance.get().getStorageService().repairAsync(keyspace, repairSpec);
+
+      // Since Cassandra provides us with a async, we don't need to use our executor interface for this.
+      int repairJobId = ShimLoader.instance.get().getStorageService().repairAsync(keyspace, repairSpec);
+
+      final Job job = service.createJob("repair");
+      ShimLoader.instance.get().getStorageService().addNotificationListener((notification, handback) -> {
+        // https://github.com/apache/cassandra/blob/600f4d9a690dbd887d5e6298fe67e6bba982033d/src/java/org/apache/cassandra/utils/progress/jmx/JMXNotificationProgressListener.java#L26
+        if(notification.getType().equals("progress")) {
+          Map<String, Integer> data = (Map<String, Integer>) notification.getUserData();
+          ProgressEventType progress = ProgressEventType.values()[data.get("type")];
+          switch(progress) {
+            // TODO Finish these
+            case START:
+              break;
+            case PROGRESS:
+              break;
+            case ERROR:
+              job.setError(new RuntimeException(notification.getMessage()));
+              job.setStatus(Job.JobStatus.ERROR);
+              job.setFinishedTime(System.currentTimeMillis());
+              break;
+            case ABORT:
+              break;
+            case SUCCESS:
+              break;
+            case COMPLETE:
+              job.setStatus(Job.JobStatus.COMPLETED);
+              job.setFinishedTime(System.currentTimeMillis());
+              break;
+            case NOTIFICATION:
+              break;
+          }
+          service.updateJob(job);
+        }
+      }, (NotificationFilter) notification -> {
+        // Not real code, needs some casting first
+        int repairNo = Integer.parseInt(((String) notification.getSource()).split(":")[1]);
+        return repairNo == repairJobId;
+      }, null);
+
+      return job.getJobId();
     }
   }
 
diff --git a/management-api-agent-common/src/main/java/com/datastax/mgmtapi/util/JobExecutor.java b/management-api-agent-common/src/main/java/com/datastax/mgmtapi/util/JobExecutor.java
index f51e4f9..b76ada6 100644
--- a/management-api-agent-common/src/main/java/com/datastax/mgmtapi/util/JobExecutor.java
+++ b/management-api-agent-common/src/main/java/com/datastax/mgmtapi/util/JobExecutor.java
@@ -19,29 +19,37 @@ public class JobExecutor {
   public Pair<String, CompletableFuture<Void>> submit(String jobType, Runnable runnable) {
     // Where do I create the job details? Here? Add it to the Cache first?
     // Update the status on the callbacks and do nothing else?
-    final Job job = new Job(jobType);
-    jobCache.put(job.getJobId(), job);
 
+    final Job job = createJob(jobType);
     CompletableFuture<Void> submittedJob =
         CompletableFuture.runAsync(runnable, executorService)
             .thenAccept(
                 empty -> {
                   job.setStatus(Job.JobStatus.COMPLETED);
                   job.setFinishedTime(System.currentTimeMillis());
-                  jobCache.put(job.getJobId(), job);
+                  updateJob(job);
                 })
             .exceptionally(
                 t -> {
                   job.setStatus(Job.JobStatus.ERROR);
                   job.setError(t);
                   job.setFinishedTime(System.currentTimeMillis());
-                  jobCache.put(job.getJobId(), job);
-                  return null;
+                  updateJob(job);
                 });
 
     return Pair.create(job.getJobId(), submittedJob);
   }
 
+  public Job createJob(String jobType) {
+      final Job job = new Job(jobType);
+      jobCache.put(job.getJobId(), job);
+      return job;
+  }
+
+  public void updateJob(Job job) {
+      jobCache.put(job.getJobId(), job);
+  }
+
   public Job getJobWithId(String jobId) {
     return jobCache.getIfPresent(jobId);
   }

```

**Comment by Miles-Garnsey** [comment]
Merged to main [here](https://github.com/thelastpickle/cassandra-reaper/commit/8a26f9d858ba9ee52fc55d8e2d343d1e69845a66).
