### ISSUE TITLE
Implement compaction methods in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1340]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35567380)

## Definition of Done
- [x] the `forceKeyspaceCompaction()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getCompactions()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getCompactionParameters()` method is implemented in the HttpCassandraManagementProxy class

**Comment by Miles-Garnsey** [comment]
Merged to main.
