### ISSUE TITLE
Implement topology methods in the HttpCassandraManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1341]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35567388)

## Definition of Done
- [x] the `getLocalEndpoint()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getSimpleStates()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getAllEndpointStates()` method is implemented in the HttpCassandraManagementProxy class

**Comment by Miles-Garnsey** [comment]
Merged to main.
