### ISSUE TITLE
Implement getClusterName in the in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1342]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35567392)

## Definition of Done
- [x] the `getClusterName()` method is implemented in the HttpCassandraManagementProxy class

**Comment by Miles-Garnsey** [comment]
Removing item `getCurrentStreams` as it is tracked under #1391. Removing `getPartitioner` as it is tracked under #1381. Only getClusterName is left, renaming ticket to reflect that. 

getClusterName was completed under #1359 [here](https://github.com/thelastpickle/cassandra-reaper/pull/1359) and merged to integration branch. Marking ticket complete.
