### ISSUE TITLE
Implement repair related methods in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1343]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35567395)

## Definition of Done
- [x] the `cancelAllRepairs()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `triggerRepair()` method is implemented in the HttpCassandraManagementProxy class

**Comment by Miles-Garnsey** [comment]
Merged to main.
