### ISSUE TITLE
Implement schema methods in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1344]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=35571825)

## Definition of Done
- [x] the `getKeyspaces()` method is implemented in the HttpCassandraManagementProxy class
- [x] the `getColumnFamilyName()` method is implemented in the HttpCassandraManagementProxy class

**Comment by Miles-Garnsey** [comment]
Merged to main [here](https://github.com/thelastpickle/cassandra-reaper/commit/8a26f9d858ba9ee52fc55d8e2d343d1e69845a66).
