### ISSUE TITLE
Dashes are not respected.

### ISSUE THREAD

**Issue by joaquincasares** [thelastpickle/cassandra-reaper#137]
Here I used the `docker-compose-1` data center:

<img width="808" alt="screen shot 2017-07-07 at 2 52 50 pm" src="https://user-images.githubusercontent.com/545666/27981610-2332ca80-6354-11e7-82e7-f036722774eb.png">

But only `docker` appears within the UI:

<img width="846" alt="screen shot 2017-07-07 at 2 52 28 pm" src="https://user-images.githubusercontent.com/545666/27981609-20998926-6354-11e7-9284-fec06d6c57d0.png">

Here I used the `reaper-cluster` `cluster_name`:

<img width="427" alt="screen shot 2017-07-07 at 3 06 56 pm" src="https://user-images.githubusercontent.com/545666/27981612-276469ce-6354-11e7-94e0-e827f684b602.png">

But both the `Clusters` page:

<img width="196" alt="screen shot 2017-07-07 at 3 06 43 pm" src="https://user-images.githubusercontent.com/545666/27981611-25a76118-6354-11e7-9d4e-25130b114739.png">

And `Scheduling` page:

<img width="573" alt="screen shot 2017-07-07 at 3 07 21 pm" src="https://user-images.githubusercontent.com/545666/27981613-290ed638-6354-11e7-888c-e0cca7a052e9.png">

Have removed the dash and rendered the name as `reapercluster`.

**Comment by adejanovski** [comment]
I had a fix in another branch for the datacenter and rack names, which I just applied in master too.
I fixed the cluster name as well in master. 
Let me know how it works and please close the ticket accordingly.

**Comment by adejanovski** [comment]
This is fixed in master, closing.
