### ISSUE TITLE
Implement un-ticketed methods in the HttpManagementProxy

### ISSUE THREAD

**Issue by Miles-Garnsey** [thelastpickle/cassandra-reaper#1375]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37579387)

When ticketing this work we originally missed a number of methods which need to be implemented in Reaper. This was because we based those tickets on the management API ones but some methods were already present in management API and didn't need to be re-implemented.

# Definition of done
The required methods are as follows:

- [x] #1377
- [x] #1378
- [x] #1379
- [x] #1380
- [x] #1381
- [x] #1382
- [x] #1383
- [x] #1384
- [x] #1385
- [ ] #1386
- [x] #1387
- [x] #1388
- [x] #1389
- [x] #1390
- [ ] #1391
- [x] #1392

**Comment by adejanovski** [comment]
Closing this ticket as I've added all the subtask to the existing epic (#1326) .
