### ISSUE TITLE
Implement getTokens() in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1377]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37693416)

Method signature:

`public List<BigInteger> getTokens()`

**Comment by emerkle826** [comment]
There is a bug in the merged PR for this. I have addressed it in https://github.com/thelastpickle/cassandra-reaper/pull/1373

**Comment by Miles-Garnsey** [comment]
Merged to main [here](https://github.com/thelastpickle/cassandra-reaper/commit/8a26f9d858ba9ee52fc55d8e2d343d1e69845a66).
