### ISSUE TITLE
Implement getRangeToEndpointMap(String keyspace) in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1378]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37693641)

Method signature:

`Map<List<String>, List<String>> getRangeToEndpointMap(String keyspace)`

**Comment by Miles-Garnsey** [comment]
@emerkle826 you have this PR marked as draft but it is in status Ready for Review - can you align this?

**Comment by emerkle826** [comment]
It's ready for review now. I needed to merge the Management API PR first, publish a new openapi client, and then update the dependency in the pom here. That's all finally done now.

**Comment by Miles-Garnsey** [comment]
Merged to main [here](https://github.com/thelastpickle/cassandra-reaper/commit/8a26f9d858ba9ee52fc55d8e2d343d1e69845a66).
