### ISSUE TITLE
Implement getPendingCompactions() in the HttpManagementProxy

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#1382]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=37693681)

Method signature:
`public int getPendingCompactions() throws JMException`

**Comment by adejanovski** [comment]
This is currently blocked, waiting for #1396

**Comment by adejanovski** [comment]
The HttpMetricsProxy was partially implemented in order to get the metric we're interested in.
That allowed unblocking this ticket.

**Comment by Miles-Garnsey** [comment]
Merged to main [here](https://github.com/thelastpickle/cassandra-reaper/commit/8a26f9d858ba9ee52fc55d8e2d343d1e69845a66).
