### ISSUE TITLE
ARM docker image [feature request]

### ISSUE THREAD

**Issue by smatvienko-tb** [thelastpickle/cassandra-reaper#1407]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=38624456)

Currently, [`thelastpickle/cassandra-reaper:3.3.3`](https://hub.docker.com/layers/thelastpickle/cassandra-reaper/3.3.3/images/sha256-edf98052e003820d8b66d0fa83f31693fd864d559f431de9b44b30a72b36d096?context=explore) is built only for `linux/amd64` architecture.

![image](https://github.com/thelastpickle/cassandra-reaper/assets/79898499/de445825-5a2c-47ea-a3db-7587dd22c973)

The[ Cassandra image ](https://hub.docker.com/layers/library/cassandra/4.1.3/images/sha256-3c272d54ff753fd4017256fd9763f0f81dc1702c61b381b8d819b288b7e4a083?context=explore) supports **ARM** architecture.
![image](https://github.com/thelastpickle/cassandra-reaper/assets/79898499/fd71c6a8-4a63-4465-8d4c-d70d98d8b3f8)

I would like to use `ARM` images** to run `cassandra-reaper` as a sidecar with `Cassandra` on `linux/arm64` machines like AWS Graviton (m7g, t4g, etc) in Kubernetes.

This will cut some costs and energy consumption. And might save the Planet from global warming ;)
#ARM #CostSaving

I also will be happier to run my [Thingsboard](https://thingsboard.io) deployment with Cassandra + Reaper completely on ARM.
![image](https://github.com/thelastpickle/cassandra-reaper/assets/79898499/62111042-60a0-4fd0-8092-1c7d1e54273c)

Looking forward for your updates on ARM build.

Thank you!

**Comment by adejanovski** [comment]
Hi @smatvienko-tb,

I have started working on this recently. Just need to polish my branch and push it :)

**Comment by smatvienko-tb** [comment]
Hey, @adejanovski !
Do you need any help on this topic?

**Comment by adejanovski** [comment]
Thanks @smatvienko-tb, the PR is ready for review actually.
