### ISSUE TITLE
HttpManagementConnectionFactory does not use the same instance for all calls

### ISSUE THREAD

**Issue by burmanm** [thelastpickle/cassandra-reaper#1414]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=38977664)

When connectImpl / connectAny is called from the HttpManagementConnectionFactory, it creates a new instance of HttpManagementProxy every time. This is different from the behavior of the JMXConnectionFactory and might cause additional memory usage if multiple instances of HttpManagementProxy are created for the same node.

**Comment by Miles-Garnsey** [comment]
Merged to the integration branch. Closing.
