### ISSUE TITLE
JMX credentials per cluster

### ISSUE THREAD

**Issue by peterpramb** [thelastpickle/cassandra-reaper#143]
Currently only one set of JMX credentials can be specified in the reaper configuration, meaning that multiple clusters with different JMX credentials require multiple reaper installations.

This is somewhat related to #70. Would be great if one reaper instance could support multiple clusters.

**Comment by adejanovski** [comment]
That's true, it would indeed be much smarter to take this out of config and into storage instead.
We need to finish the fault tolerant branch first and then we'll add this.

**Comment by rustyrazorblade** [comment]
If we go down this route (I agree we should), we should probably also require encryption keys be set up on the reaper box and never store plain text creds in storage.

**Comment by adejanovski** [comment]
I finally implemented this in the config file to avoid dealing with encryption.
We'll see if we want to change this in the future, but operationally it'll be simpler this way.

The change is in PR #316.

**Comment by peterpramb** [comment]
Rather late, but confirmed that it's working as expected, thank you.

But please correct the documentation:

```The cluster name must match the one defined in the cassandra.yaml file```

what is wrong, as Reaper lowercases cluster names and strips off special characters before trying to match the configuration.
