### ISSUE TITLE
"Forbidden access. Please login to access this page", when try to access the webUI on 8080 port

### ISSUE THREAD

**Issue by anupamReaper** [thelastpickle/cassandra-reaper#1435]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=43411634)

Hi,
we have deployed reaper in open shift container and reaper service is running fine. We have also created service and its route but when we are trying to access the route link "http://reaper-ids-data-cluster.apps.idopadev15.insight.local:8080/webui/", its throwing this error "**Forbidden access. Please login to access this page**". We have used 8080 port for network communication. Please give some suggestions on how to access the web ui of reaper.

**Comment by atish-andhare** [comment]
I am getting the same error with the latest release
[cassandra-reaper-3.4.0-release.tar.gz](https://github.com/thelastpickle/cassandra-reaper/releases/download/3.4.0/cassandra-reaper-3.4.0-release.tar.gz)

@adejanovski

**Comment by Miles-Garnsey** [comment]
Hi folks, I'm trying to reproduce login related errors [here](https://github.com/thelastpickle/cassandra-reaper/issues/1438). in relation to this particular issue, we'd need more information about the deployment of Reaper. 

If you check my comment on the linked ticket, I've been unable to reproduce this issue using a docker compose deployment from the `master` branch. 

To diagnose this issue further, you may want to 
1. Compare your shiro.ini and environment against the one I've provided in the linked ticket.
2. Provide more info on where your images are coming from and any relevant k8s deployments etc. If you are not using a containerised deployment then please provide details on how Reaper has been installed and configured.
4. Attempt to login using spreaper (see linked ticket for details on how to do so) and try logging in again through the web ui.

**Comment by Miles-Garnsey** [comment]
I've just done another test using the tarball install.

If I run the following commands in a fresh docker container:

```
wget https://github.com/thelastpickle/cassandra-reaper/releases/download/3.4.0/cassandra-reaper-3.4.0-release.tar.gz
tar -zxvf cassandra-reaper-3.4.0-release.tar.gz
java -jar server/target/cassandra-reaper-3.4.0.jar server resource/cassandra-reaper.yaml
```
I am then able to log in using the /webui link.

We will need more information to reproduce any strange behaviour you folks are seeing. Please update this ticket if the behaviour continues and we can re-open it.
