### ISSUE TITLE
Schedule 2 repairs for the same cluster and keyspace with different incrementalRepair value

### ISSUE THREAD

**Issue by rsoletob** [thelastpickle/cassandra-reaper#144]
Hi all!

We are trying to schedule two repairs for a keyspace, one with incrementalRepair=true and other with incrementalRepair=false, to follow the recommended ways explained [here](http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsRepairNodesWhen.html), but it fails with this error message: 
`A repair schedule already exists for cluster "testcluster", keyspace "testkeyspace", and column families: []`

Inside code, this message is located [here](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/main/java/com/spotify/reaper/resources/CommonTools.java#L249). Could be possible to change this behaviour to include incrementalRepair property in comparison?

**Comment by adejanovski** [comment]
Hi @rsoletob ,

I've created PR #145 to fix your issue.
Can you build the branch and check that it does what you're expecting ?

Thanks

**Comment by rsoletob** [comment]
It's fine, thanks for everything. :+1:
