### ISSUE TITLE
webui login not working in docker

### ISSUE THREAD

**Issue by Sumit0789** [thelastpickle/cassandra-reaper#1450]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=47508674)

Not redirecting to home page even after successfully login.

<img width="1502" alt="Screenshot 2023-12-14 at 6 14 50 AM" src="https://github.com/thelastpickle/cassandra-reaper/assets/111736044/099d0422-07f4-4f22-adfb-06f99d45e3eb">

spec:
  containers:
  - env:
    - name: REAPER_JMX_AUTH_USERNAME
      value: cassandra
    - name: REAPER_JMX_AUTH_PASSWORD
      value: cassandra
    - name: REAPER_STORAGE_TYPE
      value: cassandra
    - name: REAPER_CASS_CLUSTER_NAME
      value: recommendation
    - name: REAPER_CASS_CONTACT_POINTS
      value: '[10.10.0.1,10.10.0.2,10.10.0.3]'
    - name: REAPER_CASS_KEYSPACE
      value: reaper_db
    - name: REAPER_CASS_AUTH_USERNAME
      value: cassandra
    - name: REAPER_CASS_AUTH_PASSWORD
      value: cassandra
    - name: REAPER_CASS_AUTH_ENABLED
      value: "true"
    - name: REAPER_AUTH_ENABLED
      value: "true"
    - name: CRYPTO_SYSTEM_PROPERTY_SECRET
      value: REAPER_JMX_KEY
    - name: REAPER_JMX_KEY
      value: encryptionPassReaper
    - name: DREAPER_JMX_KEY
      value: encryptionPassReaper
    - name: REAPER_LOGGING_ROOT_LEVEL
      value: DEBUG
    - name: REAPER_AUTH_USER
      value: reaper
    - name: REAPER_AUTH_PASSWORD
      value: reaper
    image: thelastpickle/cassandra-reaper:latest

**Comment by SkylineCookieMonster** [comment]
Have the same issue from 3.4.0 (3.3.4 still works) for running Reaper on Linux machines in sidecar mode (bare metals, no docker)

**Comment by Sumit0789** [comment]
not running with side car but in eks(kubernetes)

**Comment by adejanovski** [comment]
This issue is due to [these lines](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/docker/shiro.ini#L19-L28) in the default shiro.ini file.
While it's not consistently happening, it seems to be frequent enough that we remove those lines for now.
