### ISSUE TITLE
Cassandra Reaper strips dashes and underscore from metrics tags

### ISSUE THREAD

**Issue by Nassz** [thelastpickle/cassandra-reaper#1452]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=48403122)

Dear Community, 

Cassandra Reaper 3.4.0 still has this issue raised in PR  https://github.com/thelastpickle/cassandra-reaper/pull/1267 it strips underscores from metric tags, nevertheless support for underscored DC/RAC was added in PR https://github.com/thelastpickle/cassandra-reaper/pull/1129

Here is the log from cassandra-reaper.log :
`Triggering repair for keyspace "local_gateway" `

Here is the Metric : 
`curl -v http://localhost:8081/prometheusMetrics | grep -i gateway `
> io_cassandrareaper_service_SegmentRunner_repairing_count{cluster="**cassandracloud**",keyspace="**localgateway**",host="null",} 74.0

Thus as you see the names of Cluster and Keyspaces are stripped.

@adejanovski  could you please review the PR https://github.com/thelastpickle/cassandra-reaper/pull/1267 and build a new version of Reaper?

**Comment by adejanovski** [comment]
Merged 👍 
You'll get a new beta release once CI completes.

**Comment by Nassz** [comment]
but I guess some fixes to CI to be done as well :) 
https://github.com/thelastpickle/cassandra-reaper/actions/runs/7387942552/job/20099970403

`+ ccm create test -v binary:3.0.25
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.1/x64/bin/ccm", line 7, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'`

@adejanovski please check :)

**Comment by Nassz** [comment]
@adejanovski  When do you plan to push a new release, not a 'beta' one?
