### ISSUE TITLE
improve system services

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#147]
Looks like FPM makes it easy to set up system services.  We can even build an OSX installer it seems.  Wild stuff.

https://fpm.readthedocs.io/en/latest/source/pleaserun.html

**Comment by adejanovski** [comment]
Could you be more specific on what you'd want to achieve here ? 
We already have system services with the rpm and deb packages generated by FPM.

**Comment by rustyrazorblade** [comment]
We have system services but we write them ourselves.  FPM can make it easier to manage.

**Comment by adejanovski** [comment]
@rustyrazorblade , I'll go ahead and close this ticket. 
Feel free to reopen and comment if you think it's worth pursuing this.
