### ISSUE TITLE
web UI can not login when Authentication is activate

### ISSUE THREAD

**Issue by JerryKwan** [thelastpickle/cassandra-reaper#1472]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=54102099)

when upgrading from version 3.3.1 to version 3.4.0, web UI failed to work. login failed all the time. and the page are redirected to /webui/login.html again and again.
when digger deeper, it seems like the API /login returns status code 204 'No Content'
But when using the command line spreaper, it succeed.
Anyone can explain what may caused that problem?

**Comment by SkylineCookieMonster** [comment]
@JerryKwan had the same issue and 3.5.0 is just released which contained a fix for this. I upgraded to 3.5.0 and saw that it was solved for me.

**Comment by adejanovski** [comment]
Yes, we fixed this by reverting some changes that were made in the shiro.ini file a while ago. Not sure why it's failing (as it's not happening in all deployments), but v3.5.0 indeed has the fix.

**Comment by JerryKwan** [comment]
@adejanovski 
Thanks for fixing this issue
