### ISSUE TITLE
API REST repair_run segmentCountPerNode

### ISSUE THREAD

**Issue by xaviergainon** [thelastpickle/cassandra-reaper#1475]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=54536577)

Hi, 

I try to create a repair with a specific segmentCount value through the rest aPI but
 the result is systematically the creation of a repair with 14 segments which corresponds to the number of nodes in my cluster.
 
 
I tested with segmentCount=128 and segmentCountPerNode=128 but I still ended up with 14 segments

 repair_run?clusterName=mycluster&keyspace=mykeyspace&owner=myowner&segmentCountPerNode=128&segmentCount=128
 
 the return api :
 {
"cause": "no cause specified",
"owner": "myowner",
"id": "baf6d810-d4e6-11ee-9f4b-310c6a3ce6d7",
"state": "NOT_STARTED",
"intensity": 0.8999999761581421,
"duration": null,
"cluster_name": "mycluster",
"column_families":[
"path",
"file_chunk"
],
"keyspace_name": "mykeyspace",
"incremental_repair": true,
"total_segments": 14,
"repair_parallelism": "PARALLEL",
"segments_repaired": 0,
"last_event": "no events",
"nodes":[],
"datacenters":[],
"blacklisted_tables":[],
"repair_thread_count": 1,
"repair_unit_id": "315c1600-d4e2-11ee-9227-8967019589c6",
"segment_timeout": 30,
"adaptive_schedule": false,
"end_time": null,
"creation_time": "2024-02-26T20:36:33Z",
"start_time": null,
"pause_time": null,
"current_time": "2024-02-26T20:36:33Z",
"estimated_time_of_arrival": null
}

Thank for your help

**Comment by adejanovski** [comment]
Hi, 

Incremental repairs cannot be performed in a subrange mode, Cassandra won't allow this due to the overhead of anticompaction.
As such, the segment count per node will be ignored by Reaper and a single segment will be created per node in the cluster.

**Comment by xaviergainon** [comment]
HI,

Thank you for this feedback, I understand better
