### ISSUE TITLE
Segment count stuck at # of node regardless of settings

### ISSUE THREAD

**Issue by ostefano** [thelastpickle/cassandra-reaper#148]
I have been testing cassandra-reaper, and regardless of the settings in `cassandra-reaper.yaml` or what I input when creating a repair, the number of total segments is stuck at the number of nodes currently part of the cluster. Is that intended? Admittedly I have been testing incremental repairs only.

**Comment by ostefano** [comment]
Ok, I see. Incremental repairs do not allow selecting the number of segments and default to number of nodes.

**Comment by ostefano** [comment]
Is that because it is not possible to pre-compute which segments are already repaired?

**Comment by adejanovski** [comment]
Hi @ostefano,

Incremental repair cannot run in subrange mode and shouldn't even run on the primary range.
The only efficient way of running it is to run it on each node for all its tokens at the same time.
This is why Reaper doesn't allow to set the number of segments and creates only one "fake" segment per node in the cluster.

Short explanation is that subrange incremental repair would trigger a lot of anticompaction, which would make it mostly unusable and likely create a very high number of SSTables.

**Comment by ostefano** [comment]
Hi @adejanovski ,

I see, makes perfect sense. Thanks for the full explanation.
