### ISSUE TITLE
Support Keystore configuration for communicating with multiple Management API deployments

### ISSUE THREAD

**Issue by emerkle826** [thelastpickle/cassandra-reaper#1490]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=59246149)

In a centralized Reaper K8s deployment, where one Reaper instance will manage repairs for multiple Cassandra clusters spread across K8s clusters, Reaper will need to be configured to communicate with each of the Management APIs running in the Cassandra clusters. When these communication links are secured (https instead of http), Reaper will have to manage certificate/truststores/keystores for these communication links.

The Reaper pod will get every keystore/trustore pair for each cluster mounted as a separate volume.
The directory structure will look as follows:

```java
/etc/encryption/mgmt
   |
   -- cluster1
           |
           -- keystore.jks
           |
           -- truststore.jks
   |
   -- cluster2
           |
           -- keystore.jks
           |
           -- truststore.jks
```

This will require a restart of the Reaper pod each time a cluster is added or removed.

The hot reloading feature that's already built in will handle refreshing the certificates on rotation.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-10) by [Unito](https://www.unito.io)
┆Issue Number: REAP-10

**Comment by adejanovski** [comment]
@burmanm, here's the ticket about attaching the encryption materials to Reaper for the registered clusters.
