### ISSUE TITLE
Segment count for incremental repairs remains 1 per node regardless of the segment count specified (3.2.0 + )

### ISSUE THREAD

**Issue by Valgar** [thelastpickle/cassandra-reaper#1502]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=61610099)

When specifying segment count for incremental repairs in repair, the value seems to be ignored (including any defaults set in config)

Unsure if this is expected behaviour, as segment count/node can be specified for full repairs. 

This causes failures and backoffs during incrementals on large segments.

Screenshots of launching incremental repair and specifying segment count/node and the resulting segment count of the running repair (3 node cluster 1 per node only, instead of 64 per node)

<img width="2567" alt="reaper3 2 0-incremental-repair-config" src="https://github.com/thelastpickle/cassandra-reaper/assets/8887689/bbb6e587-727f-4651-8ccb-ae81bddaabc7">
<img width="2805" alt="reaper3 2 0-incremental-repair-running" src="https://github.com/thelastpickle/cassandra-reaper/assets/8887689/5e6872ac-bb70-4022-ba5e-379dc2a724ef">

**Comment by adejanovski** [comment]
We will introduce a new "Subrange incremental" type of repair to cover this case.
I think there are cases where a global incremental will work better than the subrange version, and vice versa.
