### ISSUE TITLE
ClassCastException in RepairParametersMapper when using H2 database

### ISSUE THREAD

**Issue by smarsching** [thelastpickle/cassandra-reaper#151]
There is a bug in the RepairParametersMapper when using the H2 database (instead of PostgreSQL). The code tries to cast Object[] to String[], which results in a ClassCastException:

> java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
>         at com.spotify.reaper.storage.postgresql.RepairParametersMapper.map(RepairParametersMapper.java:33)
>         at com.spotify.reaper.storage.postgresql.RepairParametersMapper.map(RepairParametersMapper.java:28)
>         at org.skife.jdbi.v2.Query$4.munge(Query.java:183)
>         at org.skife.jdbi.v2.QueryResultSetMunger.munge(QueryResultSetMunger.java:41)
>         at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1344)
>         at org.skife.jdbi.v2.Query.fold(Query.java:173)
>         at org.skife.jdbi.v2.Query.list(Query.java:82)
>         at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:253)
>         at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:43)
>         at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:43)
>         at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:212)
>         at org.skife.jdbi.v2.sqlobject.SqlObject$3.intercept(SqlObject.java:127)
>         at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$3580ecc6.getRunningRepairsForCluster(<generated>)
>         at com.spotify.reaper.storage.PostgresStorage.getOngoingRepairsInCluster(PostgresStorage.java:356)
>         at com.spotify.reaper.service.SegmentRunner$1.initialize(SegmentRunner.java:175)
>         at com.spotify.reaper.service.SegmentRunner$1.initialize(SegmentRunner.java:171)
>         at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:100)
>         at com.spotify.reaper.service.SegmentRunner.canRepair(SegmentRunner.java:302)
>         at com.spotify.reaper.service.SegmentRunner.runRepair(SegmentRunner.java:184)
>         at com.spotify.reaper.service.SegmentRunner.run(SegmentRunner.java:101)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
>         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
>         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:748)

I believe that this problem is similar to a problem that existed in the RepairScheduleMapper that was fixed with 15f4755d58f730b6f6ee52c86bad9faa1ee66abf.

**Comment by michaelsembwever** [comment]
Thanks for the PR. Has been merged.
