### ISSUE TITLE
How to change defult admin password. 

### ISSUE THREAD

**Issue by starkh02** [thelastpickle/cassandra-reaper#1530]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=87994224)

Hello, i want to change default admin password, but i don't understand how do it.
I installed cassandra-reaper locally not docker 
In FAQ you wrote
Copy the default shiro.ini file and adapt it overriding the “users” section :
where i need copy shiro.ini file ? I tried copy to /etc/cassandra-reaper/shiro.ini or /etc/cassandra-reaper/config/shiro.ini . Then change password , and it does not work.
I tried change this part of config 
accessControl:
  sessionTimeout: PT10M
  shiro:
    iniConfigs: ["classpath:shiro.ini"]
to 
accessControl:
  sessionTimeout: PT10M
  shiro:
    iniConfigs: ["/etc/cassandra-reaper/shiro.ini"]

I tried to find shiro.ini in the system and result is empty.
Please help me

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-194) by [Unito](https://www.unito.io)
┆Issue Number: REAP-194

**Comment by adejanovski** [comment]
you need to put `file:` in front of your shiro.ini path, like it's done [here](https://github.com/thelastpickle/cassandra-reaper/blob/ee8530765f42763446083d6e28c7e316a7048a96/src/server/src/main/docker/configure-webui-authentication.sh#L32) for example.

**Comment by starkh02** [comment]
Thank you, i tried , but it does not work 
I create folder  iniConfigs: ["file:/etc/cassandra-reaper/config/shiro.ini"] and copy default shiro.ini file, then change admin password 
 [root@test ~]# cd /etc/cassandra-reaper/config/
[root@test config]# cat shiro.ini | grep admin
# default authentication is the following hardcoded admin user
admin = qweASD123, operator
but it does not work and password is default
May be rights on file or folder are wrong ?
[root@test config]# 
ll

-rw-r--r--. 1 root root 2390 nov 20 18:22 shiro.ini
[root@test cassandra-reaper]# ll config
-rw-r--r--. 1 root root 2390 nov 20 18:22 shiro.ini

**Comment by starkh02** [comment]
Thank you very much , its work!
