### ISSUE TITLE
Configuration of two datacenters environment having three Cassandra nodes each

### ISSUE THREAD

**Issue by Ritu-Thakur** [thelastpickle/cassandra-reaper#154]
<Using C3.11>
Having issues in starting up repair for 2 datacenters - 3 Cassandra nodes each.
DC1 - IP1 (seed node), IP2, IP3
DC2 - IP4(seed node), IP5, IP6

We want to run reaper on seed nodes i.e. IP1 and IP4?
How should we create keyspace reaper_db?
In cassandra-reaper.yaml, what should be the value in contactPoints and jmxports?

**Comment by michaelsembwever** [comment]
@ritu0407, which version/branch of reaper are you using?

> We want to run reaper on seed nodes i.e. IP1 and IP4?

You mean you want to run two reaper instances?

> In cassandra-reaper.yaml, what should be the value in contactPoints and jmxports?

Provide for contactPoints  a few of the ipaddresses of the nodes in the same datacenter as reaper is running, and/or the datacenter you wish reaper to connect to (LOCAL_ONE and LOCAL_QUORUM requests).

jmxports doesn't need to be specifiied if all nodes are running jmx on the default 7199.

**Comment by Ritu-Thakur** [comment]
@michaelsembwever , Thanks for replying.
We are using the latest version 0.6.1.
Yes we want to run two reaper instances to distribute load. Is it the right approach for two dcs environment?

**Comment by michaelsembwever** [comment]
> Yes we want to run two reaper instances to distribute load. Is it the right approach for two dcs environment?

This is not yet supported. It's currently being developed in the `ft-reaper-improvements-final` branch, which is stable, undergone a lot of testing, and soon to be merged to master.

**Comment by Ritu-Thakur** [comment]
@michaelsembwever 
Do you know when is ft-reaper-improvements-final branch going to be merged in master?

**Comment by rustyrazorblade** [comment]
@ritu0407 the branch has been merged into master.  See the Multi-DC section on http://cassandra-reaper.io/docs/
