### ISSUE TITLE
Switch packages to use io.cassandra_reaper

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#172]
@michaelsembwever brought up that keeping com.spotify is a recognition of the original work, and that works for me.  let's just update the FAQ explaining why it's like that.

**Comment by zznate** [comment]
This is not feasible long term if we intend to publish artifacts on Maven Central. Archive coordinates have to point to a domain name to which one can be recognized as affiliated with.

**Comment by rustyrazorblade** [comment]
Good point Nate.  Renaming this issue to reflect the work to be done.

**Comment by rustyrazorblade** [comment]
Alternatively we could use io.cassandra_reaper since the domain is up now.
