### ISSUE TITLE
discuss adding java formatter

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#182]
It would be nice to run our code through a formatter with a set of conventions we can agree on and not have to nit over style.  Something like Google's Java formatter: https://github.com/google/google-java-format, but it doesn't have to be exactly their conventions / decisions.  Style should be, in my opinion, standardized and removed from the discussion when looking at a patch.  It adds noise to the discussion and focuses on the appearance of the code rather than the quality.

**Comment by michaelsembwever** [comment]
I don't think it should matter which tool we use, there's a few out there, but that the efforts of any commit are measurable.
Re-applying a formatter isn't a sustainable approach: once the code is cleaned up then a PR can simply be blocked until code style meets requirements.

Measuring code style can be done in a number of different ways: checkstyle, pmd, findbugs, sonar; which all plugin into maven. I believe @adejanovski already has set up sonar reporting for Reaper? And i believe checkstyle, pmd, and findbugs all can plug into sonar?

**Comment by rustyrazorblade** [comment]
I'm not pushing for any particular tool, just that something is picked and we roll with it.  I was using the google one as an example.

**Comment by michaelsembwever** [comment]
> I'm not pushing for any particular tool, just that something is picked and we roll with it. I was using the google one as an example.

Think we might be speaking past each other there? I don't think we need to pick any tool because any tool that is used should only be used the once. What i would say is more important is that we have code style rules and metrics in place. 

(For example with these things in place, after we're done one pass of code formatting, then there's no excuse that the code style deteriorates again… We also  want to avoid a code base that's littered with ongoing automated formatting commits)

**Comment by rustyrazorblade** [comment]
> I don't think we need to pick any tool because any tool that is used should only be used the once. 

I disagree.  Any other project that I've worked on has required the use of the code formatter to ensure the project stays formatted properly.  Otherwise you end up with a bunch of nit comments over formatting, and that's just unnecessary noise. 

> We also want to avoid a code base that's littered with ongoing automated formatting commits

I don't see formatting commits as a negative thing, so I'm going to disagree with you on this.  Ideally any PR that goes up has been run through the formatter already.  People can squash those commits, but I really don't care if they do or don't.  Perfectly clean history isn't something I attach value to.

**Comment by michaelsembwever** [comment]
Work in progress in https://github.com/thelastpickle/cassandra-reaper/pull/198
