### ISSUE TITLE
investigate moving to gradle

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#183]
I just moved CDM to gradle and found it to be a lot nicer to work with than maven.  I'm going to port our pom.xml to gradle's build file so we can see what it looks like.  One thing that really sold me was how easy it was to write tasks that ran shell commands.  For instance:

```bash
task buildBinary(type: Exec) {
    commandLine "cat", "src/main/sh/execute.sh", "build/libs/cdm.jar"
    standardOutput = new FileOutputStream('bin/cdm')
}
```

I found it to be pretty obvious what was happening here.  Adding tasks to build the docs, docker images, artifacts, etc, would be similarly easy.

**Comment by adejanovski** [comment]
I think we're happy with Maven so far and don't see a good reason to invest in moving to Gradle.
Closing the ticket.
