### ISSUE TITLE
Hung repair segments are sometimes not aborted

### ISSUE THREAD

**Issue by smarsching** [thelastpickle/cassandra-reaper#185]
Sometimes it happens that a hung repair segment is not aborted, thus keeping other repair segments (possible from other repair runs) from running.

In the logfile the following message shows up:

> SegmentRunner declined to repair segment … because one of the hosts (…) was already involved in a repair

It took me some time to figure out why this happens, but I think I understand the issue now:

Usually, Cassandra Reaper will use the timeout to determine when a repair segment is stuck and abort the segment when it takes too long. Obviously, the segment will not be aborted if Cassandra Reaper is restarted before the timeout. Usually, this is not a problem because on startup, Cassandra Reaper iterates through all running segments of all running jobs and restart them. When the job has been paused (or aborted), this will not happen (which makes sense because the segment should not be restarted in this case).

The issue is that the stale entry for the "running" segment will still keep repairs on the affected nodes from being aborted, possibly blocking future repair runs. I believe that this is due to a bug in the implementations of the`getOngoingRepairsInCluster(String)` method in `CassandraStorage` and `PostgresStorage`. The implementation in `MemoryStorage` does not have this bug, so the problem described above should not appear when using `MemoryStorage`.

I will try to put together a PR which fixes this issue.

**Comment by adejanovski** [comment]
Fixed by bdb0bd1eba1c5c06c512461fb17829daaa1872bd
