### ISSUE TITLE
Unrecognized field at: datacenterAvailability

### ISSUE THREAD

**Issue by adisharoon** [thelastpickle/cassandra-reaper#206]
When starting cassandra-reaper with 'datacenterAvailability: ALL' defined in /etc/cassandra-reaper/cassandra-reaper.yaml, the service stops with the following error:

/etc/cassandra-reaper/cassandra-reaper.yaml has an error:
  * Unrecognized field at: datacenterAvailability
    Did you mean?:
      - dataSourceFactory
      - repairIntensity
      - repairParallelism
      - incrementalRepair
      - database
        [17 more]

The documentation and errors describe this as a supported option.  What's going on?

**Comment by adejanovski** [comment]
Hi, it is supported as of 0.7.0 and won't work with 0.6.2.
