### ISSUE TITLE
Failed to establish JMX connection across datacenters

### ISSUE THREAD

**Issue by adisharoon** [thelastpickle/cassandra-reaper#211]
I'm trying to track down why I'm getting consistent issues communicating with nodes outside the private network in which reaper is running.  The UI shows "Not available" for those datacenters, and the logs contain errors stating that reaper failed to establish a JMX connection.  And yet, I can telnet to the JMX port and even open jconsole to those nodes from the system reaper is on just fine (via an SSH tunnel).

It could be that reaper is attempting to communicate with them over the private network interface somehow.  These are EC2 instances, with datacenters in different regions, if that helps.  The public addresses show up in the log and UI, however.

I've tried using a reaper in each region/datacenter with datacenterAvailability on EACH, but that doesn't seem to have helped... each reaper still gets errors that it can't connect to nodes in other datacenters.

It's highly possible I'm just ignorant and am doing something wrong, but I've run out of leads that I can see.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-305) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-305

**Comment by adejanovski** [comment]
If you're running an AWS multi region cluster, you need to turn on the address translator in the Reaper yaml file : 
`useAddressTranslator: true`

I reckon it's currently missing from the yaml samples and it is undocumented on [cassandra-reaper.io](http://cassandra-reaper.io) :'(
I'll fix that ASAP.

You shouldn't open JMX on the cross region link though, and you'll need to have one Reaper instance in each DC. You can use either `LOCAL` or `EACH` as `datacenterAvailability`, `EACH` providing more safety as you're guaranteed to use remote nodes metrics before starting a segment (whether repair is running and the number of pending compactions) , while `LOCAL` will only require the metrics from the local DC, using remote DCs metrics if available.
`EACH` should work fine if you have one Reaper in each DC and your cluster is small (<=10 nodes per DC). Otherwise `LOCAL` might be a better option for now.

**Comment by adisharoon** [comment]
Thanks!  I'm still not quite working however.  I'm running with the address translator on in EACH mode now, with a reaper in each datacenter/region.  However, in the logs, a given datacenter is still complaining that it can't reach hosts in other datacenters by JMX.  I also noticed that adjusting jmxConnectionTimeoutInSeconds doesn't seem to change the frequency of those errors like I thought it might.  I'm almost starting to think that certain config options just aren't being respected.  Other options definitely are, such as the reaper keyspace name.

**Comment by adejanovski** [comment]
By default JMX isn't exposed on the public IP, only the private IP, so it's expected that Reaper in DC1 cannot communicate with nodes in DC2. This is where the Cassandra backend is used to have Reaper in DC1 able to get metrics from DC2, and coordinate with potential Reaper instances there.

Do you see progress in your repairs ? Can you share how many nodes there are in both DCs ?

If you see that Reaper complains about not being able to get all metrics (having some messages like these is expected) and the repair doesn't show progress, switch to `datacenterAvailability: LOCAL` and see if that improves progress.

**Comment by adisharoon** [comment]
Even with three reapers each running in LOCAL mode in one of three DCs, the cassandra-reaper.log contains exceptions like:

```
ERROR  [2017-09-28 15:34:58,256] [pool-11-thread-2] c.s.r.c.JmxProxy - Failed to establish JMX connection to xx.xx.xxx.xxx:7199
INFO   [2017-09-28 15:34:58,259] [pool-11-thread-2] c.s.r.c.JmxConnectionFactory - Unreachable host
com.spotify.reaper.ReaperException: Failure when establishing JMX connection
```

Where xx.xx.xxx.xxx is a host in a *different* DC.  

Additionally, the web ui displays details for one DC (the one I started reaper first in, presumably) but all others display 'Not available'.  The below screenshot is from the eu-central-1 region - but note how it only displays the us-west-2 region.  

![reaper-screenshot](https://user-images.githubusercontent.com/11983158/30976477-7e4ab456-a43a-11e7-9c0f-fc0ed1bd67ff.png)

This is the config file from the eu-central-1 region, with the IPs and password redacted: [cassandra-reaper.txt](https://github.com/thelastpickle/cassandra-reaper/files/1341494/cassandra-reaper.txt)

I do see progress in the repairs.  So the core functionality appears to be working.

**Comment by adisharoon** [comment]
I just had a thought - should the cassandra keyspace that is backing the cassandra-reaper have a replication factor that crosses DCs or should each reaper get its own keyspace?  Right now I have a single keyspace for reaper replicated across all DCs.

**Comment by adejanovski** [comment]
This is the right setup : all reapers should connect to the same reaper_db keyspace that needs to be replicated across all DCs.
Having "unreachable host" exceptions is expected too (although I think we should mute those exceptions in the logs because that's gonna happen in cross region clusters).

It's odd that you're getting only details from a single DC because the info is coming from a single node...
Could you run "nodetool gossipinfo" and share the output here once you've obfuscated ip addresses ? You could also send it to me directly if you prefer : alex[at]thelastpickle.com

Also, which version of Cassandra are you running ?

Thanks

**Comment by adisharoon** [comment]
Here's the gossipinfo output:

[gossipinfo.txt](https://github.com/thelastpickle/cassandra-reaper/files/1345751/gossipinfo.txt)

We're actually running [Elassandra](http://elassandra.readthedocs.io/en/latest/architecture.html), a Cassandra fork that includes elasticsearch, so there are some extra fields in the gossipinfo output that have to do with elasticsearch indices.  The Cassandra version is 3.11.0.

**Comment by adejanovski** [comment]
Thanks for the gossipinfo output. 

It looks like the `X2` entry is messing up with the parsing by adding a `/` which is used to split the data by endpoint.
I'll add a fix so that it works with Elassandra too.

**Comment by aslanbakirov** [comment]
I am sorry, @adejanovski . maybe I missed that point, why "You shouldn't open JMX on the cross region link though, and you'll need to have one Reaper instance in each DC"? If I will have one Reaper per DC, is it gonna be able to make cross-dc repair?

**Comment by adejanovski** [comment]
Hi @aslanbekirov,

opening the JMX port on cross region links is considered a security flaw, unless maybe you turn on encryption.
To avoid having to do this and starting with Reaper 0.7, you can start one Reaper in each region that will communicate with the local nodes only. Both Reaper will exchange informations and perform leader election on segments using the Cassandra backend.

To answer your question precisely : if you have a Reaper in each DC, running at least Reaper 0.7 with the Cassandra backend for storage, it will handle cross dc repairs. 
Prefer `datacenterAvailability: LOCAL` for now in the reaper yaml file.

**Comment by aslanbakirov** [comment]
Thx a lot @adejanovski for quick response. yes, I am running cassandra as a backend. We have on prem cluster across 2 DCs. Is there any advantage running one reaper instance per DC over one reaper instance per cluster, besides security flaw , you mentioned?

**Comment by adejanovski** [comment]
Fault tolerance is the only one that comes to my mind. 
But we really designed this feature for multi region deployments where JMX couldn't be accessible on the cross DC link.

Having a single Reaper that can access all nodes is the simplest setup you can have. If you can achieve this without security issues, then go for it ;)

**Comment by adejanovski** [comment]
Closing this ticket since it's been inactive for years now.
