### ISSUE TITLE
Unable schedule repairs

### ISSUE THREAD

**Issue by jaibheem** [thelastpickle/cassandra-reaper#22]
Hello I am using cassandra-reaper for repairs. I am able to run repair but I am unable to schedule the repairs. 
Please see the attachement,  I am unable to select Add schedule, the option is greyed out. 

I am using the default config from : resource/cassandra-reaper.yaml
<img width="1427" alt="screen shot 2016-11-21 at 11 47 46 pm" src="https://cloud.githubusercontent.com/assets/7039921/20515272/ae8fcbcc-b045-11e6-895a-34608a8125b2.png">

**Comment by mgobec** [comment]
You are missing an AM or PM next to the Start time. Its buggy it doesn't set it to something by default.

**Comment by adejanovski** [comment]
Hi Jai, 

You should have no "--" left in the "Start time" input field indeed.
Can you follow Matija's suggestion to see if that fixes your problem ?

Thanks

**Comment by jaibheem** [comment]
@mgobec @adejanovski  Thanks for the help
It would be good if it display AM/PM in that filed like how we display dd/mm/yyyy for the date

**Comment by adejanovski** [comment]
Sure thing, I'll see if I can patch the UI to get a default value. 
Did you get it to work by providing a value manually ?

**Comment by jaibheem** [comment]
@adejanovski it works perfectly fine 👍

**Comment by adejanovski** [comment]
Great !
Thanks @mgobec for the help !

I'll keep the issue opened until we've patched the UI.

**Comment by kapilibm** [comment]
Hi 
I am trying to input date/time in the "Start Time" field given in above screenshot but its throwing **invalid schedule_trigger_time** error on the UI.This is the format i am following **08/08/2017, 3:40PM**
 Can anyone specify what is the correct date format.

**Comment by gfediere** [comment]
Hi, as provided in the documentation date should be: _Give date values in ISO format, e.g. “2015-02-11T01:00:00”_

**Comment by aby786** [comment]
![image](https://user-images.githubusercontent.com/38696609/39195409-c886b83c-47ad-11e8-9a19-d2c4f31c3acb.png)

I am still getting issues when i use format as 04/22/2018 03:00PM and as per documentattion it is mm/dd/yyyyand in log it gives message
i.c.r.RepairScheduleResource - cannot parse data string: 04/22/2018 03:00PM
java.lang.IllegalArgumentException: Invalid format: "04/22/2018 03:00PM" is malformed at "/22/2018 03:00PM"

**Comment by aby786** [comment]
Just tried below format for ISO and worked, i think documentation should have example or something and also at starttime we should have some hover to mention what should be format
2018-04-24T15:30:00

**Comment by adejanovski** [comment]
The datetime picker was replaced with a more intuitive one a while ago.
