### ISSUE TITLE
changelog is not up to date

### ISSUE THREAD

**Issue by hkroger** [thelastpickle/cassandra-reaper#230]
The changelog of 0.7.1:
https://github.com/thelastpickle/cassandra-reaper/blob/0.7.1/changelog.txt

Show the last version as 0.6.2.

**Comment by michaelsembwever** [comment]
i'm thinking we just delete the changelog, and write it manually for each release.

as the commit log isn't that long between releases writing it manually won't be that difficult and will be better targeted for the user. (developers will also be more inclined to read a shorter commit log).

this would seem a more pragmatic approach to take, at least in the short-term.

@adejanovski

**Comment by hkroger** [comment]
I'm happy as long as the change log is readable somewhere (and up to date)

**Comment by rustyrazorblade** [comment]
The commit log is a bit... verbose and probably too noisy.  I think using the issues associated with a version/milestone in GitHub is a more practical approach.  That's each enough to script out and we can make it part of the release process.

**Comment by adejanovski** [comment]
Changelog was updated in the latest release using this : https://github.com/lalitkapoor/github-changes

We're going to see how we can integrate this in the release process so that it gets updated automatically.
