### ISSUE TITLE
Port native_transport_port

### ISSUE THREAD

**Issue by CassDBA** [thelastpickle/cassandra-reaper#236]
Hi Team,

can someone help exposing native_transport_port in cassandra reaper yaml file.

**Comment by adejanovski** [comment]
Hi @bhisey,

you can add a `port:` setting at the same level than the `contactPoints:` one.
Follow the sample here : https://github.com/composable-systems/dropwizard-cassandra/blob/master/src/test/resources/smoke/basic.yml

**Comment by CassDBA** [comment]
Thank you, even found authorization on same link :)

authProvider:
    type: plainText
    username: cassandra
    password: xxxxxxxxx
