### ISSUE TITLE
Add development/build documentation

### ISSUE THREAD

**Issue by mrwulf** [thelastpickle/cassandra-reaper#242]
Compiling a jar is easy enough (with IntelliJ), but knowing that make, fpm, npm, and bower are required to build a deployable package is less obvious. Converting to gradle as in #183 seems like it could make this easier.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-315) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-315

**Comment by rustyrazorblade** [comment]
Agreed, this is quite a pain at the moment.  Have you looked at the build instructions that utilize docker?  http://cassandra-reaper.io/docs/download/docker/

**Comment by adejanovski** [comment]
We have docker containers providing build capabilities along with the appropriate docs.
