### ISSUE TITLE
update gitignore

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#264]
I just did a build using the docker method and there's a bunch of files that were generated that aren't covered by gitignore.  

I'm assuming all of them should be ignored, but I didn't touch any of this so I'd rather not break anything.

```text
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/server/src/main/resources/assets/deps.js
	modified:   src/server/src/main/resources/assets/index.html
	modified:   src/server/src/main/resources/assets/index.js
	modified:   src/server/src/main/resources/assets/repair.html
	modified:   src/server/src/main/resources/assets/repair.js
	modified:   src/server/src/main/resources/assets/schedules.html
	modified:   src/server/src/main/resources/assets/schedules.js
	modified:   src/ui/app/jsx/navbar.jsx
```

**Comment by michaelsembwever** [comment]
These are the generated files for the UI that have been checked into the git repository. So they can't be put into `.gitignore`

My opinion here is not to put generated files into version control (and to then put them into `.gitignore`)
To do this means that the `-Pbuild-ui` profile becomes part of the default build, and building requires `npm` and `bower` to be installed.
I have no problem with making those that want to build reaper have to have these installed. They are pretty normal build packages now-a-days.

**Comment by rustyrazorblade** [comment]
Docker also covers the entire build process if people don't want to mess with npm / bower, etc.  I'm in favor of removing them from version control and updating the docs to make it clear you either need to do -Pbuild-ui or use docker.

**Comment by adejanovski** [comment]
If you guys want to remove those, then we need to remove the build-ui profile as well and make building the UI part of the standard build process.
I still think not everyone wants to mess with bower, npm or even docker, but I seem to be the only one with that opinion, so let's move on with the majority.

**Comment by michaelsembwever** [comment]
The `build-ui` profile has been removed, it is now part of the default build.
