### ISSUE TITLE
better feedback in UI for repair failure and history

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#27]
The current UI is so minimal it is frequently not very helpful.

**Comment by elsmorian** [comment]
If I could add to this -  a manual "retry" option would be great - we have had occasions where temporary network issues have meant that Reaper can't find any nodes for a certain range and fails, it would be really handy to be able to get it to pick off where it left off after this error

**Comment by michaelsembwever** [comment]
This was solved in https://github.com/thelastpickle/cassandra-reaper/pull/302
