### ISSUE TITLE
Feature Request: CF-aware segmentation

### ISSUE THREAD

**Issue by eriksw** [thelastpickle/cassandra-reaper#279]
For keyspaces with a few extremely large CFs and a large number of comparably microscopic CFs, the time to do a whole-keyspace repair with a large number of segments (needed to make progress within acceptable timeouts on the big CFs) is nontrivially impacted by the time that gets spent coordinating the tiny-range repairs of each of the smaller CFs.

Manually creating a couple different runs, one for each of the very large CFs and one for the enumerated small CFs works around this, but it's an annoying maintenance burden to have to re-do the schedules in reaper every time a CF is added or dropped.

It'd be nice if reaper enumerated CFs and their sizes when generating segments and made it so that each segment of the repair covers (by rough estimates) the same number of bytes, whether that's a very tiny range in a single large CF or `-pr`-equivalent of a large number of small CFs.

**Comment by adejanovski** [comment]
Hi @eriksw,

that's a very interesting point and I guess it's pretty much what is described in #280.
I've added this to the 1.1.0 milestone and will close this ticket as a duplicate.
I'll post your full comment there to make the intent clear.

Thanks !
