### ISSUE TITLE
Reaper triggers then immediately aborts repair

### ISSUE THREAD

**Issue by eriksw** [thelastpickle/cassandra-reaper#285]
When creating a repair run manually using the UI, reaper starts a repair command but then immediately aborts it gets stuck on `Failed to renew lead on segment`.

I dropped all reaper_db tables before starting cassandra-reaper (v1.0.1) for the first time, and am running only one reaper instance which has jmx access to all nodes.

    Nov 27 23:09:39 presence-cassandra-1-reaper-1 java[9873]: INFO   [dw-28 - POST /repair_run?clusterName=presence&keyspace=presence&owner=sre&tables=client_macs&repairParallelism=PARALLEL&incrementalRepair=true] i.c.s.RepairUnitService - create new repair unit for cluster 'presence', keyspace 'presence', column families: [client_macs], nodes: [] and datacenters: []
    Nov 27 23:09:40 presence-cassandra-1-reaper-1 java[9873]: INFO   [dw-28 - POST /repair_run?clusterName=presence&keyspace=presence&owner=sre&tables=client_macs&repairParallelism=PARALLEL&incrementalRepair=true] c.d.d.c.u.UUIDs - PID obtained through native call to getpid(): 9873
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [dw-25 - PUT /repair_run/0bbd3a40-d3c8-11e7-9220-e77c0745b02b?state=RUNNING] i.c.r.RepairRunResource - modify repair run state called with: id = 0bbd3a40-d3c8-11e7-9220-e77c0745b02b, state = Optional.of(RUNNING)
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [dw-25 - PUT /repair_run/0bbd3a40-d3c8-11e7-9220-e77c0745b02b?state=RUNNING] i.c.r.RepairRunResource - Starting run 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [dw-25 - PUT /repair_run/0bbd3a40-d3c8-11e7-9220-e77c0745b02b?state=RUNNING] i.c.s.RepairManager - Starting a run with id #0bbd3a40-d3c8-11e7-9220-e77c0745b02b with current state 'NOT_STARTED'
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [dw-25 - PUT /repair_run/0bbd3a40-d3c8-11e7-9220-e77c0745b02b?state=RUNNING] i.c.s.RepairManager - scheduling repair for repair run #0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b] i.c.s.RepairRunner - Running segment for range (-6148914691236517202,-6148914691236517202]
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b] i.c.s.RepairRunner - Next segment to run : 0bbd6151-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.j.JmxProxy - Triggering repair of range (-6148914691236517202,2] for keyspace "presence" on host 10.7.32.110, with repair parallelism parallel, in cluster with Cassandra version '2.1.17' (can use DATACENTER_AWARE 'true'), for column families: [client_macs]
    Nov 27 23:09:48 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.SegmentRunner - Repair for segment 0bbd6151-d3c8-11e7-9220-e77c0745b02b started, status wait will timeout in 36000000 millis
    Nov 27 23:09:51 presence-cassandra-1-reaper-1 java[9873]: INFO   [pool-1-thread-1] i.c.s.SegmentRunner - Postponing segment 0bbd6151-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:09:51 presence-cassandra-1-reaper-1 java[9873]: INFO   [pool-1-thread-1] i.c.s.SegmentRunner - Aborting repair on segment with id 0bbd6151-d3c8-11e7-9220-e77c0745b02b on coordinator 10.7.32.110
    Nov 27 23:10:48 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:11:48 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:12:48 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 27 23:13:48 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b

Looking at metrics for the cassandra cluster, it appears that the "aborted" repair is in fact still going on.

Addendum:

Reaper is still stuck, logging `Failed to renew lead on segment` repeatedly, even after the "aborted" repair completed and all compaction died down.

**Comment by eriksw** [comment]
It eventually tried again, but as before it immediately "aborted" the repair (despite leaving the real repair running):

    Nov 28 00:08:49 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:09:49 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:09:49 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.SegmentRunner - Repair command 4 on segment 0bbd6151-d3c8-11e7-9220-e77c0745b02b returned with state NOT_STARTED
    Nov 28 00:09:49 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:09:49 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6151-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Could not release lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:09:51 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b] i.c.s.RepairRunner - Running segment for range (-6148914691236517202,-6148914691236517202]
    Nov 28 00:09:51 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b] i.c.s.RepairRunner - Next segment to run : 0bbd6152-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:09:52 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6152-d3c8-11e7-9220-e77c0745b02b] i.c.j.JmxProxy - Triggering repair of range (2,6148914691236517206] for keyspace "presence" on host 10.7.34.45, with repair parallelism parallel, in cluster with Cassandra version '2.1.17' (can use DATACENTER_AWARE 'true'), for column families: [client_macs]
    Nov 28 00:09:52 presence-cassandra-1-reaper-1 java[9873]: INFO   [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6152-d3c8-11e7-9220-e77c0745b02b] i.c.s.SegmentRunner - Repair for segment 0bbd6152-d3c8-11e7-9220-e77c0745b02b started, status wait will timeout in 36000000 millis
    Nov 28 00:09:58 presence-cassandra-1-reaper-1 java[9873]: INFO   [pool-1-thread-1] i.c.s.SegmentRunner - Postponing segment 0bbd6152-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:09:58 presence-cassandra-1-reaper-1 java[9873]: INFO   [pool-1-thread-1] i.c.s.SegmentRunner - Aborting repair on segment with id 0bbd6152-d3c8-11e7-9220-e77c0745b02b on coordinator 10.7.34.45
    Nov 28 00:10:52 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6152-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b
    Nov 28 00:11:52 presence-cassandra-1-reaper-1 java[9873]: ERROR  [presence:0bbd3a40-d3c8-11e7-9220-e77c0745b02b:0bbd6152-d3c8-11e7-9220-e77c0745b02b] i.c.s.CassandraStorage - Failed to renew lead on segment 0bbd3a40-d3c8-11e7-9220-e77c0745b02b

**Comment by adejanovski** [comment]
Hi @eriksw,

could you check the content of the `reaper_db.leader` table when you get such errors ?
Failure to renew the lead means that the lead wasn't "taken" or isn't considered as such. 
Taking the lead should happen when the instance picks the segment to start working on it. There a lead will be created using an LWT with a TTL of 3 minutes.
The lead is renewed regularly during the segment processing, using another LWT that expects the row to be present in the `leader` table. 

What is odd is that a failure to take the lead would prevent the segment from being picked...

Do you have a single datacenter or several ? 
If you have several, is the reaper_db keyspace replicated on all datacenters ?
Do you run an incremental repair or a full one ?

I would gladly take the full log files by email : reaper[at]thelastpickle.com

Thanks !

**Comment by eriksw** [comment]
This is single-dc (`datacenterAvailability: ALL`), although the cluster has in the past been migrated  a couple times by way of adding and decommissioning DC's. 

I dropped all CFs in the reaper_db keyspace before starting reaper 1.0.1 for the first time.

Are there logs beyond this that you would want to see the next time I attempt using reaper in this situation? (I'll collect the leader CF as well.):

    logging:
      level: INFO
      loggers:
        io.dropwizard: WARN
        org.eclipse.jetty: WARN
      appenders:
        - type: console
          logFormat: "%-6level [%t] %logger{5} - %msg %n"

**Comment by eriksw** [comment]
Both during and after a re-test (including drop and re-create), with the same outcome, there was never anything in `reaper_db.leader` at all:

    $ cqlsh -e 'select * from reaper_db.leader'

     leader_id | last_heartbeat | reaper_instance_host | reaper_instance_id
    -----------+----------------+----------------------+--------------------

    (0 rows)

Here's the create, it's identical to the keyspace being repaired:

    CREATE KEYSPACE reaper_db WITH replication = {'class': 'NetworkTopologyStrategy', 'us-east-1_presence-1': '3'} AND durable_writes = true;

Here's the cassandra storage configuration:

    cassandra:
      clusterName: "Presence"
      contactPoints: ["presence-cassandra-1.redacted.redacted.redacted"]
      keyspace: reaper_db
      loadBalancingPolicy:
        type: tokenAware
        shuffleReplicas: true
        subPolicy:
          type: dcAwareRoundRobin
          localDC:
          usedHostsPerRemoteDC: 0
          allowRemoteDCsForLocalConsistencyLevel: false

Other things that might be of note:

*   This did not occur with reaper 0.6.2.
*   We are using racks in the cluster.
*   In this case, replication=racks=total nodes, but I'm seeing this same issue on another rack-using cluster where we have 2 nodes per rack instead of one.

Aside: I've had no issues repairing this cluster using the memory backend, and following on from suspicion that there's something wrong with cassandra storage in reaper 1.0.x, have switched yet another cluster's reaper that's having tons of "reported that it is involved in a repair, but there is no record..." issues over to h2 to see if that helps.

**Comment by adejanovski** [comment]
Hi @eriksw,

sorry it took me very long to follow up on this ticket.
The only reason I see for those problems to happen is if your Cassandra nodes aren't correctly synchronized on clocks. 
Leader election has been introduced in 1.0.0 indeed (didn't exist in 0.6.2) and the TTL for records in the `leader` table is 3 minutes.
Following the code path, I see that leader election takes place correctly has segments are started, but the RepairManager checks segments with no leaders regularly to prevent stuck repairs, and aborts them accordingly. 
So 6s after a record has been created in the `leader` table, the repair manager cannot see it.

Enabling DEBUG level logging could be helpful to determine what's precisely happening between the start of the repair and the abortion.

Thanks

**Comment by adejanovski** [comment]
@spike01 : apparently Reaper gets a `COMPLETE` jmx notification but never got the `SUCCESS` notification, nor the `START` one, so the status of the segment is left at `NOT_STARTED` in the database. 

Is there anything in the Cassandra logs showing a failure of some sort for those repair sessions ?
Could you send the full reaper logs to reaper[at]thelastpickle.com ?

Thanks

**Comment by adejanovski** [comment]
Fixed
