### ISSUE TITLE
Add Run Now button for scheduled repairs

### ISSUE THREAD

**Issue by elsmorian** [thelastpickle/cassandra-reaper#290]
I have had the situation where it would be really handy to trigger a scheduled repair at that time, and not either have to wait for it to schedule automatically, or go in and enter the run time so it starts shortly.

A Run Now button on schedule repairs would be really handy!

**Comment by mrwulf** [comment]
Same as #241 ?

**Comment by elsmorian** [comment]
Aha, sorry managed to miss this in my search. Yup that would cover it!

**Comment by adejanovski** [comment]
Closing as duplicate of #241
