### ISSUE TITLE
if endTime is set, so must startTime be set (v1.0.1)

### ISSUE THREAD

**Issue by ludekdolejsky** [thelastpickle/cassandra-reaper#291]
I am unfortunately seeing issue similar to #281 even after upgrading to 1.0.1.

I am running one Reaper per DC and the `endTime is set, so must startTime be set` error is happening occasionally (I'd say less frequently than prior to upgrading to 1.0.1).

please see attached full log files from both DCs:
[logs.zip](https://github.com/thelastpickle/cassandra-reaper/files/1530109/logs.zip)

data causing the issue (you can see they come from dc2 log file):
```
cqlsh> select segment_start_time, segment_end_time from reaper_db.repair_run where id=231ee1e0-d871-11e7-8db9-7bb3e751dc82 and segment_id=23212c16-d871-11e7-8db9-7bb3e751dc82;

 segment_start_time | segment_end_time
--------------------+---------------------------------
               null | 2017-12-04 00:36:45.261000+0000

(1 rows)
```

everything goes back to normal when I fix the data manually by running:
```
update reaper_db.repair_run set segment_end_time=null where id=231ee1e0-d871-11e7-8db9-7bb3e751dc82 and segment_id=23212c16-d871-11e7-8db9-7bb3e751dc82;
```

**Comment by adejanovski** [comment]
@ludekdolejsky : It appears that you ran into a race condition where the `SUCCESS` JMX notification was processed after the `COMPLETE` one.
Release 1.0.2 hides the issue and allows not to break Reaper in case that happens.

We're working on a proper fix that should be available shortly.

**Comment by ludekdolejsky** [comment]
Thanks - will try 1.0.2 out!

**Comment by vdemonchy** [comment]
Hello, just wanted to let you know that we encountered the issue while using Reaper in my company in a version <= 1.0.1 but no longer in 1.0.2, and even if I'm aware that it's a temporary workaround until it's properly fixed, thank you !

**Comment by michaelsembwever** [comment]
The precondition checks are back in place (and will be released in 1.0.3).
If people hit this problem again the checks can be explicitly disabled by starting reaper with the jvm system property `-Dreaper.disableSegmentChecks=true`.

This shouldn't be necessary though as the underlying bug (caused by d6e5a10af05382b25a9621b5f0dcd6d0c5f2ef56) has been fixed.

**Comment by sergeyyegournov** [comment]
Probably there is another path how to face another precondition failure:

```
INFO   [2018-01-20 00:54:38,279] [cassteamcityny48:d90fcc70-fda2-11e7-9651-4f9ee784df88:d90fcc79-fda2-11e7-9651-4f9ee784df88] i.c.j.JmxProxy - Triggering repair of range (-7064879232693954581,-65141245440
67066362] for keyspace "test1" on host 10.10.107.205, with repair parallelism parallel, in cluster with Cassandra version '3.11.1' (can use DATACENTER_AWARE 'true'), for column families: []
INFO   [2018-01-20 00:54:38,305] [cassteamcityny48:d90fcc70-fda2-11e7-9651-4f9ee784df88:d90fcc79-fda2-11e7-9651-4f9ee784df88] i.c.s.SegmentRunner - Nothing to repair for keyspace test1
ERROR  [2018-01-20 00:54:38,324] [cassteamcityny48:d90fcc70-fda2-11e7-9651-4f9ee784df88:d90ff3af-fda2-11e7-9651-4f9ee784df88] i.c.s.RepairRunner - Executing SegmentRunner failed
java.lang.IllegalStateException: startTime must be set if segment is RUNNING or DONE
        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at io.cassandrareaper.core.RepairSegment$Builder.build(RepairSegment.java:205)
        at io.cassandrareaper.service.SegmentRunner.runRepair(SegmentRunner.java:272)
        at io.cassandrareaper.service.SegmentRunner.run(SegmentRunner.java:133)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I am running 1.1.0-SNAPSHOT. It seems that this is due to context.storage.updateRepairSegment() not properly setting startTime after coordinator.triggerRepair() returns 0 and segment is marked as DONE.

**Comment by michaelsembwever** [comment]
@sergeyyegournov next time feel free to open a new ticket for this please. these preconditions have raised a number of shortcomings in the consistency of the codebase.

otherwise your analysis is correct: startTime is set in `processTriggeredSegment(..)`, but in `runRepair()` there's a number of exit (return) points possible before this method is called (and without startTime being set).  A number of fixes needs to be applied here (and various unit test cases added!)
  
This a great example here of how multiple return statements in a method are but glorified goto statements.

**Comment by sergeyyegournov** [comment]
@michaelsembwever, thank you for the fix! Though this one is not really a big deal but just one more step to Reaper awesomeness!
