### ISSUE TITLE
Web UI not up-to-date with the latest release

### ISSUE THREAD

**Issue by vdemonchy** [thelastpickle/cassandra-reaper#296]
Hello there,

It seems the Web UI of reaper hasn't been regenerated to update the displayed version (still "1.0.1-SNAPSHOT" in both 1.0.1 and 1.0.2), so would it be possible for you to do so please?

Thank you!

**Comment by adejanovski** [comment]
Hi @vdemonchy,

I updated both releases with a new tar.gz package that contains the rebuilt UI.
The deb and rpm packages shouldn't have the problem.

Thanks for the notice !

**Comment by vdemonchy** [comment]
Awesome, thanks a lot! :)
