### ISSUE TITLE
Opportunity to change intensity during execution

### ISSUE THREAD

**Issue by kipwoker** [thelastpickle/cassandra-reaper#301]
Hello.

I want to change intensity during execution.
I have a highload cassandra cluster during 8 working hours every weekday.
During working hours I want to have small intensity, like 0.2.
During maintenance window (night, day off) I want to have intesity like 0.8.

Am I right that there is no way to do it with [autoScheduling](http://cassandra-reaper.io/docs/configuration/reaper_specific/)?
Should I make a pull request for this feature?

**Comment by adejanovski** [comment]
Hi @kipwoker, 

I confirm that intensity is a fixed value for each repair run and cannot currently vary based on the current time.
Any PR to add that feature would be much appreciated indeed :)

How far do you see this going in flexibility ? Would you add just 2 possible intensities with 2 time ranges for each repair ? Or add a high load and a low load time range on the clusters, and then 2 distinct intensities for repair run ?

**Comment by kipwoker** [comment]
@adejanovski I want to do it very flexible. :)
Actually I just want to implement feature: «Change intesity when repair paused»
After that I can do whatever I want though using api + cron. It's very flexible.
Also for web interface I see it like this
![intensity](https://user-images.githubusercontent.com/1760443/34038162-6f139ada-e19c-11e7-8529-fdb4967e608b.PNG)
1. If pressed «Pause» button, show «Edit» button.
2. If pressed «Edit» button, show settings which can be changed (for now only intensity)
3. If field with value blurred, send ajax query to server with new value
4. If activate button pressed again, repair run again but with new settings

What do you mind about this?

**Comment by kipwoker** [comment]
I've tried to make something. You may check it out: https://github.com/kipwoker/cassandra-reaper/commit/bdb3947aa6734bc998113d5fcc0171d0eec4efd6

**Comment by adejanovski** [comment]
Merged as part of #303
