### ISSUE TITLE
base url not retained

### ISSUE THREAD

**Issue by samuelbenhamou** [thelastpickle/cassandra-reaper#311]
Hi, just installed the tool recently to try it out and I have had a few issues so far:
The service runs behind reverse proxies and I had to manually patch the jar/deps.js because the /ping and /cluster endpoint did not take the full path from the url into account:
let's say I redirect my service to : 
http://myproxyurl/cassandra/reaper

I would expect the endpoints to take that full url into account for the ajax requests like:
http://myproxyurl/cassandra/reaper/ping

problem is that it gets redirected to:
http://myproxyurl/ping

I would not want to add all possible urls into the reverse proxies configuration as I have multiple services running on them but would prefer the deps.js to take that into account...

**Comment by denniskline** [comment]
Can this issue be solved by updating your config.yaml to include:

```
server:
  applicationContextPath: /cassandra/reaper
```

https://www.dropwizard.io/0.7.1/docs/manual/configuration.html

**Comment by denniskline** [comment]
Oh I see.  Regardless, webui's URI_PREFIX points to "/".  

How about changing declarations of:
```
const URL_PREFIX = isDev ? 'http://127.0.0.1:8080' : '';
```
To something like:
```
const contexPath = (window.top.location.pathname).includes('/webui') ? (window.top.location.pathname).substring(0, (window.top.location.pathname).indexOf("/webui")) : '';
const URL_PREFIX = isDev ? 'http://127.0.0.1:8080' : contexPath;
```
This would mean that anything before /webui would be preserved and then reaper could make calls to /{contextPath}/ping, /{contextPath}/cluster, etc
