### ISSUE TITLE
schedule tab not working in some browsers

### ISSUE THREAD

**Issue by samuelbenhamou** [thelastpickle/cassandra-reaper#313]
I have been using certain versions of ffox/chromium and cannot change them as I do not have the rights
ffox works out for both browser whereas chromium has an issue :

> duplicate  data property in object literal not allowed in strict mode

coming from schedules.js:4233

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-336) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-336

**Comment by adejanovski** [comment]
The UI went through many changes since this ticket was created. Are you still experiencing this problem with latest versions?

**Comment by adejanovski** [comment]
Closing this stale ticket.
