### ISSUE TITLE
yaml configuration

### ISSUE THREAD

**Issue by samuelbenhamou** [thelastpickle/cassandra-reaper#314]
I have multiple interfaces defined on the cassandra nodes:
one for inter nodes communication and one for external access

I like the idea of having the possibility to specify for each node the JMX port but it would be probably easier to consider that all nodes from a cluster share the same port and not repeat the same line for a different ip addr.

Now, concerning the first part: in order to have reaper to work out I had to specify for a node the JMX port for the two ip addresses (internal and external), which is not an issue in case I have a 3 nodes cluster but for a larger size it would be a pain.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-337) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-337

**Comment by adejanovski** [comment]
Yes, I definitely agree.

I think this can be achieved pretty easily though.
The plan would be to accept `[host]:[port]` as input for the seed nodes of a cluster (I think that's already possible) and use it as the default port for the whole cluster.
I'll wait for #316 before working on this as it will probably conflict with what's done there.

**Comment by adejanovski** [comment]
This was addressed a while ago with the JMX port being stored in the database and set during cluster registration.
