### ISSUE TITLE
Repair run is stalled following short term problems with Cassandra backend, restart fixes the issue

### ISSUE THREAD

**Issue by sergeyyegournov** [thelastpickle/cassandra-reaper#318]
Running the 1.1.0-SNAPSHOT as of writing; Cassandra is used as backend.

I have a repair run that got stalled in the middle (4059/11520). Before making any changes to the run I consulted repair_run table in Cassandra - all rows had a state of RUNNING.

When I paused the run - all rows got updated and switched to PAUSED state. Now when I click Activate - nothing happens.

`
INFO   [2018-01-24 14:45:08,600] [dw-289449 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/PAUSED] i.c.r.RepairRunResource - modify repair run state called with: id = 40aee550-0069-11e8-9208-931ae1c16c5b, state = Optional.of(PAUSED)
INFO   [2018-01-24 14:45:08,920] [dw-289449 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/PAUSED] i.c.r.RepairRunResource - Pausing run 40aee550-0069-11e8-9208-931ae1c16c5b
172.16.4.42 - - [24/Jan/2018:19:45:08 +0000] "PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/PAUSED HTTP/1.1" 200 739 "http://cassreaper-40001:8080/webui/repair.html?currentCluster=documentservicesonline" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" 323
INFO   [2018-01-24 14:46:12,132] [dw-289082 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/RUNNING] i.c.r.RepairRunResource - modify repair run state called with: id = 40aee550-0069-11e8-9208-931ae1c16c5b, state = Optional.of(RUNNING)
INFO   [2018-01-24 14:46:12,454] [dw-289082 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/RUNNING] i.c.r.RepairRunResource - Resuming run 40aee550-0069-11e8-9208-931ae1c16c5b
INFO   [2018-01-24 14:46:12,454] [dw-289082 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/RUNNING] i.c.s.RepairManager - Starting a run with id #40aee550-0069-11e8-9208-931ae1c16c5b with current state 'PAUSED'
`

I would expect to see something like `Running segment for range` log message from the `RepairRunner.startNextSegment` - however it does not happen. I suspect that the problem is that RepairRunner for this run did not exist at all - and when `RepairManager.startRepairRun` handles transition from PAUSED to RUNNING - it does not attempt to call `startRunner(runId)` - I believe correctly assuming that runner should exist - but probably it does not exist in this case.

Now what happened before this run got stalled is that there were issues with Cassandra backend:
`
INFO   [2018-01-23 17:19:18,649] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b:40b37992-0069-11e8-9208-931ae1c16c5b] i.c.s.SegmentRunner - Repair for segment 40b37992-0069-11e8-9208-931ae1c16c5b started,
 status wait will timeout in 1800000 millis
INFO   [2018-01-23 17:19:18,716] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - Next segment to run : 40b01e04-0069-11e8-9208-931ae1c16c5b
INFO   [2018-01-23 17:19:19,639] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b:40b37992-0069-11e8-9208-931ae1c16c5b] i.c.s.SegmentRunner - Repair command 1625 on segment 40b37992-0069-11e8-9208-931ae1c16c5b returned with state DONE
INFO   [2018-01-23 17:19:19,840] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - Running segment for range (67040611113521179026527156973825772500,103080720378346048410509852424785803724]
INFO   [2018-01-23 17:19:20,117] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - Next segment to run : 40b48b20-0069-11e8-9208-931ae1c16c5b
ERROR  [2018-01-23 17:19:21,221] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
ERROR  [2018-01-23 17:19:21,221] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
ERROR  [2018-01-23 17:19:21,222] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
ERROR  [2018-01-23 17:19:21,222] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
ERROR  [2018-01-23 17:19:21,222] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry

...

ERROR  [2018-01-23 17:19:23,464] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
ERROR  [2018-01-23 17:19:23,464] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
ERROR  [2018-01-23 17:19:23,464] [paidrecs:40aee550-0069-11e8-9208-931ae1c16c5b] i.c.s.RepairRunner - RepairRun FAILURE, scheduling retry
INFO   [2018-01-24 14:45:08,600] [dw-289449 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/PAUSED] i.c.r.RepairRunResource - modify repair run state called with: id = 40aee550-0069-11e8-9208-931ae1c16c5b, state = Optional.of(PAUSED)
INFO   [2018-01-24 14:45:08,920] [dw-289449 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/PAUSED] i.c.r.RepairRunResource - Pausing run 40aee550-0069-11e8-9208-931ae1c16c5b
172.16.4.42 - - [24/Jan/2018:19:45:08 +0000] "PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/PAUSED HTTP/1.1" 200 739 "http://cassreaper-40001:8080/webui/repair.html?currentCluster=documentservicesonline" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" 323
INFO   [2018-01-24 14:46:12,132] [dw-289082 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/RUNNING] i.c.r.RepairRunResource - modify repair run state called with: id = 40aee550-0069-11e8-9208-931ae1c16c5b, state = Optional.of(RUNNING)
INFO   [2018-01-24 14:46:12,454] [dw-289082 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/RUNNING] i.c.r.RepairRunResource - Resuming run 40aee550-0069-11e8-9208-931ae1c16c5b
INFO   [2018-01-24 14:46:12,454] [dw-289082 - PUT /repair_run/40aee550-0069-11e8-9208-931ae1c16c5b/state/RUNNING] i.c.s.RepairManager - Starting a run with id #40aee550-0069-11e8-9208-931ae1c16c5b with current state 'PAUSED'
`

But as far as I understand when an error above is logged it's followed by `context.repairManager.scheduleRetry(this);` which should re-schedule RepairRunner instance 
 again and clearly does not attempt to kill this repair session.  Also I search logs any any trace of a call to `killAndCleanupRunner` but did not find anything.

**Comment by adejanovski** [comment]
I think this is a side effect of #320.

Closing as duplicate, and let's reopen if the problem still occurs despite the fix in #321.
