### ISSUE TITLE
UI parallelism options don't match Cassandra

### ISSUE THREAD

**Issue by corey-cole** [thelastpickle/cassandra-reaper#32]
The UI stores the string description value of the parallelism option when creating a repair, but when Reaper tries to retrieve the repair from the database, it fails with the following stack trace:

`ERROR  [2016-12-14 20:13:30,824] [dw-22 - GET /repair_run] i.d.j.e.LoggingExceptionMapper - Error handling a request: 18b1eccefcda9f42
java.lang.IllegalArgumentException: No enum constant org.apache.cassandra.repair.RepairParallelism.parallel
        at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_102]
        at org.apache.cassandra.repair.RepairParallelism.valueOf(RepairParallelism.java:26) ~[cassandra-reaper-0.3.2-SNAPSHOT.jar:0.3.2-SNAPSHOT]
        at com.spotify.reaper.storage.postgresql.RepairRunMapper.map(RepairRunMapper.java:41)
(deleted the rest)`

I can (temporarily) get the repair in the database to appear in the UI by changing the value in repair_run.repair_parallelism to the enumeration name (e.g. PARALLEL instead of parallel).

This is reaper 0.3.2 against Cassandra 2.25 using Postgres as a storage backend.

**Comment by adejanovski** [comment]
Hi @corey-cole,

branch **fix-issue-32** should fix the issue by using fromName() instead of valueOf() to match the value to the enum constant when using postgres as storage backend.

Let us know if that fixes your issue, so that we can merge the fix into master.

Thanks

**Comment by corey-cole** [comment]
That did the trick.  Thanks for the quick fix.

**Comment by adejanovski** [comment]
Thanks for the feedback, I've merged the associated PR.
