### ISSUE TITLE
Metrics request

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#322]
From Gitter : 

I was also hopeful that the new metrics via dropwizard would superceed my shonky shell script that curl queried the API for:
* Total Segments per cluster
* Segments Repaired from current run for cluster

But these basic metrics don't seem to be there.
I would expect them to be somewhere under: io.cassandrareaper.service.RepairRunner
There is a percentage completed under reaper.io.cassandrareaper.service.RepairRunner.repairProgress.clustername.00000000000000160000000000000000 but no actual numbers of segments repaired per run and I need the actual numbers not a %
I found some promising metrics under reaper.io.cassandrareaper.service.SegmentRunner.runRepair and reaper.io.cassandrareaper.service.SegmentRunner.repairing
But I can only tie these up to the total segments repaired ever. That's not exactly what I want.
Last on my wish list was incompleted/aborted/error runs. I currently track these with a complex set of nested Wavefront functions using time windows and holding values. Would it be possible to send an metric for aborted run or error run (or any run where segments repaired never equalled total segments?

**Comment by debswade** [comment]
It might be helpful if I clarify a bit.  I'm hoping for something like:
1) total_segments  (per run )
2) segments_repaired (per run)
3) run_outcome (abort, error, success)

eg.
1) reaper.io.cassandrareaper.service.RepairRunner.repairProgress.myclustername.000000000000006a0000000000000000.total_segments
2) reaper.io.cassandrareaper.service.RepairRunner.repairProgress.myclustername.000000000000006a0000000000000000.segments_repaired
3) reaper.io.cassandrareaper.service.RepairRunner.repairProgress.myclustername.000000000000006a0000000000000000.run_outcome  (maybe 0 for incomplete, aborted, error and 1 for success? This is just a suggestion - you may have a better idea)

Then additionally have those metrics as a 'master metric' which is not tagged to a specific run_id but that contained telemetry from all the runs.  Elsewhere in the tree you have called this run null:

4) reaper.io.cassandrareaper.service.RepairRunner.repairProgress.myclustername.null.total_segments
5) reaper.io.cassandrareaper.service.RepairRunner.repairProgress.myclustername.null.segments_repaired
6) reaper.io.cassandrareaper.service.RepairRunner.repairProgress.myclustername.null.run_outcome

I very much appreciate your continued efforts on this guys.  Thank you!

**Comment by zznate** [comment]
@debswade You interested in hacking out a patch for this? It seems like you've done the research needed.

**Comment by debswade** [comment]
I can make very basic changes but I'm not a JS dev, I'm a DBA.  I had a go at exposing segmentsDone and segmentsTotal metrics, which I have a PR for, and I guess exposing RepairRun.RunState would do the job for points 1-3 above.
I wasn't sure how to make 'master' or non repairRun specific metric so I can't address 4-6 either. 

Also I don't have perms to push my PR
debswade/cassandra-reaper $ git push
remote: Permission to thelastpickle/cassandra-reaper.git denied to debswade.
fatal: unable to access 'https://github.com/thelastpickle/cassandra-reaper/': The requested URL returned error: 403

**Comment by zznate** [comment]
> Also I don't have perms to push my PR

First off, thanks for the effort contributions of any sort are always appreciated. 

Process wise, you have to fork the repository to your account and send a pull request. This guide provides a lot of details on doing so: 
https://help.github.com/articles/fork-a-repo/

**Comment by sergeyyegournov** [comment]
I also felt a need for metrics like segments repaired/total segments - in my case I handled this simply via wrapping spreaper calls which nicely exposes running repairs and all attributes of interest. Since I am using prometheus it was just a matter of introducing json exporter on top of the spreaper output - and now I have ability to be alerted on failed repair runs, stuck repairs or keyspaces without a repair run within certain time window. Having that exported through metrics would be nice but IMHO thanks to REST API and spreaper it's not a big deal

**Comment by zznate** [comment]
Just merged a patch from @debswade adding segmentsDone and segmentsTotal metric counters: https://github.com/thelastpickle/cassandra-reaper/pull/325

Still some work to do for whoever on hooking the rest up.

**Comment by kingm5** [comment]
I just created a PR that will make segmentsDone,segmentsTotal work and added the keyspace to the metric. This really helps .. as you can now track progress on a keyspace repair separately. Regarding the fix to segmentsDone .. it now will update as the segments are getting processed. Regarding the fix to segmentsTotal .. it now will write the total before the repair starts. This way.. you know how many segments are going to be processed and you can track them again in realtime. Also, I changed they types to integers as it did not make sense to me have as a float. I may be wrong here, but currently I do not believe we can have 5.3 segments.
https://github.com/thelastpickle/cassandra-reaper/pull/350
