### ISSUE TITLE
WebUI shows incorrect version

### ISSUE THREAD

**Issue by a1exsh** [thelastpickle/cassandra-reaper#327]
I've built the jar from 1.0.2 release tag, using `mvn clean package`, however in the WebUI I see this:
```
Version 1.0.1-SNAPSHOT
Git commit :
https://github.com/thelastpickle/cassandra-reaper/commit/cbad80e

Build date :
2017-11-22 13:21:24
```
The values come from `src/server/src/main/resources/assets/deps.js` it seems.  I guess this should be updated for every release?

**Comment by adejanovski** [comment]
Hi @a1exsh,

the new release pipeline that was setup yesterday will fix this. New releases are now pushed to [Bintray](https://bintray.com/thelastpickle) and the UI will be correctly rebuilt before packaging.

Cheers

**Comment by a1exsh** [comment]
Good to know, thank you! :-)
