### ISSUE TITLE
Cassandra Reaper Process Hung

### ISSUE THREAD

**Issue by harikavangapelli** [thelastpickle/cassandra-reaper#328]
I initiated Cassandra Repair process 15 days ago and after repairing 286/7230 segments repair process hung.

The reaper log shows the WARN messages as  below.
WARN   [2018-02-05 18:44:37,851] [testcluster:edd24600-fbe6-11e7-9a5a-796a12432b5a] i.c.s.RepairRunner - Looks like segment #edd24626-fbe6-11e7-9a5a-796a12432b5a has been running more than a day. Start time: 2018-01-18T03:57:50.867Z
WARN   [2018-02-05 18:44:47,995] [testcluster:edd24600-fbe6-11e7-9a5a-796a12432b5a] i.c.s.RepairRunner - Looks like segment #edd24626-fbe6-11e7-9a5a-796a12432b5a has been running more than a day. Start time: 2018-01-18T03:57:50.867Z
WARN   [2018-02-05 18:44:58,138] [testcluster:edd24600-fbe6-11e7-9a5a-796a12432b5a] i.c.s.RepairRunner - Looks like segment #edd24626-fbe6-11e7-9a5a-796a12432b5a has been running more than a day. Start time: 2018-01-18T03:57:50.867Z
WARN   [2018-02-05 18:45:08,280] [testcluster:edd24600-fbe6-11e7-9a5a-796a12432b5a] i.c.s.RepairRunner - Looks like segment #edd24626-fbe6-11e7-9a5a-796a12432b5a has been running more than a day. Start time: 2018-01-18T03:57:50.867Z

**Comment by adejanovski** [comment]
Hi @harikavangapelli, 

this issue has just been fixed in master and can be tested in the latest 1.1.0 dev releases : http://cassandra-reaper.io/docs/download/
