### ISSUE TITLE
New Segment Viewer always requesting 127.0.0.1

### ISSUE THREAD

**Issue by zachaller** [thelastpickle/cassandra-reaper#333]
I know this is not an official release or anything but noticed in trying it that the url that its trying to request seems to be hard coded to 127.0.0.1:8080 or something is broken figuring that out.

The request is
http://127.0.0.1:8080/repair_run/8d67c380-0d07-11e8-a100-33f28d286626/segments
but should be
http://\<browserhostname\>:8080/repair_run/8d67c380-0d07-11e8-a100-33f28d286626/segments
where \<browserhostname\> is the dns of the box we are running reaper from

**Comment by adejanovski** [comment]
Hi @zachaller,

indeed, as the segment list is served from an iframe, it falls into a hack that allows us to use webpack live reloading features when developing on the UI.
I've just ninja-fixed this and a new snapshot is available for you to test.

Let me know if it's working now and please update the issue status accordingly.

Thanks !

**Comment by zachaller** [comment]
Yup its working, thanks for all the hard work.
