### ISSUE TITLE
No signed .deb packages?

### ISSUE THREAD

**Issue by a1exsh** [thelastpickle/cassandra-reaper#336]
Trying to install a .deb package for 1.0.2 I'm getting this, first from running `apt-get update`:
```
W: The repository 'https://dl.bintray.com/thelastpickle/reaper-deb wheezy Release' is not signed.
```
Then, `apt-get -y install reaper=1.0.2` fails with the following message:
```
WARNING: The following packages cannot be authenticated!
  reaper
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

Are you planning to provide signed packages?  Thanks.

**Comment by adejanovski** [comment]
Hi @a1exsh,

I've just activated gpg signing of packages and re-uploaded 1.0.2. 
Could you update and try again to install it ?

Thanks

**Comment by a1exsh** [comment]
@adejanovski hi, could you please update the docs to mention the expected GPG key id (and maybe a commandline to install the pubkey)?  Currently getting this:
```
W: GPG error: https://dl.bintray.com/thelastpickle/reaper-deb wheezy Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2895100917357435
W: The repository 'https://dl.bintray.com/thelastpickle/reaper-deb wheezy Release' is not signed.
```
Thank you.

**Comment by adejanovski** [comment]
Please run the following command to get the key : `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 2895100917357435`

I'll update the documentation to include it.

**Comment by a1exsh** [comment]
@adejanovski thanks, worked now :)
