### ISSUE TITLE
No error message when back-end inaccessible

### ISSUE THREAD

**Issue by SesquipedalianDefenestrator** [thelastpickle/cassandra-reaper#339]
**Spotted on 1.0.2 (1c42b07)**

A bit of background:  I was hopping between VPNs, having already loaded the Reaper webpage.  When I was on the "wrong" VPN, I was able to successfully click among the various menus.  However, instead of getting an error message, the page would come up as if no clusters/schedules/repairs were defined.  The end result was several hours of me trying to figure out why Reaper had suddenly lost/forgotten all state/config/history, when the actual problem was just a reachability issue.  To save future headaches for others, it would be nice if an inability of the webapp to reach the back-end resulted in an error rather than a successful-looking empty interface :)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-340) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-340

**Comment by SesquipedalianDefenestrator** [comment]
Update:  still present in 1.4.6, at least to some extent. 
The Repair screen shows a nice error message about not being able to contact the server, but the main/Cluster view just fails silently and reports that no clusters are found/defined in the Reaper instance.

**Comment by adejanovski** [comment]
@SesquipedalianDefenestrator, are you still experiencing this issue?

**Comment by SesquipedalianDefenestrator** [comment]
Nope, as of 3.1.1 it seems to be quite consistent about displaying an error message rather than an apparently-successful empty instance.
