### ISSUE TITLE
Remove use of deprecated `dateof` CQL function

### ISSUE THREAD

**Issue by a1exsh** [thelastpickle/cassandra-reaper#340]
Just seen this warning in the Cassandra server log (v3.0.15):
```
WARN  The function 'dateof' is deprecated. Use the function 'toTimestamp' instead.
```

Looks like the only two uses are in CassandraStorage.java: https://github.com/thelastpickle/cassandra-reaper/search?utf8=%E2%9C%93&q=dateof&type=

**Comment by michaelsembwever** [comment]
Shall be tackled as part of https://github.com/thelastpickle/cassandra-reaper/pull/430
