### ISSUE TITLE
Reaper might be reading tombstone

### ISSUE THREAD

**Issue by nicolasguyomar** [thelastpickle/cassandra-reaper#349]
Hi guys,
Thank you for this tool ! 

I have quite a lot of warning from cassandra-reaper which does appear as soon a a repair starts : 

WARN  [ReadStage-2] 2018-02-17 07:25:02,559 ReadCommand.java:533 - Read 3644 live rows and 1012 tombstone cells for query SELECT * FROM reaper_db.repair_run WHERE id = 584f87d0-1362-11e8-abcf-57de97efc120 LIMIT 5000 (see tombstone_warn_threshold)

This cluster has 256 vnodes, 9 nodes over 3 racks, and the scheduled repair is the default one from the UI on reaper 1.0.2. 

This happened during the first repair on the cluster. Is it something known ?

Reaper config : 
cassandra:
  clusterName: "cassandra"
  contactPoints: ["xxx","xxx","xxx"]
  keyspace: reaper_db
  loadBalancingPolicy:
    type: tokenAware
    shuffleReplicas: true
    subPolicy:
      type: dcAwareRoundRobin
      localDC: "dc1"
      usedHostsPerRemoteDC: 0
      allowRemoteDCsForLocalConsistencyLevel: false

**Comment by adejanovski** [comment]
Hi Nicolas,

postponing segments can indeed generate tombstones as it requires use to null both the segment start time and end time. We tried to fix this issue a little while ago but it ended up creating race conditions that left the database in an inconsistent state.
You can check the number of postpones in the metrics at : http://your-reaper-ip:8081/metrics 

I agree that we may want to revisit that behavior but it could take a little bit of time as the last attempt proved to be more challenging than expected. I can think of some easy hacks that could allow us to avoid creating tombstones while keeping the db consistent. 

As the repair_run table uses LCS, it should do a fairly good job at merging the tombstones and you shouldn't be experiencing performance problems. 

I'll keep that issue opened and target 1.2.0 for a fix.

**Comment by nicolasguyomar** [comment]
Hi Alex,

Metrics endpoint give me those numbers, which I do not know how to interpret : 

"io.cassandrareaper.service.SegmentRunner.postpone.MyIp.cassandra.mykeyspace": {
      "count": 1
    },
    "io.cassandrareaper.service.SegmentRunner.postpone.**null**.cassandra.mykeyspace": {
      "count": 2372
    },

Is the "null" keyword a bad configuration on my side ? 

Thank you for the 1.2.0 flag !

**Comment by michaelsembwever** [comment]
> Since you have postpones in the thousands, it indeed explains the tombstone warnings you're seeing.

This isn't to be ignored. 
It's also worth noting that the ratio of live to tombstone cells isn't completely out of whack.

> I think it's the main source of postpone calls and it happens when both startTime and endTime are already null. We only use this to increment the fail count, which shouldn't be incremented in this case anyway as the segment hasn't failed to run, it's just not eligible yet.

I agree that this specific call to `postponeCurrentSegment()` could be customised. But it might be awkward to implement.

It might be simpler to just reduce the `fetchSize` of the `getRepairRunPrepStmt` query…?
I'm thinking: if the ratio of live:tombstone in such postpone heavy situations typically is 3:1, we could presume a safe ceiling of a ratio of 1:1, then reduce `fetchSize` from 5k to 1k  should keep tombstones read under the threshold. The consequence is that those queries would be slower (due to multiple fetches) but I can't see this being an issue for this path in the code.

**Comment by adejanovski** [comment]
Fixed by #351 that was just merged into master.
Betas will be pushed to Bintray shortly.
