### ISSUE TITLE
Add ability to auto repair a node after it's been down for a configurable amount of time

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#377]
Operators should be able to bring a node back up, and reaper should repair it automatically.  Reaper should wait for hints to reply before starting the repair.

UX wise, we should be able to repurpose the existing repair one-off page, adding details for rules such as how long to wait after hints have replayed.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-347) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-347

**Comment by adejanovski** [comment]
It seems unlikely that we'll ever implement this feature.
Also you may want some human intervention on such cases as repairs can have an impact on performance, and could make things worse if performance issues had caused the initial failure.
