### ISSUE TITLE
 schedule_trigger_time format not shown

### ISSUE THREAD

**Issue by aarontroot** [thelastpickle/cassandra-reaper#379]
In the "how to" video I see that there is a default schedule trigger time shown in the text box.  It doesn't show up in mine. This only appears to be an issue in Firefox, it shows up in Chrome.
![](https://user-images.githubusercontent.com/10158026/37805435-ef1507be-2dff-11e8-865e-fefb7a80c84c.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-348) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-348

**Comment by adejanovski** [comment]
@terrcin : it would be great to have a proper date/time picker component in the repair schedule UI to pick the start time.

Thanks !

**Comment by kotaroyamazaki** [comment]
This ticket seems to be done.

**Comment by adejanovski** [comment]
it is, closing.
