### ISSUE TITLE
HTTP 404 upon start up

### ISSUE THREAD

**Issue by iMajna** [thelastpickle/cassandra-reaper#382]
Upon start up a service I'm getting 404 error on applicationConnector port. 
On adminConnector port I think everything is fine
![image](https://user-images.githubusercontent.com/10169730/37903048-d027f9d4-30f6-11e8-835b-e52de24abbbc.png)

When I open */webui* this is what I got: 
![image](https://user-images.githubusercontent.com/10169730/37903414-16667cf8-30f8-11e8-8716-3b9aa7a2a2a9.png)

without /webui
![image](https://user-images.githubusercontent.com/10169730/37903438-39a564f4-30f8-11e8-959e-ebece9114192.png)

Server side info:
![image](https://user-images.githubusercontent.com/10169730/37903476-6215bb78-30f8-11e8-83dd-ec052812c7d3.png)

**Comment by adejanovski** [comment]
Hi @iMajna,

try adding a `/` after webui : `http://whatever:8080/webui/` 

I need to fix this...

**Comment by iMajna** [comment]
Yeap, I tried adding the most funny thing ever `/index.html` and it worked :D, but was waiting for someone to answer because I was worried that I did something wrong.
