### ISSUE TITLE
Convert cluster names for Graphite ingestion

### ISSUE THREAD

**Issue by joaquincasares** [thelastpickle/cassandra-reaper#385]
If a cluster name has a `.` in it, like `tlp-monitoring-stack-2.2`, Graphite will split the metric endpoint into two:

* `tlp-monitoring-stack-2`
* `2`

We need to sterilize `.`'s into `_`'s scores or `-`'s.

Same thing for hostnames that are IP addresses. `.`'s should not create new Graphite endpoints.

**Comment by michaelsembwever** [comment]
Addressed in pull request https://github.com/thelastpickle/cassandra-reaper/pull/386
