### ISSUE TITLE
"given schedule_trigger_time is in the past"

### ISSUE THREAD

**Issue by mrwulf** [thelastpickle/cassandra-reaper#398]
When creating a new schedule the validation seems to be against a different time zone. Initially I thought this was an issue with the reaper container (we're running reaper in kubernetes) having the wrong timezone, but that doesn't seem to have fixed the validation. It would be nice if (when creating a new schedule) the start time was initialized to the current system time and/or if the start time is in the past the schedule just immediately goes into effect.

**Comment by adejanovski** [comment]
All times are using UTC in the server while the frontend uses no specific timezone, which creates the (crappy) behavior you're observing.
The simplest way to deal with this is indeed to allow schedules that start in the past and let Reaper trigger a new run straight away.
I've always been very frustrated with this as well :D

**Comment by amorton** [comment]
grooming: @adejanovski has code  on his laptop that will send the timezone from the UI to the server so we can sort out the correct UTC time in the back end. Will also immediately start a scheduled repair that starts in the past
