### ISSUE TITLE
Repair completed succesfully but nodetool info doesn't show any change

### ISSUE THREAD

**Issue by dannyz29** [thelastpickle/cassandra-reaper#402]
I have a cluster of 4 nodes with C* version 3.11.
RF is 3 and consistency level is 1 for both read and write.

I've setup and ran reaper (1.2.0) for the first time on my largest keyspace. Reaper shows all segments were repaired successfully but when I run "nodetool info" on the cluster nodes, I see no change in "percent repaired" from before.

Could someone point me to the right direction understanding why is that?

Nodetool info output:

```
ID                     : 3700f895-8974-4a7b-9e4b-9f1c086d5d5e
Gossip active          : true
Thrift active          : true
Native Transport active: true
Load                   : 132.03 GiB
Generation No          : 1523867999
Uptime (seconds)       : 78748
Heap Memory (MB)       : 4977.82 / 16384.00
Off Heap Memory (MB)   : 1605.02
Data Center            : us-west-2
Rack                   : 2c
Exceptions             : 0
Key Cache              : entries 2620911, size 299.23 MiB, capacity 300 MiB, 9479767 hits, 36031622 requests, 0.263 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 50 MiB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Chunk Cache            : entries 7680, size 480 MiB, capacity 480 MiB, 47772733 misses, 58982696 requests, 0.190 recent hit rate, 1073.532 microseconds miss latency
Percent Repaired       : 61.35356885298504%
Token                  : (invoke with -T/--tokens to see all 256 tokens)
```

Reaper repair job details:

```
Last event | All done
-- | --
Start time | April 16, 2018 12:06 PM
End time | April 17, 2018 8:55 AM
Pause time | April 16, 2018 12:06 PM
Duration | 20 hours 48 minutes 54 seconds
Segment count | 1024
Segment repaired | 1024
Intensity | 0.5
Repair parallism | SEQUENTIAL
Incremental repair | false
Nodes
```

**Comment by adejanovski** [comment]
Hi,

the percent repaired value only applies to incremental repair and full (non subrange) repairs, which mark SSTables as repaired (and thus allows to compute that value).
Reaper uses subrange repair, which is the only way to avoid anticompaction, and the safest way to run repair to this day.

You will not get a value there unless you set Reaper to perform incremental repairs, which we still do not currently recommend : http://thelastpickle.com/blog/2017/12/14/should-you-use-incremental-repair.html
