### ISSUE TITLE
tarball install

### ISSUE THREAD

**Issue by CassDBA** [thelastpickle/cassandra-reaper#405]
Hi , 

With tarball install and cassandra as backup ,

started reaper as following , able to see migration script creating tables inside reaper_db keyspace but webui is showing blank page 

Tarball start command
/opt/app/workload/jdk18/bin/java -jar /opt/app/workload/reaper/cassandra-reaper-1.1.0/server/target/cassandra-reaper-1.1.0.jar server /opt/app/workload/reaper/cassandra-reaper-1.1.0/resource/cassandra-reaper-cassandra.yaml &

**Comment by adejanovski** [comment]
This is probably due to a bug in the UI. Please try to add a `/` at the end of the URL : `http://..../webui/`
