### ISSUE TITLE
jmxCredentials 1.1.0

### ISSUE THREAD

**Issue by vpukis** [thelastpickle/cassandra-reaper#407]
I got an error during service start "/etc/cassandra-reaper/cassandra-reaper.yaml has an error: Unrecognized field at: jmxCredentials" using RPM installed reaper-1.1.0-1.x86_64 on Centos 7. According to docs this should be possible since 1.1.0

**Comment by adejanovski** [comment]
Hi @vpukis,

it's a mistake in the docs, this feature hasn't been merged in 1.1 but is available in master.
You can install the latest beta in order to use it.
