### ISSUE TITLE
Throttle repair to allow nodes to keep up with compaction

### ISSUE THREAD

**Issue by ecnepsnai** [thelastpickle/cassandra-reaper#408]
Our cluster has two DCs with three RACs in each with a total of 18 nodes. The nodes in DC2 have slower, spinning-disk HDDs while the nodes in DC1 have NVME flash storage.

We've been having issues with both nodetool and repair repairs filling up the disk on the DC2 nodes quickly as compaction jobs cannot keep up with the streams.

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        63G  3.0G   57G   6% /
tmpfs            16G   12K   16G   1% /dev/shm
/dev/sda1       477M   94M  358M  21% /boot
/dev/sdb1       1.7T  1.6T  103G  94% /data1

$ ./nodetool compactionstats
pending tasks: 648
                                     id   compaction type   keyspace           table      completed           total    unit   progress
   a31ea0d0-48a4-11e8-bda3-15f66f07c590        Compaction         ...            ...    20951961409     42978922612   bytes     48.75%
   3711ba70-4837-11e8-bda3-15f66f07c590        Compaction         ...            ...   510572487184   1104760365330   bytes     46.22%
```

We started a repair parallel repair job with 200 segments at 1 intensity a few days ago, and two nodes are now at or near 100% full and we're trying to look at our next steps to help fix this issue.

How can we throttle our reaper repair jobs to allow for these slower nodes to perform compaction in-time?

**Comment by adejanovski** [comment]
Hi,

are you using 1 Reaper instance in each DC and `datacenterAvailability: EACH` ?
If you use  `datacenterAvailability: EACH` or `datacenterAvailability: ALL` (in case one Reaper can access all nodes in both DCs), then  Reaper will stop processing segments if they involve a replica that has more than 20 pending compactions.

Please check this page for more info : http://cassandra-reaper.io/docs/usage/multi_dc/

**Comment by adejanovski** [comment]
Closing this issue. Feel free to reopen if anything new pops up.
