### ISSUE TITLE
Repair Doesnot start

### ISSUE THREAD

**Issue by satishsoma** [thelastpickle/cassandra-reaper#41]
When I execute the repair through reaper for a particular keyspace.The repair does not start and I can find 
Info:Starting a run with id #11 with current state 'NOT_STARTED' 
Info:scheduling repair for repair run #11

Could anyone please help me with this issue

**Comment by adejanovski** [comment]
Hi,

Could give more informations to help us analyze the issue?
Which version of Apache Cassandra are you using?
How did you create the repair in reaper ? UI, command line or rest call?
Which backend are you using for reaper storage ? Postgres or Cassandra?

Thanks

**Comment by satishsoma** [comment]
Hi,

Version:2.2.5
Creation:command line
backend:Postgres

Thanks

**Comment by adejanovski** [comment]
There is a bug in 2.2.5 with the notification service. This prevents reaper from getting feedback on the repair status.

This is fixed in Cassandra 2.2.6.

**Comment by satishsoma** [comment]
Thank you
