### ISSUE TITLE
Excessive network traffic on the reaper server

### ISSUE THREAD

**Issue by gaborauth** [thelastpickle/cassandra-reaper#413]
There is a cluster (4DCs 16 nodes), it has ~20 keyspaces and ~200 tables. I ran a full repair on every keyspaces with reaper this morning and yesterday morning... and experienced a huge network traffic on the reaper's server: ~70 GByte per day mostly incoming traffic (from the Cassandra nodes). The cluster has only ~1 GB data. Is it normal?

Reapers node (there is no Cassandra only the reaper):
![image](https://user-images.githubusercontent.com/16724720/39591825-3a8ff804-4f05-11e8-9ed5-35d158e27b89.png)

Cassandra node (and the end of the previous repair):
![image](https://user-images.githubusercontent.com/16724720/39592031-e29f0d28-4f05-11e8-8ca0-ff335d94318c.png)

**Comment by adejanovski** [comment]
that's a lot indeed... 

You should try to raise the `repairManagerSchedulingIntervalSeconds` in the yaml file to see if it reduces the network usage.
Also cleaning up past repairs could help.

Could you check the logs at the time you had such consumptions to see if you had a lot of failed attempts at running segments ? I suspect that the way we handle postpones now could've created some overhead in the reads Reaper makes to the backend.

**Comment by gaborauth** [comment]
I thought the Reaper just the orchestrator of the process... :/

I ran a cluster wide full repair on every keyspaces with `nodetool repair -full` this morning from 8AM to 9AM:
![image](https://user-images.githubusercontent.com/16724720/39956174-db4e0eb6-55db-11e8-938e-5d8346a8c02c.png)

Significantly did not show on the graph that it was a repair... sending and receiving the merkle trees is not a network intensive process, it is mostly I/O intensive task.

**Comment by adejanovski** [comment]
Reaper is the orchestrator but it stores the list of segments in Cassandra if you use it as backend, and needs to read it each time it tries to start a new one.
There's obvious room for improvement there, whether we should use server side filtering or client side caching.

**Comment by gaborauth** [comment]
Okay, my cluster has ~10000 segments and the Reaper used ~ 70 GB network traffic to handle it... okay it is ~ 7 MB per segment... hm... :/

**Comment by adejanovski** [comment]
It doesn't mean each segment weighs 7MB. Each segment is read multiple times over the lifetime of the repair run.
You can reduce this right now by applying the suggestions I gave earlier, and we will address this issue in #416.

**Comment by gaborauth** [comment]
I understand. I understood that each segment generates ~ 7MB of traffic during repair. :)

Thank you! :)
