### ISSUE TITLE
[question] For cassandra backend, can I restart cassandra-reaper freely?

### ISSUE THREAD

**Issue by shuoli84** [thelastpickle/cassandra-reaper#414]
Now I run cassandra-reaper on some scheduling platform (nomad), and would like to adjust its memory usage, which will trigger an instance relocate, can I do it brainlessly? Or I have to do it when there is no active repair running.

**Comment by adejanovski** [comment]
You can restart Reaper without worrying too much. 
It will cancel previously running segments once restarted and start new ones.

It won't break repairs or generate hanging segments, you'll just re-repair the segments that were running when the restart happened.
