### ISSUE TITLE
Reduce network traffic with Cassandra as backend

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#416]
Reaper reads all the segments from the repair_run table each time the repair run manager loops (which is every 10s by default).
There are also other tasks that require to cycle through all repairs in a given state to fix the database (after a restart for example).

This tends to generate excessive network traffic if there are a lot of segments in the database and we should implement server side filtering (with or without index) or client side caching to reduce it.

**Comment by michaelsembwever** [comment]
Closed, work/discussion can continue in https://github.com/thelastpickle/cassandra-reaper/pull/418 for now.
