### ISSUE TITLE
Deleting a cluster is (overly) cumbersome

### ISSUE THREAD

**Issue by mrwulf** [thelastpickle/cassandra-reaper#428]
Before a cluster can be deleted all of it's scheduled runs must be deleted and any repairs of that cluster (running or not) must be deleted. While deleting clusters isn't a common task, it is done more often by people first trying reaper. This seems like a simple bit of polish that should be easy to implement.

**Comment by michaelsembwever** [comment]
@adejanovski as we spoke about yesterday, it's a design fault that finished repair runs have to be deleted before one can delete (unregister) a cluster.

**Comment by adejanovski** [comment]
Agreed, we should prevent deletion if a schedule exists maybe, and delete the repair run history straight away if there's no active schedule.

**Comment by amorton** [comment]
Acceptance: in the UI, when clicking to delete a cluster, the ui asks if you are sure, then deletes the cluster all of it's history if there is no active schedule. If there is one or more active schedules tell the user there are active schedules in a second question and ask to confirm delete, then delete the schedules as well. If there is an active repair do not let the cluster be deleted.

(or a check box on the first popup)

on the CLI ask the user the same questions and allow params like `--yes` for the first question and `--delete-if-active` for the second.

**Comment by detinho** [comment]
As deleting a cluster is a dramatic event, maybe we should borow from AWS and add some "termination protection". The UI should proactively asks the user to set or not the config, and be clear te config to not be important on test environments.

**Comment by adejanovski** [comment]
Fixed with the `--force` flag in spreaper (and the corresponding query param in the REST API).
