### ISSUE TITLE
Reaper taking more than 2 hrs. for almost empty keyspace

### ISSUE THREAD

**Issue by kptnew3** [thelastpickle/cassandra-reaper#436]
Hi,

I setup a keyspace with a single table and a single row just for the testing. However I see that whole repair took more than 2 hrs to finish all the segments. 

I ran the repair for just the user keyspace and the specified table still it took that much longer. 

Can you please suggest how can I improve the repair performance? I couldn't find any documentation on reaper website related to that. 

Help on this is much appreciated. 

Regards,
Gagan

**Comment by adejanovski** [comment]
The latest beta implements can group token ranges that have the same replicas, so you can reduce by a lot the number of segments on clusters that use vnodes.

You should give it a try.

**Comment by carlo4002** [comment]
Hello @adejanovski , you speak about the version 1.2 ?

**Comment by adejanovski** [comment]
Yes, 1.2.2 and onwards introduced token range coalescing to reduce the number of segments.
