### ISSUE TITLE
Does Reaper have capability to encrypt the shiro.ini file

### ISSUE THREAD

**Issue by kptnew3** [thelastpickle/cassandra-reaper#453]
**Spotted on 1.2.0-BETA-20180607 (21edbeb)**

Dear Reaper team,

Can you guide if shiro.ini file for storing the user id and password can be encrypted on disk so that the plain text password can be protected?

Thanks for all the support so far!

Regards,
Gagan

**Comment by nsteinmetz** [comment]
If you follow Shiro's doc, it works as expected.

```
main]
authc = org.apache.shiro.web.filter.authc.PassThruAuthenticationFilter
authc.loginUrl = /webui/login.html
sha256Matcher = org.apache.shiro.authc.credential.Sha256CredentialsMatcher
iniRealm.credentialsMatcher = $sha256Matcher

[users]
nicolas = 807A09440428C0A8AEF58BD3ECE32938B0D76E638119E47619756F5C2C20FF3A

[...]
```

**Comment by kptnew3** [comment]
Thanks a lot Nicolas! I would give a try to it and let you know.

Regards,
Gagan
