### ISSUE TITLE
Stale list of seeds on dynamic environments

### ISSUE THREAD

**Issue by ricbartm** [thelastpickle/cassandra-reaper#455]
We use Reaper as tool for automated repairs for several internal clusters on AWS. We treat instances as inmutable infrastructure, so when we upgrade clusters, we terminate instances and new ones (with new IPs) are started. So, at some point, all Ips of a given cluster have changed.

We realised that a cluster we added a cluster few months ago using as seed the IP of one of the instances of the cluster now can't show any information about the cluster, while Reaper web interface stay rolling. We have verified that the PostgreSQL table `reaper.clusters` contains a row for the cluster with the old IPs of the cluster.

```sql
> select * from cluster
whitequeen | org.apache.cassandra.dht.Murmur3Partitioner | {10.231.0.1,10.231.0.2,10.231.0.3}
```

When we manually updated the value in the database, the cluster started to show information in the Reaper web interface and we were able to schedule a manual repair.

Looks like Reaper configured the seed IPs once and does not track/update that information in any periodic manner using JMX protocol, so at some point all IPs that Reaper has reference to do not exist anymore, resulting in Reaper unable to repair the cluster.

I need some time to look deeper at this issue in the code, but **is it a bug, or is was it never implemented, so it's a feature request?**

**Comment by adejanovski** [comment]
Hi @ricbartm,
this is something that has been addressed recently and now each time a repair starts, the list of nodes gets updated in the database : https://github.com/thelastpickle/cassandra-reaper/pull/391

You can also re-register an existing cluster (without deleting it) with a valid seed and it will also update the whole list.

This feature will be released in 1.2.0 and you can already have it if you switch to the latest beta.
