### ISSUE TITLE
Can't add a cluster

### ISSUE THREAD

**Issue by ilya-epifanov** [thelastpickle/cassandra-reaper#460]
**Spotted on 1.2.0-BETA-20180627 (d5ad059)**

When I click 'Add Cluster' button, nothing happens and I get the following in the console:

TypeError: a.findDOMNode is not a function

_onAdd
http://localhost:9050/webui/index.js:39:11310
_onAdd self-hosted:976:17 g
http://localhost:9050/webui/deps.js:49:504
[743]/</I.invokeGuardedCallback
http://localhost:9050/webui/deps.js:49:607
T
http://localhost:9050/webui/deps.js:31:28026
N
http://localhost:9050/webui/deps.js:31:28279
r
http://localhost:9050/webui/deps.js:31:12486
a
http://localhost:9050/webui/deps.js:31:12614
forEach self-hosted:261:13 t
http://localhost:9050/webui/deps.js:46:19475
processEventQueue
http://localhost:9050/webui/deps.js:31:13800
g
http://localhost:9050/webui/deps.js:55:5244
handleTopLevel
http://localhost:9050/webui/deps.js:55:5347
a
http://localhost:9050/webui/index.js:21:1409
perform
http://localhost:9050/webui/deps.js:31:20764
batchedUpdates
http://localhost:9050/webui/index.js:20:31904
e
http://localhost:9050/webui/deps.js:6:13560
dispatchEvent
http://localhost:9050/webui/index.js:21:2268
dispatchEvent self-hosted:1020:17

**Comment by amorton** [comment]
@ilya-epifanov thanks for the report, can you help with : 

1) Can you confirm if the cluster JMX is visible from the reaper server ? Can test that using jconsole or nodetool from the reaper server 
2) Can you attach the reaper server log

**Comment by michaelsembwever** [comment]
This commit broke it https://github.com/thelastpickle/cassandra-reaper/commit/c4feb99a34c1621282717494d18aac868aa92194

**Comment by adejanovski** [comment]
OK, I'll check what's broken and fix it.
Thanks @michaelsembwever
