### ISSUE TITLE
[1.2.0] Cannot resolve module 'jsx/navbar' 

### ISSUE THREAD

**Issue by nsteinmetz** [thelastpickle/cassandra-reaper#468]
To debug #467, I set up a local envt for the app - When trying to run the server, I have 

```
ERROR in ./app/jsx/schedule-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/schedule-screen.jsx 3:0-133:2

ERROR in ./app/jsx/snapshot-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/snapshot-screen.jsx 3:0-273:2

ERROR in ./app/jsx/repair-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/repair-screen.jsx 3:0-135:2

ERROR in ./app/jsx/cluster-screen.jsx
Module not found: Error: Cannot resolve module 'jsx/navbar' in /Users/nsteinmetz/Documents/Projets/cassandra/cassandra-reaper/src/ui/app/jsx
 @ ./app/jsx/cluster-screen.jsx 3:0-135:2
```

Indeed, `jsx/navbar.jsx` the file existed til 1.1 but was removed with 1.2

**Comment by nsteinmetz** [comment]
Seems it was removed with d943370fad3a93c856e7e3251599aec117a6addf and with #415 PR.

**Comment by adejanovski** [comment]
Hi @nsteinmetz,

as mentioned on the PR, `jsx/navbar.jsx` gets generated during the maven build, because it contains version specific data (version number, commit sha, build date/time) to be displayed in the UI.

Did you run `mvn clean package` before trying to run the server ? 
Do you see the file being generated in `src/ui/app/jsx` when running Maven ?

**Comment by nsteinmetz** [comment]
Haha I was also surprised by the new layout :-)

So back to master and indeed it's generated.

I may have missed something somewhere previsouly => closing.

**Comment by nsteinmetz** [comment]
Much better now for latest master :-)

<img width="1435" alt="capture d ecran 2018-07-11 a 17 43 51" src="https://user-images.githubusercontent.com/33180/42583832-164e3ed4-8532-11e8-8950-59691cb63e4f.png">
