### ISSUE TITLE
Schema mismatch during cassandra migrations

### ISSUE THREAD

**Issue by ltagliamonte** [thelastpickle/cassandra-reaper#470]
I'm having problem trying to install cassandra-reaper.
I'm running latest docker image `1.2.0` on CoreOS using cassandra 3.0.16 as backend.
On my dev cluster i'm getting schema mismatch problems during the execution of the cassandra migrations.
```
INFO   [2018-07-10 15:43:33,729] [main] o.c.c.m.MigrationTask - Migrated keyspace reaper to version 14 
WARN   [2018-07-10 15:43:33,757] [main] i.c.s.c.Migration003 - Migrating repair_unit and repair_schedule tables. This may take some minutes… 
WARN   [2018-07-10 15:43:34,235] [main] i.c.s.c.Migration003 - Migration of repair_unit and repair_schedule tables completed. 
WARN   [2018-07-10 15:43:34,253] [main] i.c.s.c.Migration014 - altering every table to set `dclocal_read_repair_chance` to zero… 
WARN   [2018-07-10 15:43:34,258] [main] i.c.s.c.Migration014 - alter every table to set `dclocal_read_repair_chance` to zero completed. 
WARN   [2018-07-10 15:43:44,515] [casssandra-uw2-zd.service.consul-worker-2] c.d.d.c.Cluster - No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes. 
WARN   [2018-07-10 15:43:44,516] [casssandra-uw2-zd.service.consul-worker-1] c.d.d.c.Cluster - No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes. 
WARN   [2018-07-10 15:43:44,575] [casssandra-uw2-zd.service.consul-worker-3] c.d.d.c.Cluster - No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.  
```
The server eventually completes the bootstrap but the cassandra driver continue to log the WARN.
The `nodetool describecluster` shows the schema mismatch:
```
Cluster Information:
	Name: platform
	Snitch: org.apache.cassandra.locator.Ec2Snitch
	DynamicEndPointSnitch: enabled
	Partitioner: org.apache.cassandra.dht.RandomPartitioner
	Schema versions:
		a1caa56c-962f-331d-a213-af50ae234cbd: [10.48.81.144]

		8db2da85-dc5f-3d08-9140-dcbf99f1201b: [10.48.80.22]

		3a088a36-e9ca-3dc4-bbb2-a5f2ce5c9109: [10.48.82.234]
```
I had a look at the migrations classes and some of them are performed with LOCAL_QUORUM/EACH_QUORUM and some statements are executed async.
imho migrations should to be formed sync and with consistency ALL.
I understand that the change of consistency can have a big impact on big cluster (eventually to verify) but ALL assures that the migration is correctly executed on the whole cluster, that imho should be preferred outcome in this case.
Maybe is it possible to introduce a new env variable/config `REAPER_CASS_MIGRATION_CONSISTENCY` that allows to set a custom consistency level.

**Comment by adejanovski** [comment]
Hi @ltagliamonte,

are you running several instances of Reaper or just one ?

It's odd that all nodes have different schema versions and it's not clear to me why Reaper would cause this. 
DDL statements will be performed at `CL.ALL` and the Java driver will try to wait for a schema agreement across the cluster. With 3 nodes, this should be fairly easy to get to unless concurrent schema changes are performed on different nodes, which usually leads to what you're seeing. 

You have 2 fixes then : 
- perform a rolling restart to get all nodes back to agree on the schema 
- run `nodetool resetlocalschema` on one node at a time to get the same result without restarting Cassandra

Is the issue still happening when you start Reaper again after the initial migrations were all made ?

**Comment by ltagliamonte** [comment]
Hi @adejanovski I'm running a single reaper instance.

Once I stop reaper and I drop the reaper keyspace using consistency All the schema version matches among all the nodes, I checked it also before running reaper and it was matching.

Didn't try to restart reaper after the first  fail, but anyway I can't leave a schema mismatch in the cluster and it looks like that are reaper migration creating this mismatch that's why I'm reporting it.

**Comment by adejanovski** [comment]
The fact that you ran another schema migration, by dropping the keyspace, brought back an agreement. But it's not the fact that the Reaper KS exists which creates the disagreement.
You could get the agreement back by leaving the Reaper keyspace there and using one of the two techniques I suggested earlier.

Are you willing to give this another try ?
It would be helpful then to enable the DEBUG logging in Reaper and provide us the output if the disagreement happens again.

**Comment by adejanovski** [comment]
@ltagliamonte, I was able to reproduce and fix the issue. We will release 1.2.1 soon with the fix.

**Comment by ltagliamonte** [comment]
Thank you @adejanovski I read the fix and my bet was on a wrong consistency or on the order of the migrations.. will try latest 1.2.1 and reopen if not fixed.
