### ISSUE TITLE
[Question] Mismatch in the doc about backends/storage types ?

### ISSUE THREAD

**Issue by nsteinmetz** [thelastpickle/cassandra-reaper#475]
Hello,

Looking at backends in the doc, there is a point I don't understand :
- Here, we have a `database` and included the description of the backend for what I understand : https://github.com/thelastpickle/cassandra-reaper/blob/6a44f3cd2069cdf00788a07a862d6c46133e68cf/src/packaging/resource/cassandra-reaper.yaml#L74-L79
- Here we have the backend as `storageType` and as top level keyword for the datasource `postgres` and  : 
https://github.com/thelastpickle/cassandra-reaper/blob/6a44f3cd2069cdf00788a07a862d6c46133e68cf/src/packaging/resource/cassandra-reaper-postgres.yaml#L74-L77

Should the `database` section be removed from default yaml file or does it have another purpose ?

Thanks,
Nicolas

**Comment by adejanovski** [comment]
Hi @nsteinmetz,

we kept `database` for backwards compatibility reasons but `storageType` should be used with either `postgres` or `h2` from now on.
I guess we'll remove the `database` option (and the corresponding section) in the near future.

So yes, it should be removed from the default yaml files, good catch.

**Comment by amorton** [comment]
@ossarga  can we clean up the default the yaml and the docs ?

**Comment by ossarga** [comment]
@adejanovski I have opened pull request #545 with a change to amend the configuration files.

**Comment by ossarga** [comment]
@nsteinmetz I have merged Pull Request [#545](https://github.com/thelastpickle/cassandra-reaper/pull/545) which corrects the _cassandra-reaper.yaml_ file as you pointed out. Please let me know if we can close this issue or if anything further needs to be done. Thank you.

**Comment by nsteinmetz** [comment]
Sounds good too - thanks !
