### ISSUE TITLE
[1.2.0/doc] useAdressTranslator no longer present

### ISSUE THREAD

**Issue by nsteinmetz** [thelastpickle/cassandra-reaper#481]
Hello,

Seems in 1.2. the `useAdressTranslator` is no longer present but it was in 1.1: https://github.com/thelastpickle/cassandra-reaper/blob/1.1.0/src/docs/content/docs/configuration/reaper_specific.md#useaddresstranslator

But it's still mentionned here : http://cassandra-reaper.io/docs/configuration/docker_vars/

Bug or feature ?

Nicolas

**Comment by ossarga** [comment]
Nice find @nsteinmetz ! This looks like it was accidentally dropped from the documentation between versions 1.1 and 1.2.

I have raised Pull Request #546 to fix the documentation.

**Comment by ossarga** [comment]
@nsteinmetz, Pull Request [#546](https://github.com/thelastpickle/cassandra-reaper/pull/546) has been merged. Let me know if you are happy for this issue to be closed.

**Comment by nsteinmetz** [comment]
Sounds good :)
