### ISSUE TITLE
Repair is in hanging state with "Couldn't get token ranges from coordinator

### ISSUE THREAD

**Issue by razsandy** [thelastpickle/cassandra-reaper#491]
**Spotted on 1.1.0-SNAPSHOT (b170de8)**"
We are getting "i.c.s.RepairRunner - Couldn't get token ranges from coordinator: #{}" and the repair is hanging

**Comment by adejanovski** [comment]
Hi @razsandy,

The stack trace of the issue should be written in the logs just below the "Couldn't get token ranges..." message you pasted in the description. Could you paste it in your original comment so we can see what's failing specifically ?

what were the settings of your repair run ? Did you restrict by nodes or datacenters ?
Is there anything specific about your cluster that could help debugging this ? (number of vnodes, number of datacenters, replication settings of the repaired keyspace, etc...)

Thanks

**Comment by razsandy** [comment]
Hi Adejanovski,
Thanks for your quick response. The issue is due to one datacenter is removed from the previous scheduled repair. And after removing datacenter its again want to get the segments from the removed datacenter. 
After again recreating the schedulars the repair job is running fine.
