### ISSUE TITLE
reaper keeps running .. almost empty cluster .. eval setup.

### ISSUE THREAD

**Issue by bhupen303** [thelastpickle/cassandra-reaper#497]
**Spotted on 1.1.0 (03ce27f)**

**Comment by adejanovski** [comment]
Hi @bhupen303,

I do not understand the issue you're running into. Could you please elaborate on the problems you're seeing ?

Thanks

**Comment by adejanovski** [comment]
Closing this ticket, feel free to re-open if needed.
