### ISSUE TITLE
Reaper-1.2 `IllegalArgumentException: unit conflicts with existing in …`

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-reaper#498]
Since Reaper-1.2 it is not possible to run a repair manually on a keyspace or table that has a schedule assigned to it.
Attempting to create such a manual repair displays the following error in the UI

<img width="1408" alt="screen shot 2018-07-26 at 12 25 31" src="https://user-images.githubusercontent.com/559444/43240256-ebce0218-90d8-11e8-8c16-ae744a9de618.png">

… and the following error in the logs:
```
ERROR  [XXX] [XX - POST /repair_run?clusterName=…&keyspace=…&owner=…&repairThreadCount=…&incrementalRepair=…] i.d.j.e.LoggingExceptionMapper - Error handling a request: …
java.lang.IllegalArgumentException: unit conflicts with existing in …:…
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at io.cassandrareaper.service.RepairUnitService.createRepairUnit(RepairUnitService.java:68)
	at io.cassandrareaper.service.RepairUnitService.getOrCreateRepairUnit(RepairUnitService.java:64)
	at io.cassandrareaper.resources.RepairRunResource.addRepairRun(RepairRunResource.java:204)
        …
```

This is a intended change in Reaper-1.2 and avoids unintentional conflicts/overlaps between users and repair runs.

The correct way to manually do such a repair on a keyspace/table that is already under a schedule, is to go to that schedule and press the 'Run Now' button.

**Comment by a1exsh** [comment]
I find this experience quite confusing.  Could we at least provide a proper error message?

How can I test effect of using more repair threads?  If I use 'Run now' from the schedule, it doesn't allow me to tune the parameters.  I don't want to make another schedule just for testing it once.

**Comment by a1exsh** [comment]
> I don't want to make another schedule just for testing it once.

Huh, that I even cannot do, because it gives me this error:
`A repair schedule already exists for cluster "clustername", keyspace "keyspacename", and column families: []`

How can I test more repair threads then w/o deleting the existing schedule first?  Can I *edit* a schedule to tune the parameters?  I don't see a button for that...  But maybe via the API?

**Comment by michaelsembwever** [comment]
> I find this experience quite confusing. Could we at least provide a proper error message?

A better error message is needed.

> How can I test more repair threads then w/o deleting the existing schedule first?  

There currently is no way of doing that.
It was important to clean the code up to prevent multiple (and overlapping) repair units/schedules, due to technicalities in how the different schemas work between different backends.

It would make sense to be able to edit a schedule, but AFAIK you have to delete it and recreate it for now.

**Comment by lapo-luchini** [comment]
This also makes impossibile to have a "weekly incremental, monthly full repair" set of schedules. 😔
