### ISSUE TITLE
Formalize branching and release cycle conventions

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#5]
This can probably be hashed out pretty quickly, but I want it here as a reminder.  I want to make sure we adopt a formal release process starting with the 0.4 release in order to be able to make bug fixes as well as adopt new features.

My proposal is to follow semver closely:

For feature development:
1. New features is done in branches off master
2. Features are to be reviewed by a committer
3. New features are merged to master

For a release:

1a. For a minor release (0.4, 0.5, 1.0, etc) start by cutting a new branch.  We can bikeshed the naming convention but for now I'll just use `x.y`.  No patch indicated.  Any preference on a prefix?
1b. For a bug fix release cutting a new branch is not necessary, as the bug fix should be merged into the branch created in 1a.
2. Create a new tag for the release prefixed with `v` plus the semver release version.  For example, `v1.0.0` is a major release, `v0.4.0` is a minor release `v0.4.1` is a bug fix release.
3. Major releases are done to indicate backwards incompatibility.  The exception to this would be releases prior to 1.0, which may change as things are rapidly stabilized.

For this issue to be closed we must update the readme with these release details.

**Comment by adejanovski** [comment]
We've addressed this for a while now.
Closing.
