### ISSUE TITLE
Maven repository for cassandra-reaper

### ISSUE THREAD

**Issue by m2spring** [thelastpickle/cassandra-reaper#504]
Can you please deploy the binaries to a Maven repository (e.g. Maven Central) so I don't have do a **manual** download to get a newer release and let Maven do this instead?
-Max

**Comment by michaelsembwever** [comment]
Sorry about that @m2spring , bit of a mix up on our side with the release process.
Should be good now, eg https://repo.maven.apache.org/maven2/io/cassandrareaper/cassandra-reaper/1.2.2/
