### ISSUE TITLE
Can't seem to forget a cluster

### ISSUE THREAD

**Issue by tsnyder91** [thelastpickle/cassandra-reaper#511]
**Spotted on 1.2.2 (0446d2d)**
We are setting this up with a new cluster, we messed up and terminated a few of them in aws console, so the reaper UI shows them as RED.

If I say, "Forget Cluster" it goes away, but then when I add the cluster back it seems to be pulling from some sort of cached entry somewhere and did not actually delete anything, because it has the nodes that were terminated and are gone, along with the new nodes we spun up to replace them.

How do I get the UX to forget a cluster or even better, refresh a cluster with the newest node information?

nodetool status only reflects the current nodes that are live and running, there are no "DN" nodes.  

I'm using the Cassandra backend.

Let me know how I can help troubleshoot this more.

**Comment by tsnyder91** [comment]
Seems like it might be reading from gossip state. Cassandra is new to me so bare with me. 

Maybe the UX will update after it cleans up the gossip states over time?

**Comment by adejanovski** [comment]
Hi @tsnyder91,

sometimes gone nodes still appear in Gossip indeed, and that's what Reaper uses.
Did you remove the nodes using `nodetool removenode <node id>` or did you replace them by bootstrapping the new nodes with `-Dcassandra.replace_address_first_boot` ?

If you did one of the above and the nodes still appear in Gossip, you can : 
- try to roll restart the cluster
or
- go to each node, run `nodetool gossipinfo` to check which nodes still see the gone ones. Then use `nodetool assassinate` to remove the terminated nodes from gossip (careful with that command, you don't want to run it on a live node).

**Comment by tsnyder91** [comment]
Thanks for the above and beyond tips @adejanovski  We did the removenode on some and nodetool decommission on others.  we also have done assasinate but not on every node so that or a rolling restart seems in order.  I'll close this out since it's not a problem with reaper, and more my inexperience with all the seemingly hidden ways nodes stick around beyond nodetool status
