### ISSUE TITLE
continuous reaping

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#52]
Perhaps a silly idea, but we should discuss having reaper running constantly, throttling itself back based on metrics like load, dropped messages, etc.  Then it could scale back on it's own when load is high and take care of business when load is low

**Comment by eriksw** [comment]
I'd be quite interested in a "continuous" mode for use with incremental repairs.

**Comment by adejanovski** [comment]
@eriksw : you can create a continuous schedule by setting the interval to 0. Each time a repair ends, it gets triggered again.

**Comment by adejanovski** [comment]
Since continuous reaping is already supported and we currently have no intent of throttling based on anything else but pending compactions/running repairs, I'll close this ticket.
Let's re-open a new one if we feel that we want to throttle based on other metrics.
