### ISSUE TITLE
Parameter segmentCountPerNode is not pre-defaulted on schedule creation

### ISSUE THREAD

**Issue by mparkachov** [thelastpickle/cassandra-reaper#523]
The parameter segmentCountPerNode from configuration file is ignored when creating new schedules. It sets to 0 instead of value from configuration file. If I create repair manually it is correctly defaulted to value in configuration file.

version: 1.2.2

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-364) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-364

**Comment by adejanovski** [comment]
This was fixed a while ago now. Closing the ticket.
