### ISSUE TITLE
How to execute cluster wise repair 

### ISSUE THREAD

**Issue by shamimgeek** [thelastpickle/cassandra-reaper#530]
How can in execute repair for all keyspaces. Does it support * ?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-365) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-365

**Comment by adejanovski** [comment]
This is not supported. Repairs are done per keyspace.
Autoscheduling can help with this as all of your keyspaces will be automatically be scheduled, but run separately.
