### ISSUE TITLE
Apply copyright headers to all source files

### ISSUE THREAD

**Issue by michaelsembwever** [thelastpickle/cassandra-reaper#531]
Apply the copyright header `Copyright 2014-2018 The Last Pickle Ltd` to all source files.

Open source projects and their licenses are a lot safer if all source files are copyrighted to the one entity. It is also a requirement to [move](https://lists.apache.org/thread.html/20c720f71fe48a6c6cf0f89ef399fd40ba89513b509588444276e296@%3Cdev.cassandra.apache.org%3E) projects into foundations like the Apache Software Foundation.

Indeed it is normal for many projects to imply that copyright is provided with contributions, and with Spotify's copyright notice in `LICENSE.txt` it seems this was likely an intention, and I suspect all contributors expect the copyright assignment to occur when they open pull requests with contributions. 

As far as individuals go, do any of you object to the copyright headers being applied to your past contributions?
Bj0rnen  varjoranta djsly Yarin78 mattnworb rouzwawi vrischmann dormidon kipwoker internetstaff elsmorian anguenot MALPI neogenix ahenry pndewit n0rad mmatalka skhatri smarsching favoretti echoajohnson SaaldjorMike mcoolive tedoc2000 debswade kingm5 a1exsh denniskline

(We will also need to get the formal agreement from Spotify to grant the copyright.)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-366) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-366

**Comment by tedoc2000** [comment]
I'm good with the copyrights being applied

**Comment by MALPI** [comment]
Fine by me.

**Comment by a1exsh** [comment]
OK with me.

**Comment by pndewit** [comment]
No objections 👍

**Comment by smarsching** [comment]
That's fine by me (I do not think that my contributions are so significant that they merit a copyright of their own anyway).

**Comment by vrischmann** [comment]
Ok with me

**Comment by internetstaff** [comment]
No objection - thanks for asking.

**Comment by djsly** [comment]
All good here as well.

**Comment by anguenot** [comment]
Fine by me. Insignificant contrib from me anyway. Thank you for asking though.

**Comment by SaaldjorMike** [comment]
Fine by me. I'm in a similar situation as @anguenot.

**Comment by ahenry** [comment]
I'm happy to assign the copyright on my tiny contribution to you.

**Comment by michaelsembwever** [comment]
Small change of plan here. We're looking at adding instead the copyright header `Copyright 2014-2018 Spotify AB` to all source files.
I'm going to presume no one that's replied already objects to that.
Spotify already has a CLA signed and submitted with the Apache Software Foundation, so this way we achieve the same with less effort.

**Comment by elsmorian** [comment]
Fine with me 👍

**Comment by kipwoker** [comment]
Fine 👍

**Comment by michaelsembwever** [comment]
At this point in time it's unclear whether Reaper will be accepted as a donation into the Apache Cassandra project, as there are competing repair management tools on offer.

Tt is still important to simplify the project's copyright. And this was the original and stated intent of this ticket.

The best that can be done for now is to split the copyright between three holders. 

Files will then have one of the following three copyright headers:
a)
```
Copyright 2014-2018 Spotify AB
Copyright 2014-2018 The Last Pickle Ltd
```
b)
```
Copyright 2015-2018 Stefan Podkowinski
Copyright 2015-2018 The Last Pickle Ltd
```
c)
```
Copyright 2014-2018 The Last Pickle Ltd
```

A `CONTRIBUTING.md` will also be added to state the copyright license agreement with contributions, as the `NOTICE.md` does for the implied license for the contribution.
https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license

For large contributions it would still be required to receive a signed CLA from individual/company.

**Comment by michaelsembwever** [comment]
Still unanswered contributors: @mattnworb @dormidon @neogenix @mmatalka @skhatri @echoajohnson @debswade @kingm5 @denniskline 

Folk, if we don't hear from you and get an agreement, we may need to remove your commits from the project.

**Comment by neogenix** [comment]
👍 fine by me.

**Comment by mattnworb** [comment]
commits from me should have the “Copyright Spotify” bit 👍

**Comment by michaelsembwever** [comment]
Still waiting to hear from  @mmatalka @skhatri @echoajohnson @debswade @kingm5 @denniskline

I have checked their commits and none of them have committed new code files to the projects, rather only offering contributions to existing files, so applying the copyright header to those files should be ok (as the LICENSE file with the Copyright statement was in place already).

**Comment by michaelsembwever** [comment]
Yes, thanks @Bj0rnen !

**Comment by varjoranta** [comment]
I'm fine with it. Sorry for late answer... parental leave.
