### ISSUE TITLE
"spreaper ping" fails

### ISSUE THREAD

**Issue by shawnbutts** [thelastpickle/cassandra-reaper#532]
This is on a fresh install of 1.2.2

`# Sending PING to Reaper...
Traceback (most recent call last):
  File "/usr/local/bin/spreaper", line 797, in <module>
    ReaperCLI()
  File "/usr/local/bin/spreaper", line 390, in __init__
    getattr(self, command)()
  File "/usr/local/bin/spreaper", line 409, in ping
    printq("# [Reply]", answer)
TypeError: printq() takes exactly 1 argument (2 given)`

**Comment by rzvoncek** [comment]
It's been a while since this was opened. Also, chances are this got _organically_ resolved meanwhile. (At least I could use spreaper just fine via current Reaper docker image built from master).

We can always expedite fixing this in case the issue is still there ;-)
