### ISSUE TITLE
Docker image tag 

### ISSUE THREAD

**Issue by riccardo-ferrari** [thelastpickle/cassandra-reaper#539]
Hey guys,

Thank you for the nice tool!

I was checking the docker image tags and found the following:
* `latest` points to `1.2.1` and the both got an update "2 days ago" (and have the same hash)
* I see https://github.com/thelastpickle/cassandra-reaper/releases/latest that should be `1.2.2` however on docker hub it was last updated "a month ago" 

Not sure it is intended or an image push issue.
Thanks

**Comment by adejanovski** [comment]
Hi,

indeed I had the 1.2.1 tag still being pushed from my local git repo.
I deleted it and pushed 1.2.2 again as latest.

Thanks for pointing it out !
