### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by brstgt** [thelastpickle/cassandra-reaper#54]
Hi folks. Thanks for your work on reaper!
To track your changes a simple changelog.md would be awesome.

**Comment by adejanovski** [comment]
Hi @brstgt,

you're right ! We've started making GitHub releases with a short "What's new" text but a changelog is definitely needed.
We'll initiate one shortly.

Cheers !

**Comment by adejanovski** [comment]
Changelog added with the merge of autoscheduling : https://github.com/thelastpickle/cassandra-reaper/blob/master/changelog.txt
