### ISSUE TITLE
Supported versions

### ISSUE THREAD

**Issue by gustavo-momente** [thelastpickle/cassandra-reaper#540]
I don't know if the documentation hasn't been updated in a while or if the actual support stops at Cassandra version 3.10. 

Because at the [docs](http://cassandra-reaper.io/docs/) it's stated:

> Reaper supports all versions of Apache Cassandra ranging from 1.2 to 3.10.

And we currently run a newer version of Cassandra, but we're looking forward to use cassandra-reaper

Thanks

**Comment by adejanovski** [comment]
Hi @gustavo-momente,

it's just docs that aren't up to date. 
Reaper works fine with all versions up to the latest 3.11.3 (and it even works with the upcoming 4.0).

Cheers
