### ISSUE TITLE
Cannot Add Schedule/Repair

### ISSUE THREAD

**Issue by yan-dblinf** [thelastpickle/cassandra-reaper#551]
**Spotted on 1.2.2 (0446d2d)**

Background: We have two apache-cassandra 3.11 clusters running on the same data center. On each node of second cluster, a cassandra-reaper instance is running, using second cluster as persistent storage. Cassandra-reaper is used to manage repair of both first and second cluster. 

Here is the bug: when start a new schedule/repair on schedules.html and repair.html respectively, the **button** Schedule/Repair is **disabled** even all required field has been filled for first cluster, which is the default value for cluster field. Also, when type at keyspace field, the name would not be autocompleted. 

How to fix: In order to add a new schedule/repair, we have to change value of cluster field to second cluster, where reaper instances are living on, then change the value back to first cluster. Now the button Schedule/Repair is enabled after all required field is filled.

**Comment by adejanovski** [comment]
This should be fixed in the latest versions. Feel free to reopen I needed.
