### ISSUE TITLE
Unable to schedule multiple repair schedules for the same keyspace on single reaper instance

### ISSUE THREAD

**Issue by ponnamvivek** [thelastpickle/cassandra-reaper#555]
Unable to schedule multiple repair schedules for the same keyspace on single reaper instance.
Can you please shed some light on this issue
Thanks.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-371) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-371

**Comment by adejanovski** [comment]
There have been improvements in later versions and you can now create (to some extent) different schedules with different settings for the same keyspace (especially mixing full and incremental repairs).
