### ISSUE TITLE
Exception logging when doing is repair running check

### ISSUE THREAD

**Issue by nbozic-zz** [thelastpickle/cassandra-reaper#56]
`JmxProxy` is doing a check if repair is running or not. Between pre 2.2 and post 2.2 version MX bean names have changes and check if repair is running will always issue `InstanceNotFoundException` in one of the checks which will get logged and pollute logs even though it is expected. 

Version of Cassandra should be checked and only one way of checking should be done, or only exception message should be logged since it is expected to have exception here.

**Comment by adejanovski** [comment]
We'll keep those log in DEBUG mode because they might be useful to troubleshoot Reaper's behavior in the future.
Pre/post 2.2 checks are now fixed in master.
