### ISSUE TITLE
Probable memory leak in cassandra-reaper

### ISSUE THREAD

**Issue by carlo4002** [thelastpickle/cassandra-reaper#560]
We are testing cassandra-reaper in our clusters.We have only one instance of reaper to run repairs on 3 cluster. We saw this warning in the logs 

WARN   [dw-891] o.e.j.u.t.QueuedThreadPool - dw{STARTED,8<=1024<=1024,i=0,q=1024} rejected org.eclipse.jetty.io.ManagedSelector$CreateEndPoint@652f93ed 

and after some googling, I found this issue in jetty

https://github.com/eclipse/jetty.project/issues/1705 

I am not sure if this is the cause of the problem but after checking the gc.log of cassandra-reaper, we identified a memory leak 

http://gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMTgvMDkvMjAvLS1nYy5sb2cuMC5jdXJyZW50LS0xMS01NC00OQ==

Can someone tell me which version of jetty cassandra reaper use ?

**Comment by adejanovski** [comment]
Jetty was upgraded a while ago now, so I'm assuming this was fixed.
Feel free to reopen if needed.
