### ISSUE TITLE
Contribution guidelines are unclear on details of the CLA

### ISSUE THREAD

**Issue by danielkza** [thelastpickle/cassandra-reaper#561]
What a "copyright grant" is completely unspecified in the contribution guidelines. Is it meant to be *assignment*, such that all rights are waived, and The Last Pickle is allowed to re-license contributions in any  way they see fit? I don't believe that kind of assignment can be made implicitly without contributors signing a legal document.

If the intention was just to make it explicit that contributions are provided under the same *license* as the whole project,  using different terminology (such as *license grant*) would be much better.

If actual assignment is expected, I urge The Last Pickle to reconsider that requirement. CLAs are actively harmful to free software projects. Some people will be barred from contributing due to legal issues (since they cannot grant copyright on work they are being hired to do). Others might avoid the project considering the imbalance inherent to demanding copyright assignment of voluntary work.

The permissive nature of the Apache license should be more than sufficient to allow TLP to use the contributions in their private endeavors.

**Comment by michaelsembwever** [comment]
We want to minimise introducing new copyright holders into the project, so a 'copyright grant' (rather than assignment) is desired.
But this only applies to new files, and hopefully with the code in a more up to date state (and the rat maven plugin in place), it's become easier (and part of the PR review) to request that grant from any contributor.

Would it help if the 'requested copyright grant' (CLA) was made more explicit also in the pull request, something like https://github.com/openzipkin/zipkin/blob/master/.github/CONTRIBUTING.md ( https://blog.github.com/2012-09-17-contributing-guidelines/#contributors-wanted-inquire-within )

**Comment by danielkza** [comment]
> We want to minimise introducing new copyright holders into the project, so a 'copyright grant' (rather than assignment) is desired.

I think we might be operating under different terminology, but what you described is not possible. You want to mix properties of different copyright/licensing schemes for contributions that can't really be mixed.

There are basically four different ways to deal with contributions; any option other than the first must be very explicit in the contribution guidelines (the current text is too vague).

a) Any contributions are *implied* to be licensed under the same terms as the whole project. Implied licenses are defined in the copyright laws of most countries, and relatively uncontroversial. That is the case for most projects, since they rarely say *anything* about the legal status of contributions.

b) Any contributions are *explicitly* licensed under the same terms as the whole project. That does *not* imply any change in copyright ownership, and *does not* grant the project owner any rights other than to those present in the project license. For example, if the project is copyleft, the project owner is also required to redistribute source code if they include any of the external contributions that are copyleft.

c) Contributions are only accepted if a CLA is signed by the author, usually granting the project owner rights that are *more broad* than those specified in the original license. For example, the right to use the contributions in proprietary fashion, even if the original license is copyleft. I don't think this case can ever happen in implied fashion, unless another contributing factor (such as a work relationship) is present. An actual agreement *must* be signed.
One (in)famous example of this case is Ubuntu's [upstart](http://upstart.ubuntu.com/). The CLA has been cited as one of the reasons systemd was created to replace it, and hence, has had *negative* impact on the project.

d) Contributions are only accepted if copyright is *transferred* to the project owner. That effectively means the code for the whole project is held by a single entity. Many people in the FOSS community consider that predatory behavior *unless* contributions are also *required* to be released under a FOSS license. This model is used, for example, by the Free Software Fundation in the GNU project, so that they can legally represent the project as a whole in any legal disputes.

---

This project was previously operating under situation A, as no contributing guidelines was present until last week. The example of Zipkin you mentioned is of situation B. But what you actually stated that you want is situation D - which I find very unpleasant to deal with, and unacceptable if an explicit promise to keep the project FOSS does not accompany it. Situation C does not seem very relevant to this project, as the Apache license is permissive enough that TLP (or anyone, really) can already release proprietary forks.

**Comment by michaelsembwever** [comment]
Yes, we're aiming at (d), and we're seeking community acceptance for that via #531

I don't have a problem with making the promise to keep the project under APLv2, although I would have thought that was implied as it's hosted on github and decentralised via git (we can't exactly take back the code, nor retro-actively change the license). I guess this can be taken one step further to promise that the project will not be developed by TLP under a different license or behind closed doors. I don't think others, nor TLP, would have any objection to making that statement.

Zipkin is more than just (b), the contributing guidelines explicitly states that copyright shall be assigned/held by `The OpenZipkin Authors`.

**Comment by danielkza** [comment]
> Yes, we're aiming at (d), and we're seeking community acceptance for that via #531

Did you consider that might stop employed developers from contributing to the project during work without legal clearance? Employees do not have the power to transfer or assign copyright on work made for hire. Any particular concern about TLP that would not be solved by an explicit *license* grant? Copyright transfer seems way too heavy handed for little gain IMO ([and of some actual lawyers[(https://sfconservancy.org/blog/2014/jun/09/do-not-need-cla/)).

edit: For example, notice how the [OpenSSL project](https://www.openssl.org/policies/cla.html) requires a Corporate CLA to accept contributions of company employees. That is a level of hassle I would not want to go through to contribute to Reaper (which is very useful software that I would like to help with),

> Zipkin is more than just (b), the contributing guidelines explicitly states that copyright shall be assigned/held by The OpenZipkin Authors.

The guidelines do not explicitly mention any copyright assignment or transfer, only licensing. I don't believe the use of the project collective in the header changes that, or that it would be sufficient in a legal setting. There are other more carefully crafted guidelines that provide better guarantees without requiring (or being ambiguous about) copyright transfer, such as the [Developer Certificate of Origin](https://developercertificate.org/) used by the Linux kernel.

**Comment by michaelsembwever** [comment]
> Employees do not have the power to transfer or assign copyright on work made for hire. 

Like Spotify and Stefan Podwinski, we'd of course consider adding a copyright holder if the contributions were significant and otherwise unavailable.

> Copyright transfer seems way too heavy handed for little gain IMO.

The background to this is the discussion about contributing the codebase to Apache Cassandra. IP Clearance is a requirement, and we currently have CLAs in place with the three copyright holders. This lead on to simply doing the exercise to clarify these things, learn and tidy.

Note that the Apache projects have also become less strict with the copyright grant on smaller contributions. Committers, and large contributions, require ICLAs (and a company CLA is appropriate), but contributions through jira tickets and patches are presumed to include the copyright grant. Apply the copyright header *during* the pull request I would think makes that grant explicit (it doesn't imply a re-assignment as it's clear who the author is, and the grant is explicit in the patch from the author).

**Comment by danielkza** [comment]
I can understand the situation better now, but unfortunately I still don't believe what you stated can work.

1) The Apache CLA does not involve copyright *assignment*. It only refers to *licensing* of use and distribution. That distinction is very significant.
2) The Apache CLA is very clear and unambiguous. It explains in detail what rights are being conceded and how.
3) When the Apache Foundation chooses to accept contributions without the signed CLA, they are relying on an implied *license* provided with the work. Copyright assignment does not take part at all, and you cannot assume the same rules apply. The [FSF, for example, requires](https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html) a signed agreement from contributors to projects they hold the copyrights to, and a waiver from an employer if applicable. My understanding is that copyright transfers require stronger affirmation than mere licenses.

IMO adding a document to the repository with an explicit CLA (which can be directly adapted from Apache's) should satisfy all your requirements and severely reduce ambiguity and possible contributor-hostility. Would that be acceptable?

**Comment by michaelsembwever** [comment]
> When the Apache Foundation chooses to accept contributions without the signed CLA, they are relying on an implied license provided with the work. 

All code residing in Apache projects must be copyrighted to the Apache Software Foundation. A copyright grant is essential of all contributions, and part of the IP Clearance process of bringing in code (eg via the Incubator).
This is covered by `2. Grant of Copyright License.` in the ASF ICLA. Contributors are free to maintain their copyright outside of the ASF, but that which is contributed to the ASF is copyrighted by the ASF. Are we talking past each other here?

> IMO adding a document to the repository with an explicit CLA (which can be directly adapted from Apache's) should satisfy all your requirements and severely reduce ambiguity and possible contributor-hostility. Would that be acceptable?

Yes. Reducing ambiguity, on a topic complex and/or unknown for most, would be wise.

**Comment by danielkza** [comment]
Sorry for being insistent, but granting a *license* to use of a copyrighted work is not the same as transferring ownership of the copyright *itself*. The Apache CLA  is a *license* grant. It even explicit mentions so, and that no other rights (*especially* the ownership of the copyright itself) are transferred.

> Except for the license granted herein to the Foundation and recipients of software distributed by the Foundation, You reserve all right, title, and interest in and to Your Contributions.

The Foundation's [licensing instructions](https://www.apache.org/legal/src-headers.html) also explicit mentions that authors do not have to forfeit ownership of their work (highlights are mine):

> Apache products are composed of lots of pieces of code across numerous source files, **licensed** to the ASF by various authors who **maintain ownership** of their contributions.

Copyright *assignment* does not seem necessary to get the code into Cassandra eventually. As I said, option D is overkill and a logistical nightmare, and why most projects avoid it unless absolutely necessary. Option C with a CLA like Apache's would be more than sufficient, and much less likely to cause discomfort to contributors.

I'm not an active member of the Cassandra or Apache communities, but I can try to get in contact with someone better informed than me to confirm my view. Thanks for spending your time with this boring legalese talk, but I really like this project and I would be very discontent if I had to avoid contributing in the future.

**Comment by michaelsembwever** [comment]
Reaper is not attempting for copyright assignment, only a grant to license the work under the APLv2 with copyright to The Last Pickle Ltd (except for named exceptions). The same sort of license grant that the ASF asks of contributors, and the same as Zipkin as well. I'm guessing this is what you mean by (b) then.  Shall I [update](https://github.com/thelastpickle/cassandra-reaper/pull/562) `CONTRIBUTING.md` accordingly, as I believe that's what you were first raising concern to?

**Comment by danielkza** [comment]
> I'm open (and it certainly wouldn't be correct for only me to make the decision) to either approach:
> What's are your thoughts, now that you've got a better idea of what we're aiming for?

I'm currently just an user (and not a lawyer), so your opinion (and of other devs) is surely much more relevant :)

As an outside contributor, I never want any chance that I am blocked from contributing due to legal shenanigans. In that light, a CLA is best avoided if at all possible. The Zipkin-style contributing guidelines should be good enough, as they are for the vast majority of projects. It's easy for everyone to understand; all the code in-and-out of the project is APL2.

Whether a CLA would be needed to merge things back to Cassandra is something only the Cassandra (and Apache) community can answer. I would personally worry about that later when (or if) the question arises.

Thank you again for your patience.

**Comment by michaelsembwever** [comment]
Ok, thanks for the input and catching the incorrectness/ambiguity @danielkza 

Reaching out to others as to what they think and would prefer: @spodkowinski @Bj0rnen @adejanovski @rustyrazorblade @varjoranta @djsly @joaquincasares (+anyone else).
It seems like the current preference is for the simpler #562 approach.
