### ISSUE TITLE
reaper_db.repair_run_by_cluster schema ASC for DESC

### ISSUE THREAD

**Issue by thetdh** [thelastpickle/cassandra-reaper#568]
While it would take some time for this to show, the fact that the schema for reaper_db.repair_run_by_cluster has "WITH CLUSTERING ORDER BY (id ASC)" instead of "WITH CLUSTERING ORDER BY (id DESC)" means that eventually, the 1000-result limit in CassandraStorage.getRepairRunsForCluster() will fail to include the most-recent runs.  (Ten keyspaces repaired at seven-day intervals would take nearly two years to show this problem.)

A possible transitional workaround would be to alter the query to specify "ORDER BY id DESC".

I wonder also if fetching an unlimited number of results, limited only by code fetching the results, will eventually cause a problem.  Last I looked, LIMIT couldn't be parameterized in a prepared statement, but it should be possible to chunk results with a fixed LIMIT if also using "WHERE id < ?".

**Comment by adejanovski** [comment]
This was fixed in the latest versions.
