### ISSUE TITLE
Fails on running Cassandra server

### ISSUE THREAD

**Issue by postformeravi** [thelastpickle/cassandra-reaper#569]
Full Product Version :

Fails on java version. It's Java "1.8.0_181"

Os Version : Ubuntu 16.04 LTS

EXTRA RELEVANT SYSTEM CONFIGURATION :

Just installed Cassandra 2.2.11 

A DESCRIPTION OF THE PROBLEM : 
#

A fatal error has been detected by the Java Runtime Environment:
#
SIGBUS (0x7) at pc=0x00007f42fc492e70, pid=12128, tid=0x00007f42fc3c9700
#
JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
Problematic frame:
C [liblz4-java8098863625230398555.so+0x5e70] LZ4_decompress_fast+0xd0
#
Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.
#
--------------- T H R E A D ---------------

Current thread (0x00000000006d0800): JavaThread "CompactionExecutor:7" daemon [_thread_in_native, id=5278, stack(0x00007f42fc389000,0x00007f42fc3ca000)]

siginfo: si_signo: 7 (SIGBUS), si_code: 2 (BUS_ADRERR), si_addr: 0x00007f2026b8b000

Registers:
RAX=0x00007f432200750a, RBX=0x00007f2026b8affc, RCX=0x00007f4322005856, RDX=0x00007f432200750a
RSP=0x00007f42fc3c7e50, RBP=0x00007f2026b8940f, RSI=0x00007f4322011d88, RDI=0x0000000000000007
R8 =0x00007f4322011d84, R9 =0x00007f4322011d90, R10=0x0000000000000003, R11=0x0000000000000000
R12=0x0000000000000000, R13=0x00007f1ffe33d40f, R14=0x00007f4322011d87, R15=0x00007f4322011d8b
RIP=0x00007f42fc492e70, EFLAGS=0x0000000000010287, CSGSFS=0x002b000000000033, ERR=0x0000000000000004
TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f42fc3c7e50)
0x00007f42fc3c7e50: 00004ce900000000 0000000000000000
0x00007f42fc3c7e60: 0000000000000004 0000000000000001
0x00007f42fc3c7e70: 0000000000000002 0000000000000001
0x00007f42fc3c7e80: 0000000000000004 0000000000000004
0x00007f42fc3c7e90: 0000000000000004 0000000000000004
0x00007f42fc3c7ea0: 0000000000000000 0000000000000000
0x00007f42fc3c7eb0: 0000000000000000 ffffffffffffffff
0x00007f42fc3c7ec0: 0000000000000000 0000000000000001
0x00007f42fc3c7ed0: 0000000000000002 0000000000000003
0x00007f42fc3c7ee0: 00007f42fc3c7fa8 00000000006d09f8
0x00007f42fc3c7ef0: 0000000000000000 0000000000000000
0x00007f42fc3c7f00: 00007f1ffe33d40f 00007f4322001d90
0x00007f42fc3c7f10: 000000002884c000 00007f42fc48f59d
0x00007f42fc3c7f20: 0000000733b5fa78 0000000000000000
0x00007f42fc3c7f30: 00007f42fc3c7fc0 0000000000000000
0x00007f42fc3c7f40: 000000002884bfff 00007f42fc3c7fa8
0x00007f42fc3c7f50: 00000000006d0800 00007f43119e8f1d
0x00007f42fc3c7f60: 00007f42fc3c7f98 0000000000000000
0x00007f42fc3c7f70: 0000000000010000 0000000000000000
0x00007f42fc3c7f80: 000000070764f4d8 0000000000000000
0x00007f42fc3c7f90: 0000000000000000 000000075b5937f0
0x00007f42fc3c7fa0: 00007f42fc3c7ff0 00000006f91d2e38
0x00007f42fc3c7fb0: 00000006d7e3f210 00007f42fc3c8040
0x00007f42fc3c7fc0: 000000070764f4d8 00007f4311f9eca8
0x00007f42fc3c7fd0: 0000510700010000 000000072dc9abb0
0x00007f42fc3c7fe0: 0000000028851103 00000006dd2d0000
0x00007f42fc3c7ff0: 000000022883f40b eb6b26fe2884bffc
0x00007f42fc3c8000: 000000070764f4d8 000100002884c000
0x00007f42fc3c8010: 000000075b5937f0 000000075b5937f0
0x00007f42fc3c8020: 0000000600000008 00000006d7f67598
0x00007f42fc3c8030: 00000006d7f67348 00007f43120080d4
0x00007f42fc3c8040: 0000000000000001 00000006d7f676d8

 

 

SYSTEM CONFIGURATION :

 

CPU - Intel Core i7 - 4771 CPU @ 3.50 GHz * 8
2. RAM - 16 GB
3. STORAGE - 967.6 GB
4. OS - Ubuntu 16.04 LTS
5. Apache Cassandra - 2.2.11
6. CPP Driver - 2.2.1-1
7. libuv - 1.4.2-1 
8. Java version - "1.8.0_181" 
Java (TM) SE Runtime Environment (build 1.8.0_181-b13)
Java Hotspot (TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
 

Cassandra was working normally before generating this bug. Now when i am trying to restart my server getting this bug.

Please help me asap.

**Comment by michaelsembwever** [comment]
It's unclear how this is related to the Cassandra-Reaper project. (It looks to be only Cassandra related.)

**Comment by postformeravi** [comment]
Can you help me in this?

**Comment by adejanovski** [comment]
We cannot as your issue doesn't relate to Reaper. Please reach out on the Apache Cassandra users mailing list to get help from the community : http://cassandra.apache.org/community/
