### ISSUE TITLE
Add ability to repair a specific set of nodes

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#57]
Reaper should be able to repair a single node or a given set of nodes.
Currently Reaper creates segments for the whole token ring, but should be able to repair only the segments that one node is responsible (or replica) for.

This would allow to run downtime/outage related repairs in Reaper, which is not currently possible.

**Comment by michaelsembwever** [comment]
what's the difference between this issue and https://github.com/thelastpickle/cassandra-reaper/issues/165 ?

**Comment by adejanovski** [comment]
It's the same.

Closing this one as duplicate.
