### ISSUE TITLE
Compiling twice in docker build

### ISSUE THREAD

**Issue by cscetbon** [thelastpickle/cassandra-reaper#570]
There should run only once at https://github.com/thelastpickle/cassandra-reaper/blob/master/src/packaging/docker-build/Dockerfile#L48-L49

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-374) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-374

**Comment by ossarga** [comment]
No longer an issue. Closing.
