### ISSUE TITLE
How to schedule a repair with reaper tool only on weekdays (Monday to Friday)?

### ISSUE THREAD

**Issue by ponnamvivek** [thelastpickle/cassandra-reaper#571]
How to schedule a repair with reaper tool only on weekdays (Monday to Friday)?? adejanovski amorton

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-375) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-375

**Comment by adejanovski** [comment]
Hi @ponnamvivek,

this is not currently supported by Reaper's scheduler, sorry.

**Comment by adejanovski** [comment]
Closing as duplicate of #447
