### ISSUE TITLE
Cannot add cluster due to `Failed creating a new JMX connection to cassandra`

### ISSUE THREAD

**Issue by spinus** [thelastpickle/cassandra-reaper#572]
I've tried different versions of reaper (1.2, 1.3 from master, some old version I don't remember) on different versions of cassandra (1.2.19, 3.10, 3.11) using docker-compose (from this repo, `docker-compose up reaper cassandra`), using my own docker image and also using production setup on EC2.
In each case, I'm able to connect to port 7199 and 9042 (and others as well) using telnet or netcat. I'm able to connect through IP (docker host IP, container IP, docker link DNS name, EC2 private IP, DNS to private EC2 IP).

But on each of that cases I have exactly the same error (this is one I've tried through docker-docker DNS link):
```
reaper-in-memory_1     | INFO   [2018-10-13 13:14:18,464] [dw-15 - POST /cluster?seedHost=cassandra] i.c.r.ClusterResource - POST addOrUpdateCluster called with seedHost: cassandra 
reaper-in-memory_1     | ERROR  [2018-10-13 13:14:18,726] [dw-15 - POST /cluster?seedHost=cassandra] i.c.j.JmxConnectionFactory - Failed creating a new JMX connection to cassandra 
reaper-in-memory_1     | java.lang.RuntimeException: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to cassandra:7199
reaper-in-memory_1     | 	at io.cassandrareaper.jmx.JmxConnectionFactory$JmxConnectionProvider.apply(JmxConnectionFactory.java:229)

```

Is that a bug or am I doing something terribly wrong?

**Comment by nsteinmetz** [comment]
Hi,

Could you share your configuration and docker-compose file ? Are you sure about the dns resolution of "cassandra" in your environment ?

**Comment by spinus** [comment]
I was using dockerfile of this repo. And im sure about dns, as i wrote, i can connect from reaper container using other method to that port using both ip and dns.

I will provide steps to reproduce.

On October 15, 2018 10:28:56 AM GMT+02:00, Nicolas Steinmetz <notifications@github.com> wrote:
>Hi,
>
>Could you share your configuration and docker-compose file ? Are you
>sure about the dns resolution of "cassandra" in your environment ?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thelastpickle/cassandra-reaper/issues/572#issuecomment-429753812

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by adejanovski** [comment]
@spinus, did you enable external access to JMX on the nodes and disabled authentication?
If authentication is enabled, did you correctly configure Reaper to authenticate for JMX calls?

**Comment by spinus** [comment]
Steps that I'm using to try for the simplest scenario
```
cd src/packaging
vim docker-compose.yml  # I'm changing reaper image to one that's on docker-hub
docker-compose up reaper-in-memory cassandra
xdg-open 0.0.0.0:8080
# trying to add using ip $(docker inspect packaging_cassandra_1) or 'cassandra' docker "link"
# I also tried scenario when I remove JMX auth from env files (from cassandra and reaper)
```

@adejanovski I have no auth on jmx, I can connect to it with jmxterm (jmx cli) and do things.

**Comment by nsteinmetz** [comment]
hmm by default you may have local jmx only and not remote ones - did you enable remote jmx ?

**Comment by adejanovski** [comment]
Since you're using C* 1.2, you probably needed the thrift port (9160) to be opened as well.
Closing this ticket.
