### ISSUE TITLE
Environment variable to blacklist tables when using auto scheduling

### ISSUE THREAD

**Issue by SaaldjorMike** [thelastpickle/cassandra-reaper#576]
I have a few keyspaces that contains specific tables that I’d like to disable repairs for, but auto schedule repair of everything else.

For the Docker container of Cassandra Reaper, it is currently possible to exclude whole keyspaces, but seems like there are no environment variable to use, for only blacklisting specific tables.

**Comment by adejanovski** [comment]
Is it a duplicate of #577 ?

I would rather fully exclude the keyspaces that contain the tables to blacklist from the autoscheduler and schedule them manually (with the proper blacklist).

**Comment by SaaldjorMike** [comment]
The goal for me is to disable repairs for TWCS tables, and instead of manually creating repair schedules with blacklists for our TWCS tables, this environment variable would allow me to explicitly name our TWCS tables. I'm pretty sure I'd prefer to simply skip all TWCS tables altogether though, so #577 would definitely be much cleaner IMO. Let's close this one and stick to #577
