### ISSUE TITLE
Disabling repair of tables with TWCS

### ISSUE THREAD

**Issue by SaaldjorMike** [thelastpickle/cassandra-reaper#577]
We have a bunch of tables containing time series data with TTL’ed data using TWCS. Initially our plan was to simply enable the auto scheduling feature for all our keyspaces, but quickly noticed a huge difference in repair durations. After digging into why, we noticed that it was running a lot of compactions on TWCS tables containing our TTL’ed time series data. After digging a bit more, I found a post proposing to disable repair of such tables entirely and only run repairs when machines have been down longer than the configured hint window.

http://thelastpickle.com/blog/2016/12/08/TWCS-part1.html#comment-3558631910

Ideally I’d prefer to stick to auto scheduling as much as possible, but I’d rather not exclude entire keyspaces as not all tables in a given keyspace are using TWCS with TTL’ed data.

What is the recommended approach to handle this case? I was hoping was a flag that I could use to get this behaviour using the image from https://hub.docker.com/r/thelastpickle/cassandra-reaper/

**Comment by adejanovski** [comment]
Hi @SaaldjorMike,

such a flag would make sense indeed. I guess the best way to handle this would be to blacklist TWCS tables when auto-creating the schedules : https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/service/ClusterRepairScheduler.java#L109-L129

This would require to cycle through the tables of the keyspace and grab the compaction strategy through JMX, then blacklist it if the table uses TWCS or DTCS.
The feature should be toggled through a parameter under the autoscheduling section in the yaml.

Would you be willing to contribute such a feature?

**Comment by SaaldjorMike** [comment]
Hi @adejanovski,

Willing yes, just not exactly sure when I'll be able to do this. The amount of tables I have with TWCS is small enough that I was ok (at least for now) with manually adding repair schedules for the keyspaces and simply blacklisting them using the UI.

Should anyone pick it up before I do, please do tell. At least I know the proposal to introduce such a flag would make sense to others as well and not only to me.
