### ISSUE TITLE
installing Cassandra-reaper has altered hampered datadog-monitoring

### ISSUE THREAD

**Issue by yugalarora** [thelastpickle/cassandra-reaper#578]
used versions:
cassandra-reaper : 1.3.0
cassandra : 3.11.2

I've a multi node cluster with multiple seed nodes, I installed reaper on one of a seed node.
Changed JMX mode to remote for all nodes, restarted Cassandra
reaper was able to connect all nodes, but Datadog was unable to monitor any stats (because I forgot to configure imx auth in Datadog-agent)
I changed JMX mode back to local, reaper could not connect with my nodes now.
Datadog is able to connect to all nodes and is reporting stats.
Now, the problem is
Datadog is unable to fetch 2 statistics (Cassandra.read_latency.75th_percentile and Cassandra.load_count)
When I start reaper ( Datadog-agent is able to fetch Cassandra.read_latency.75th_percentile from seed nodes only)
When I stop reaper (Datadog-agent is unable to fetch Cassandra.read_latency.75th_percentile from any node)
When I uninstalled reaper (Datadog-agent was again unable to fetch Cassandra.read_latency.75th_percentile from any node)
ever since I installed reaper ( Cassandra.read_latency.75th_percentile is not being fetched by Datadog-agent from non-seed peers, Cassandra.load_count is not being fetched from any node)

Note: I've not altered/changed/installed/uninstalled anything other then reaper on this cluster.

I believe since reaper fetches some metric on it's own, it has:
a) either altered some default metric name
b) updated some metric-*.*.*.jar in classpath, that's why Datadog-agent is not able to fetch this particular metric now.
c) I've only observed this problem for these 2 stats as of now, other 7 stats I was monitoring continue to work.

**Comment by arodrime** [comment]
Just seeing this now, and by chance, quite randomly @yugalarora. Is it still a problem nowadays or should we close it?

From what you described I'm wondering how Reaper could produce this. Maybe is it related to an increased number of metrics being pulled by the datadog agent, that historically had a limit (maybe 350 then 700 metrics, I don't remember well).

**increase the max_returned_metrics**

If that's still a problem, you could try increasing the `max_returned_metrics` in conf.yaml if some charts are not showing up (a service datadog-agent status would also let you know if there is an issue with metrics collection):

`max_returned_metrics: 2500`

The value above depends mostly on the number of tables in use (in Cassandra part). I've been counting 'per table metrics' and made some calculation, considering you have 25 tables for example:

Here are the 'per table metrics' with default (OOTB) Cassandra dashboards only: (2*4+6*3+3*2+3+10+8+3*2)*25 = 1475

So trying to limit to a bigger number of metrics to be collected as a maximum (Default is 350 metrics...). I think 2500 metrics collected in total should do in the case you have 25 tables. If not change the calculation above and add maybe 500 to 1000 for non-table related metrics. That's where this 2500 metrics max suggestion comes from.

The only tradeoff I heard about when increasing metrics collected is the CPU burden. Control CPUs while doing. Even though latest agent versions are really performant. It's also possible to go incrementally as well until the 'service datadog-agent status' no longer shows the warning about metrics being truncated as it is probably now, this is the output we care about and want to fix:

```
# service datadog-agent status
cassandra
  instance_name : cassandra-localhost-7199
  message : Number of returned metrics is too high for instance: cassandra-localhost-7199. Please read <http://docs.datadoghq.com/integrations/java/> or get in touch with Datadog Support for more details. Truncating to 350 metrics.
  metric_count : 350
  service_check_count : 0
  status : WARNING
```

Sorry we missed that one, and I hope you've been through it on your own.

@adejanovski I think this isn't on reaper, but on datadog side. I would probably close this one (that is around without activity for a while anyway).
