### ISSUE TITLE
cannot start the cassandra-reaper service with (storageType: cassandra)

### ISSUE THREAD

**Issue by hitek6** [thelastpickle/cassandra-reaper#583]
Hi Sirs,

i'm having some issues starting cassandra-reaper service in (storageType: cassandra) mode. Can someone please help?

Please see attachment for the current (YAML) configuration and Log file:

[cassandra-reaper.txt](https://github.com/thelastpickle/cassandra-reaper/files/2539038/cassandra-reaper.txt)
[reaper.log](https://github.com/thelastpickle/cassandra-reaper/files/2539039/reaper.log)

**Comment by hitek6** [comment]
[reaper.log](https://github.com/thelastpickle/cassandra-reaper/files/2539022/reaper.log)

[cassandra-reaper.txt](https://github.com/thelastpickle/cassandra-reaper/files/2539024/cassandra-reaper.txt)

**Comment by adejanovski** [comment]
It looks like your /tmp folder has some restricted access rights that don't allow the datastax driver to work properly.

Could you check this and make it writable/readable by the user running reaper?

**Comment by adejanovski** [comment]
According to [this page](https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/MsY7opPBlSo), your OS doesn't support FFI and you may have to start Reaper with the following flag : `-Dcom.datastax.driver.USE_NATIVE_CLOCK=false`

**Comment by adejanovski** [comment]
Closing this issue. Feel free to reopen if needed.
