### ISSUE TITLE
dc_suffix is ignored with Ec2Snitch

### ISSUE THREAD

**Issue by jmetzmeier** [thelastpickle/cassandra-reaper#587]
We have two seperate datacenters using Ec2Snitch. These datacenters are in the same Ec2 region. They get assigned to different DCs based on `dc_suffix` in the `cassandra-rackdc.properties`. The `nodetool status` command correctly reports these as separate DCs, but reaper incorrectly groups instances from both datacenters into the same DC, ignoring the suffix. Our Cassandra cluster is running 2.1.15.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-377) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-377

**Comment by adejanovski** [comment]
Fixed by #1129
