### ISSUE TITLE
Feature request: snapshot only on DC

### ISSUE THREAD

**Issue by maciej-lasyk** [thelastpickle/cassandra-reaper#589]
Currently, Reaper is able to schedule a snapshot over the whole cluster in all DCs on all nodes.

However, having 2 DCs (replication = {'class': 'NetworkTopologyStrategy', 'eu-central': '5', 'us-east': '5'}) where eu-central is used mainly as a hot-spare and where all backups take place it would be great to have the ability for snapshotting only on this very DC eu-central (why bother the production one us-east, that handles application traffic?).

Cheers,

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-378) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-378

**Comment by adejanovski** [comment]
We probably won't invest a lot more in snapshot management, since backup tools such as Medusa are actively developed to handle this.
