### ISSUE TITLE
Invalid column name token_ranges because it conflicts with an existing column

### ISSUE THREAD

**Issue by deimosfr** [thelastpickle/cassandra-reaper#597]
Hi,

I'm running Cassandra 3.11.3 and on the first boot, I'm getting this error:
```
Error during migration of script 014_segment_coalescing.cql while executing 'ALTER TABLE repair_run ADD token_ranges text;'
```

I manually repair it and it's ok:
```
ALTER TABLE repair_run DROP token_ranges;
```

May be we should remove this ADD query inside 014_segment_coalescing.cql ?

What's your point of view ?

Thanks

**Comment by michaelsembwever** [comment]
The column is needed.
Is there any other error message that might explain as to why `ALTER TABLE repair_run ADD token_ranges text;` failed to execute?
( as we're not seeing this is the integration tests against 3.11.3 :-/ )

**Comment by michaelsembwever** [comment]
I saw this in a deployment where a kubernetes pod was frequently crashing. It was crashing during the migration steps. I'm guessing this left the schema in a bad way and it failed to resume on next pod execution.

**Comment by michaelsembwever** [comment]
To best of our knowledge this occurs from the migration steps being run in, or near, parallel. (For example a k8 pod that restarts on failed attempts too quickly can cause the problem.)

The workaround is to wipe the keyspace, and start from scratch, making sure only one instance of Reaper is allowed to run until the schema is correctly installed (and agreed upon amongst all C* nodes).
