### ISSUE TITLE
Network spikes on coordinator (seed node) for repair

### ISSUE THREAD

**Issue by nbozic-zz** [thelastpickle/cassandra-reaper#60]
During repair run we noticed big network spikes on one node in cluster. This was due to communication between monitoring machine and this single node, to get notifications about ongoing repairs. 

This node is added as seed to Reaper through UI. There should be possibility to add multiple seeds when defining cluster so network load for communication can be spread across multiple nodes.

![networkspikes](https://cloud.githubusercontent.com/assets/7149847/23813026/38886428-05dd-11e7-9ddb-fb7734f5fc3d.png)

**Comment by adejanovski** [comment]
@nbozic : I've created PR #63 that allows to automatically create the clusters with all nodes as seed, and JMX connections are shuffled by default.

We still have to determine if all that traffic is necessary or if we're making extra calls that we could remove.

**Comment by adejanovski** [comment]
Fixed by 0.6.0 Cassandra backend improvements.

The footprint of Reaper on the backend is now very low.
