### ISSUE TITLE
Using the WebUI with HTTPS

### ISSUE THREAD

**Issue by a-boynton** [thelastpickle/cassandra-reaper#600]
Hi,

I have been trying to workout how to setup the Web UI for Reaper with HTTPS. I'm sure it is just a config option but I can't seem to find the right combination. What are the other options for the cassandra-reaper.yaml server settings below:

server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 0.0.0.0
  requestLog:
    appenders: []

Thanks

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-380) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-380

**Comment by nsteinmetz** [comment]
Hi @AndrewB2018,

In my case, I set up nginx as reverse proxy + ssl termination on top of reaper (which then listen only on localhost interface)

```
server {
    listen 172.16.0.28:80;
    server_name _;
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 172.16.0.28:443 ssl http2;
    server_name _;
    charset utf-8;

    ssl_certificate /srv/ssl/certs/wildcard.bigcorp.com/fullchain.pem;
    ssl_certificate_key /srv/ssl/certs/wildcard.bigcorp.com/privkey.pem;

    root /srv/www/;
    index index.html;

    location = / {
        return 301 https://$host/webui/;
    }

    location /webui/ {
        proxy_pass http://127.0.0.1:8080/webui/;
    }
    location /cluster {
        proxy_pass http://127.0.0.1:8080/cluster;
    }
    location /ping {
        proxy_pass http://127.0.0.1:8080/ping;
    }
    location /repair_run {
        proxy_pass http://127.0.0.1:8080/repair_run;
    }
    location /repair_schedule {
        proxy_pass http://127.0.0.1:8080/repair_schedule;
    }
   location /snapshot {
        proxy_pass http://127.0.0.1:8080/snapshot;
    }
   location /login {
        proxy_pass http://127.0.0.1:8080/login;
    }
   location /logout {
        proxy_pass http://127.0.0.1:8080/logout;
    }
```

**Comment by adejanovski** [comment]
This page shows how to setup https in Dropwizard: https://www.dropwizard.io/en/latest/manual/configuration.html#https
