### ISSUE TITLE
Multiple networks issue for connection 

### ISSUE THREAD

**Issue by omahonyb** [thelastpickle/cassandra-reaper#611]
Hey folks. I am trying to set up reaper on a few cassandra nods, and it is wrecking my head [I do understand I am probably doing this a**ways, but there is certain requirements in what I am trying to do]. I dont know much about cassandra, as this is from an infrastructure point of view. 
A quick overview:
There is three cass nodes per each of two sites. Each has an admin subnet and a db subnet. Both sites can see each other on each network, but not cross subnet. So admin can see admin from dc1 to dc2 and vice versa. Same for DBNET.
There is a different hostname for both the adm network and the db network. 
JMX is listening on all ports, and i can use jmxterm to connect on the admin network and get cass beans.
However when I try to add the cluster on the adm network, the reaper.log is showing "No route to host" for the ips for the DB network.

I am assuming what I am trying is not possible and is obviously non-standard method, but though I would just ask before I knocked the idea on the head altogether.

Thanks!
B

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-381) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-381

**Comment by michaelsembwever** [comment]
Did you get anywhere with this @omahonyb ?

If you can make jmx connections from the reaper host to the cassandra nodes using jmxterm, then it should be possible with Reaper too.

**Comment by omahonyb** [comment]
We were running 4 Cassandra instances per node on ports 7196-7199, so in the end I ended up using firewalld, removing all the defaults by setting the network to trusted. I then added direct rules as DNATs for the IPs I needed.
[I had issues trying to use just iptables with DNATs on rhel7, so went and actually used firewalld, even if i felt a little bit dirty doing so]

The issue wasnt the connections. The issue was the two interfaces were listening. Reapewr would connect on the interface it could contact [ADMIN], but the nodes were talking back on the DB network the reaper node didnt have access to.

**Comment by FrancoisLe-Labs** [comment]
I had the same issue. 
Even when I set enableDynamicSeedList to false on cassandra-reaper.yaml, then my cluster can be added in the GUI by putting the admin subnet address of cassandra server, but repairs fail because reaper still want to establish JMX connection on address of db subnet (get from node discovery ?).

**Comment by adejanovski** [comment]
This issue was answered in #1100, with the use of `jmxAddressTranslator`.
