### ISSUE TITLE
[Question] How can I export reaper metrics to prometheus?

### ISSUE THREAD

**Issue by sandpwr** [thelastpickle/cassandra-reaper#614]
Can you please explain a procedure to export reaper specific metrics to prometheus?

I see below comments in cassandra-reaper.yaml 
Reaper also provides prometheus metrics on the admin port at /prometheusMetrics

But I can't see any documentation about it. Will it be possible to export reaper metrics directly to prometheus?

Thanks

**Comment by winterheart** [comment]
Hello.
If you configured reaper by default, you have http://localhost:8081/prometheusMetrics on admin interface (ie port 8081). These metrics should be ready to import to Prometheus.

**Comment by sandpwr** [comment]
That helps. Thanks for the reply. 

When ever reaper triggers a job based on schedule it create a new metric for it. This seems to be not very useful and metrics names are getting created with some random numbers. Is this something expected? or we have any work around to over come this?

By the way am using reaper backend as PostgreSQL.

**Comment by michaelsembwever** [comment]
@sandeepnethi the random numbers of the UUID of the repair run id. we're looking for input from users how to improve the metrics. if you have ideas on the metrics dashboards you'd like to create please share :-)

**Comment by Leutin** [comment]
@michaelsembwever you can put this repair run id into metric labels, not into metric names. For example,
`io_cassandrareaper_service_RepairRunner_segmentsDone_prodcluster_2d7a2c80b29a11e98f9fa1d8db1f43af{instance="srv-reaper01:8081",job="reaper"}`
will become
`io_cassandrareaper_service_RepairRunner_segmentsDone{cluster="prodcluster",repair_run_id="2d7a2c80b29a11e98f9fa1d8db1f43af",instance="srv-reaper01:8081",job="reaper"}`, so one could set up dashboard pointing to io_cassandrareaper_service_RepairRunner_segmentsDone metric with fixed name.

**Comment by gpaggi** [comment]
@sandeepnethi, to add on @Leutin config, if you are not interested in the rest of the Dropwizard metrics reported by Reaper, you can drop them by adding:
```
metric_relabel_configs:
  - source_labels: [__name__]
     regex: "io_cassandrareaper_service_RepairRunner_segments(Done|Total)_(.*)_(.*)_(.*)"
     action: keep
```

@michaelsembwever it would be nice to have metrics for start times / end times to make it easier to monitor run times.

**Comment by rzvoncek** [comment]
Hi all, I've put out a PR that adds some docs on how to do the relabelling. It's just the setup, and it doesn't tackle the _monitoring run times_ issues. 

However, Reaper already has `repairProgress` and `millisSinceLastRepair` that are somewhat useful for monitoring repair progress. They are not the same as start and end times though. If we want to add those, I guess they deserve a separate issue.
