### ISSUE TITLE
Version 1.4.0 breaks TLS / HTTPS web server if X-Forwarded-Proto is missing

### ISSUE THREAD

**Issue by mattheworiordan** [thelastpickle/cassandra-reaper#615]
With 1.3.0 we have a router providing TLS termination and authentication in front of the Reaper. This has worked fine as requests are served without redirects.  For example:

```
curl -i https://eu-west-1-reaper.foo.bar/webui --user reaper:[REDACTED]
HTTP/1.1 200 OK
Content-Type: text/html;charset=utf-8
Date: Wed, 13 Feb 2019 11:47:36 GMT
Etag: "c4be3b76c051a5396df03d972dc080fc--gzip"
Last-Modified: Tue, 09 Oct 2018 09:01:00 GMT
Vary: Accept-Encoding
Content-Length: 1932

<!DOCTYPE html>
<!-- Copyright 2016-2018 The Last Pickle Ltd
```

Now with 1.4.0, the reaper web server redirects the request but does not use HTTPS in the URL, thus breaking access to the server over HTTPS.

```
$ curl -i https://eu-west-1-reaper.foo.bar/webui --user reaper:[REDACTED]
HTTP/1.1 302 Found
Content-Length: 0
Date: Wed, 13 Feb 2019 11:52:32 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: http://eu-west-1-reaper.foo.bar/webui/login.html;jsessionid=[REDACTED].node0
Set-Cookie: JSESSIONID=[REDACTED].node0;Path=/
```

Looking at the raw request that arrives at the web server, I can see that the server is in fact not "told" that the request is HTTPS:

```
GET /webui HTTP/1.1
Host: eu-west-1-reaper.foo.bar
User-Agent: curl/7.54.0
Accept: */*
Authorization: Basic [REDACTED]
X-Forwarded-For: 82.35.1.1
X-Forwarded-To: 172.17.0.2:8080
X-Request-Id: c2f308d4-0a09-4603-8ff8-496db617b83c
X-Request-Start: 1550058752794
Accept-Encoding: gzip
```

Until we can get this issue resolved in our routers, do you know if there is any workaround in the reaper to force the Reaper to assume all requests are over HTTPS?

**Comment by mattheworiordan** [comment]
Closing this issue as the reality this is not a reaper problem.  Sorry for the noise.

**Comment by adejanovski** [comment]
thanks for the update @mattheworiordan
