### ISSUE TITLE
Deploy to Maven Central

### ISSUE THREAD

**Issue by jvanzyl** [thelastpickle/cassandra-reaper#62]
Hi, we'd like to use your project internally and it's much easier if we can retrieve your build artifacts from Maven Central. Happy to help with a pull request and help get you setup in Maven Central if you need a hand with this.

**Comment by zznate** [comment]
Hi @jvanzyl  - yes we have definitely discussed this. That said, since it's **you** of all folks making the offer, we'd be psyched to take such a pull request.

**Comment by adejanovski** [comment]
Deployments to Maven Central are now done for every release.
