### ISSUE TITLE
Reaper seems hang state in last segment

### ISSUE THREAD

**Issue by razsandy** [thelastpickle/cassandra-reaper#623]
**Spotted on 1.1.0-SNAPSHOT (b170de8)**
Hi Team,

We are facing an issue in our repair when we are doing through reaper. We are repairing two keyspaces  for two different cluster. One have 11776 segment counted and another have 22272 segment counted. The 11776 segment is doing well and completed in 3 days. But for the 22272 segment the repair is completed in 5 days earlier now a days it runs till 22271 and stuck. We left for 15 days but it have not completed and we stopped it many times. In the log it show following many times repeating. We have done manual scrub in all the nodes but still it stuck in 22271 segment. Please help here.

`[cluster_graph:xxx] i.c.s.RepairRunner - Running segment for range (-6216733632189656343,-3102478998626203200]
[cluster_graph:xxx] i.c.s.RepairRunner - Running segment for range (-3102478998626203200,1463746518107093]
[cluster_graph:xxx] i.c.s.RepairRunner - Running segment for range (1463746518107093,3104588015225018226]
[cluster_graph:xxx] i.c.s.RepairRunner - Running segment for range (3104588015225018226,6102373346883618706]
[cluster_graph:xxx] i.c.s.RepairRunner - Running segment for range (-9223027102887996609,-6216733632189656343]
`
Thanks
Rajib

**Comment by michaelsembwever** [comment]
@razsandy could you try upgrading to the latest released Reaper and seeing if the problem persists? we're fixed a number of efficiency issues that could address this since 1.1.0

**Comment by adejanovski** [comment]
Closing this issue, feel free to reopen if needed.
