### ISSUE TITLE
Wrong timezone in logs

### ISSUE THREAD

**Issue by bgfor** [thelastpickle/cassandra-reaper#638]
Hi,

when I added
%d{yyyy-MM-dd HH:mm:ss,SSS}
into logFormat in cassandra-reaper.yaml
I noteiced that time is given in UTC instead of LocalTime.

How can I change this?

> ~# timedatectl
>       Local time: Tue 2019-04-02 08:34:22 CEST
>   Universal time: Tue 2019-04-02 06:34:22 UTC
>         RTC time: Tue 2019-04-02 06:34:22
>        Time zone: Europe/Warsaw (CEST, +0200)
>  Network time on: yes
> NTP synchronized: yes
>  RTC in local TZ: no

**Comment by michaelsembwever** [comment]
This is more a question for dropwizard configuration https://www.dropwizard.io/1.3.9/docs/manual/configuration.html

**Comment by bgfor** [comment]
Thank you very much for help.

Based on https://logback.qos.ch/manual/layouts.html#conversionWord
i change this line into
%d{yyyy-MM-dd HH:mm:ss.SSS, Europe/Warsaw}
and it started working.
