### ISSUE TITLE
Enable TLS

### ISSUE THREAD

**Issue by sinohC** [thelastpickle/cassandra-reaper#644]
Hi all,

I have enabled TLS for the native protocol port . Because of that I need Reaper to communicate correctly with C* on that port.

I have been searching in the doc, and only found the next ENV to be configured in the Reaper docker :
REAPER_CASS_NATIVE_PROTOCOL_SSL_ENCRYPTION_ENABLED

But i cannot see anywhere how to configure the cert files in Reaper.

Do you know whats the correct way to configure Reaper with TLS?

Regards.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-387) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-387

**Comment by jsanda** [comment]
@sinohC, in addition to configuring the Java driver to use TLS, I think we would also to be able to configure JMX to use TLS as well. It might be worth tackling these in separate tickets/PRs though. In fact, it probably makes sense to have a ticket for postgres if Reaper does not already support TLS connections for it.

**Comment by dave-pollock** [comment]
This commit added support for configuring SSL connections to Cassandra however it doesn't seem to have been released as part of 2.0.5.

https://github.com/thelastpickle/cassandra-reaper/commit/8a28b2d618e5df4c149dff66ab7108bbbb63d28d

**Comment by adejanovski** [comment]
Both Cassandra and JMX can be configured to be accessed using SSL/TLS.
Check the SSL settings section [here](http://cassandra-reaper.io/docs/backends/astra/).
