### ISSUE TITLE
Dockerization 

### ISSUE THREAD

**Issue by aahutsal** [thelastpickle/cassandra-reaper#645]
Since it's pretty tiresome to run development/test environment every time on every computer I'd suggest to create Docker image that runs that environment internally. That image being run with `--network host` will make it feeling like it's run on localhost. Seems michaelsembwever confirmed.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-388) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-388

**Comment by michaelsembwever** [comment]
Thanks @gutsal-arsen 
for reference sake, there's no need to create an issue in front of a pull request in this project. just go ahead and create the PR.

**Comment by adejanovski** [comment]
Closing this issue as well as the related PR.
Thanks for the work done there @aahutsal and let us know if you still want to get that done in some form.

**Comment by aahutsal** [comment]
@adejanovski if you have some new requests - I'll be glad to review them.
