### ISSUE TITLE
Provide a way to disable login/auth via an environment variable (docker)

### ISSUE THREAD

**Issue by eriksw** [thelastpickle/cassandra-reaper#649]
There should be a way to set up dockerized Reaper for running behind an identity-aware proxy like Pomerium. The minimum would be an an environment variable that can be set to disable reaper's auth/auth functionality.

A wonderful stretch bonus would be a way for Reaper to trust and utilize Pomerium's [auth headers](https://www.pomerium.io/docs/signed-headers.html) (again, solely via environment variables supplied to the docker image), but being able to turn off Reaper's auth and rely on cloud security group firewalling would be enough for my use case.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-390) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-390

**Comment by michaelsembwever** [comment]
Sounds like this would be using the `$REAPER_SHIRO_INI` variable to point to a custom `shiro.ini` configuration that recognised and passed through the Pomerium auth headers.

**Comment by eriksw** [comment]
I assume this `REAPER_SHIRO_INI` envvar would be something like the base64'd contents of shiro.ini, written out by an entrypoint script in the container?

**Comment by michaelsembwever** [comment]
It a file path to where the custom shiro.ini file is.

https://github.com/thelastpickle/cassandra-reaper/blob/1.4.1/src/server/src/main/docker/Dockerfile#L70
 -->
  https://github.com/thelastpickle/cassandra-reaper/blob/1.4.1/src/server/src/main/docker/configure-webui-authentication.sh#L21

**Comment by eriksw** [comment]
Ah, in that case I guess this issue should be more along the lines of:

The container build should include a shiro.ini that disables auth, which can be selected using `REAPER_SHIRO_INI`.

Having to provide a _file_ to disable auth is highly undesirable when deploying in ECS, which provides facilities for injecting environment variables as part of a task definition but _not_ arbitrary files. An option to inject shiro.ini contents as base64 would also be sufficient. With neither, the container image as provided is useless and forces otherwise-unnecessary forking of the container build to remove auth.

**Comment by michaelsembwever** [comment]
> The container build should include a shiro.ini that disables auth, which can be selected using REAPER_SHIRO_INI.

Sounds reasonable.

**Comment by mimarpe** [comment]
And why not something as simple as:
-e "REAPER_AUTH_ENABLED=false"
and skip all the rest and not enforce basic auth?

We already hace other layers of auth and this is redundant for us.

Thanks :)

**Comment by mimarpe** [comment]
As a hack, I found an easy (maybe not so elegant) way to disable login, by changing the shiro.ini: replacing from authc to anon on the webui urls and removing the jwt tokens from the REST endpoint session creation requirements...
That solved my problem, but maybe a env var or config var still makes sense. Thanks.

**Comment by adejanovski** [comment]
The `REAPER_AUTH_ENABLED` env variable was introduced in the Docker container 2 years ago.
Closing this ticket.
