### ISSUE TITLE
given segment count is ignored

### ISSUE THREAD

**Issue by RolandOtta** [thelastpickle/cassandra-reaper#65]
when starting a repair (also with scheduled repairs) i always have the problem, that creaper starts the repair with 9 segments, no matter how many segments have been configured with the webapp

**Comment by adejanovski** [comment]
Hi @RolandOtta,

this is normal if you set Incremental repair to true, and have 9 nodes in your cluster.
Incremental repair cannot run in subrange mode, and to avoid validation failures it is highly recommended to run it on one node at a time.

If you want to run subrange repair, please set incremental repair to false and Reaper will pick up the number of segments you specified.

**Comment by RolandOtta** [comment]
Hi,

thank you so much for the clarification!

br,
roland
