### ISSUE TITLE
Exception in AppContext init throws NPE

### ISSUE THREAD

**Issue by treuherz** [thelastpickle/cassandra-reaper#654]
When `AppContext` initialises, it has some exception handling if it's unable to determine a host address.
https://github.com/thelastpickle/cassandra-reaper/blob/d7d045f7eaa4e214584c4ec8082265ba45c36d9b/src/server/src/main/java/io/cassandrareaper/AppContext.java#L53-L62
I'm getting a NullPointerException on Line 58, which I think is because, above...
https://github.com/thelastpickle/cassandra-reaper/blob/d7d045f7eaa4e214584c4ec8082265ba45c36d9b/src/server/src/main/java/io/cassandrareaper/AppContext.java#L40-L43
the logger isn't initialised till after this function runs. 

I may have misunderstood what's going on here, but this seems like a simple oversight in the ordering. Happy to submit a PR to fix if you agree on the cause, but not sure how best to set up a test case.

**Comment by adejanovski** [comment]
oh wow, that is silly 😅 

Totally agree on the cause and happy to take that PR. Not sure how to test this either though...
