### ISSUE TITLE
seeing select query even after the reaper jobs are stopped

### ISSUE THREAD

**Issue by dipeshacharya** [thelastpickle/cassandra-reaper#670]
Hello,
we are using reaper to run repairs jobs in  our production Cassandra  cluster. However due to high loads on nodes we have stopped reaper jobs during peak period. But we see below selects running on the reaper db. which is  causing some issue . Please suggest if this is normal or something else is kicking select statement.

SELECT * FROM reaper_db.repair_run WHERE id = 79e8a7a0-7c02-11e9-9a6e-2fd227d99d2e AND segment_state = 2 LIMIT 5000>, time 517 msec - slow timeout 500 msec

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-395) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-395

**Comment by adejanovski** [comment]
Hi @dipeshacharya,

it is expected indeed as there's a cleanup job which will run every 10 to 30 seconds (depending on your config) which will try to kill all running segments for paused repairs.
To do so, it has to find all segments in state RUNNING (2) and then abort them.

I think we could improve the load that Reaper puts on the cluster by using a local segment cache, avoiding the need to hit the database that often.

@michaelsembwever, wdyt?

**Comment by dipeshacharya** [comment]
Hi @adejanovski 

Thankyou for the response. Could you please suggest what will be the optimal value that we can have for segment cache? if this is helpful .  I have 16 node cluster ( 8 on each data center) with 16 TB of Data? Appreciate your help on this?

**Comment by michaelsembwever** [comment]
The select query is already bound to a single partition (ie the `id` is bound).

> But we see below selects running on the reaper db. which is causing some issue.

@dipeshacharya , what problems is this causing? Is there something else than it appearing in the slow query logger?

@adejanovski why would a single-partition query be taking more than 500ms? 5k+ segments sounds a bit crazy for one repair, maybe segment coalescing isn't enabled here?

**Comment by dipeshacharya** [comment]
@michaelsembwever 
no mostly it  appears in query logger but its a constantly runs on the cassandra nodes and is taking 600 to 700 ms and the select query runs every 5 -10 seconds .  Just thinking if these are causing any load in system or any issue, we are encountering some issues in production so trying to rule out.

Can you all please suggest what will be optimal value for segment cache and how do i enable segmant coalescing for production enviroment?

**Comment by michaelsembwever** [comment]
> Can you all please suggest what will be optimal value for segment cache and how do i enable segment coalescing for production environment?

Segment coalescing is supported when repairing clusters running Cassandra 2.2 or greater. See `SegmentGenerator.java`

**Comment by adejanovski** [comment]
Closing ticket due to inactivity.
