### ISSUE TITLE
DC names containing underscores not appearing correctly in WebUI

### ISSUE THREAD

**Issue by kalaolani** [thelastpickle/cassandra-reaper#713]
**Spotted on 1.4.1 (9853df3)**

Instead of showing DC names of cc1_1, cc3_1, and cc3_2, the WebUI is showing DC names of cc1 and cc3, where all of the nodes of both the cc3_1 and cc3_2 DCs are showing in the cc3 DC, while nodetool status shows cc1_1, cc3_1, and cc3_2 with node the expected node membership.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-398) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-398

**Comment by adejanovski** [comment]
Hi @kalaolani, 

Could you post here a screenshot of the problem along with the output of `nodetool gossipinfo` from one of your nodes?
Please obfuscate the ip addresses before posting for security reasons.
Thanks!

**Comment by 0x6373** [comment]
This looks like a duplicate of #647

**Comment by adejanovski** [comment]
Closing as duplicate.
The problem was solved in later versions of Reaper.
