### ISSUE TITLE
Developers VS CORS

### ISSUE THREAD

**Issue by therb1** [thelastpickle/cassandra-reaper#729]
Hello it's me again =)

I try write some code to resolve this problem https://github.com/thelastpickle/cassandra-reaper/issues/721

but I spent all day trying to start a project locally = (

At the end i have problem with cors from reaper server when i try work with webpack-dev-server

`Access to XMLHttpRequest at 'http://servername_1:8080/cluster' from origin 'http://servername_1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

cassandra-reaper server does not do anything with **startup** key

- -DenableCrossOrigin

- -DenableCrossOrigin="true"

cassandra-reaper server does not do anything with **config** key

- enableCrossOrigin: true

What i do wrong?

Why reaper dont send me allowing CORS?

Do you have scripts to run the project locally, for developers?

**Comment by adejanovski** [comment]
Hi Maxim,

when working with the webpack dev server, use the following URL :
http://127.0.0.1:8000/webpack-dev-server
Prior to that, start a reaper server locally with the default
settings/port, and it should work fine.

Cheers,


-----------------
Alexander Dejanovski
France
@alexanderdeja

Consultant
Apache Cassandra Consulting
http://www.thelastpickle.com

**Comment by therb1** [comment]
Hello Alexander.
I run the reaper server, on to the same machine as reaper's web interface.
On different ports.

server:
http://1.1.1.1:8080/webui/index.html
Command:
/opt/jdk/bin/java -jar /usr/share/cassandra-reaper/cassandra-reaper-1.4.4.jar server /etc/cassandra-reaper/cassandra-reaper.yaml

web ui:
http://1.1.1.1:8000/webpack-dev-server/
Command:
cd /cassandra-reaper/src/ui
npm run start

![image](https://user-images.githubusercontent.com/9654476/62199044-7702a980-b38b-11e9-9cb1-8747dc078bcd.png)

But reaper UI didn't see cluster and ping on local.
Or if i change mixin.jsx
from:
```
export const getUrlPrefix = function(location) {
  const isDev = location.includes('webpack-dev-server');
  const contextPath = location.includes('/webui') ? location.substring(0, location.indexOf("/webui")) : '';
  const URL_PREFIX = isDev ? 'http://127.0.0.1:8080' : contextPath;
  return URL_PREFIX;
}
```
to:
```
export const getUrlPrefix = function(location) {
  const isDev = location.includes('webpack-dev-server');
  const contextPath = location.includes('/webui') ? location.substring(0, location.indexOf("/webui")) : '';
  const URL_PREFIX = isDev ? 'http://1.1.1.1:8080' : contextPath;
  return URL_PREFIX;
}
```
I've got problem with CORS

**Comment by adejanovski** [comment]
Why are you accessing the UI on http://1.1.1.1:8000/webpack-dev-server/ instead of http://127.0.0.1:8000/webpack-dev-server/ ?

**Comment by therb1** [comment]
i can't run this project on my local machine because i dont have rights for this.
Because of that i run standalone server with ip 1.1.1.1

**Comment by adejanovski** [comment]
We have a `./start-webpack.sh` script in `src/ui/` which we use to start the webpack server.
It runs `./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --port 8000 --content-base build/ -d` instead of `npm run start`.

Not sure if this could help with your problem.

**Comment by therb1** [comment]
No
He still try access to cluster and ping handlers on localhosts
![image](https://user-images.githubusercontent.com/9654476/62202554-29d60600-b392-11e9-92c0-3790beab5d2b.png)

**Comment by therb1** [comment]
thats how it run on server
![m o](https://user-images.githubusercontent.com/9654476/62203074-28f1a400-b393-11e9-8be7-c65dd1116cb9.png)

**Comment by therb1** [comment]
as work around

1. I change files
2. Then run `mvn clean package -DskipTests`
3. Then run full project
