### ISSUE TITLE
Upgrade shiro

### ISSUE THREAD

**Issue by dashcheulov** [thelastpickle/cassandra-reaper#748]
Hi,

I tried to set LDAP (AD) authentication and faced an inability to set searchFilter in shiro.ini. It's important part of my config and I have to set it to _(sAMAccountName={0})_. But it's hardcoded in version currently used by cassandra-reaper.

Shiro has enabled a support of searchFilter configuration and released it in version 1.4.0:
https://github.com/apache/shiro/commit/28c95ee33531fb9b573836d92e4ebee0a30cb554#diff-7e80cb4738d58d7e2b06e9a2132a851b

Unfortunately, your dependency to dead project dropwizard-shiro 0.2.0 (the latest release was in Mar, 2015) depends on Shiro 1.2.4:
https://github.com/silb/dropwizard-shiro/blob/4e05392a4820443c36522e9d3c5a4989a3953b42/pom.xml#L128

Please, bump up Shiro somehow and thus make possible setting searchFilter in shiro.ini.

**Comment by adejanovski** [comment]
This was done in 3.1 and we're now using Shiro 1.8.0
