### ISSUE TITLE
Build Docker Images

### ISSUE THREAD

**Issue by chrislbs** [thelastpickle/cassandra-reaper#75]
Create a docker image for cassandra-reaper as part of the build process. Somewhat of a precursor #51 .

**Comment by chrislbs** [comment]
@adejanovski Does thelastpickle have a [docker hub](https://hub.docker.com/) account? If you can create one and set the encrypted variables in the travis yml, I should be able to update my existing PR to publish the created docker images.

**Comment by joaquincasares** [comment]
@chrislbs @adejanovski is out of the office for the next couple of weeks, but I may be able to help. We already have a Docker Hub account (https://hub.docker.com/u/thelastpickle). What all is needed? Thanks again!

**Comment by chrislbs** [comment]
@joaquincasares So, I'll need encrypted variables of the user account that has access to push to your docker hub account. I will have to use them to configure the docker plugin to push to the appropriate repository. I'm not sure how the $GITHUB_TOKEN environment variable was created but if you could create DOCKER_HUB_USER and DOCKER_HUB_PASS environment variables in the same way it would be easy for me to consume. If necessary, you can use the travis command line to encrypt them in the .travis.yml file. https://docs.travis-ci.com/user/environment-variables/

**Comment by joaquincasares** [comment]
I'm not sure how this got closed, but I'm closing #51 since #76 does half of what #51 was intending to do.

**Comment by FlorianHockmann** [comment]
Any updates on this? From the documentation it looks like it's now very simple to build the Docker image. So is really only the publish to Docker Hub missing?

**Comment by joaquincasares** [comment]
@FlorianHockmann Sorry, I was OOO for an extended period. That's correct, the Docker build code is now part of the repo and we only need to add the auto-publishing to Docker Hub, if it's not already there.

Do be aware that there was a recent reorganization and I'm not sure what all was affected.
