### ISSUE TITLE
High amount of Reads/sec on WebUI Repair page

### ISSUE THREAD

**Issue by Lyky35** [thelastpickle/cassandra-reaper#754]
Hi,
I have noticed that having multiple tabs of reaper webui (in repair tab) causes high amount of Reads/Sec to reaper_db. The WebUI sessions never timeout, so users keep polling the data all the time - even if they forgot about the tab.

Here are graphs on reaper_db reads/sec (today, and last 30 days)

![image](https://user-images.githubusercontent.com/36609323/65440777-dfe82a00-ddee-11e9-8c0d-1951ebc58ad0.png)
![image](https://user-images.githubusercontent.com/36609323/65441159-8df3d400-ddef-11e9-9b25-a18e47838bac.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-404) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-404

**Comment by adejanovski** [comment]
Hi,

The web UI refreshes a lot indeed and can hammer the Cassandra backend fairly hard if there are running repairs with lots of segment. This is something we definitely want to optimize.

**Comment by adejanovski** [comment]
There have been optimizations in latest versions on the number of calls we make to the backend.
I'll close this ticket but feel free to reopen if necessary.
