### ISSUE TITLE
Don't resolve seed nodes before saving it to the backend

### ISSUE THREAD

**Issue by lewisdiamond** [thelastpickle/cassandra-reaper#756]
Currently, when a seed node is configured, the IP address is resolved and that IP is then persisted to the backend. In cases where IPs are not static (the very reason why you'd use a hostname or dns) cassandra-reaper will fail to contact those nodes if their IP changes. Instead, the unresolved contact point should be saved and resolved at connection time to ensure it always connects to the right node.

An example use is inside a Kubernetes cluster, where pods restarting will get a new IP address.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-406) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-406

**Comment by adejanovski** [comment]
Hi @lewisdiamond,

the thing is we don't actually resolve IP addresses. 
Instead, when a cluster is added with a seed node, we connect to it through JMX and invoke the `StorageServiceMBean.getLiveNodes()` operation which will return the list of nodes currently in the cluster. As Cassandra identifies nodes by host id and IP address (it doesn't store hostnames) we get a list of IP addresses at the time of the request.

We could have a workaround to disable dynamic reload of the seeds in Reaper, and just use the provided address(es). Reaper wouldn't be able to track topology changes, but it would at the very least always contact the nodes using the hostname initially provided when adding the cluster.

How does this sound?

**Comment by lewisdiamond** [comment]
I'm not familiar with how Cassandra-reaper is implemented. Would it work if you simply store the initial seeds and use that as a recovery when no node are online (via their original IP)?

**Comment by adejanovski** [comment]
We now have a way of running Reaper in Kubernetes which is to use a service as seed and disable the enableDynamicSeedList option to prevent it from being updated.
