### ISSUE TITLE
spreaper list-runs arguments not working

### ISSUE THREAD

**Issue by atallahade** [thelastpickle/cassandra-reaper#758]
Running `spreaper list-runs cluster keyspace` outputs the list of all repairs. I'm expecting this to filter the list to only repairs for the specified cluster and keyspace.
This command is using the `/repair_run` endpoint which doesn't provide a way to filter the repairs by cluster/keyspace via query parameters. Maybe the API has changed and spreaper hasn't been updated?

**Comment by adejanovski** [comment]
Hi @atallahade,

you're right and I think I see what's wrong.
`spreaper` [is passing query params](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/packaging/bin/spreaper#L521) as `cluster` and `keyspace` while the [REST endpoint expects](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/resources/RepairRunResource.java#L658-L659) `cluster_name` and `keyspace_name`.

That should be easy enough to fix.

**Comment by rzvoncek** [comment]
When trying to reproduce, I found out this was fixed in 897c0b655559e51fe475cdc042a17c999c2734da.
