### ISSUE TITLE
Allow different JMX passwords for different clusters

### ISSUE THREAD

**Issue by jfharden** [thelastpickle/cassandra-reaper#759]
In cassandra-reaper it is possible to connect to multiple cassandra clusters but only a single JMX password can be specific.

We would like to have different JMX passwords for different cassandra clusters.

**Comment by adejanovski** [comment]
Hi @jfharden,

this is already supported. Please check the `jmxCredentials` section [in the documentation](http://cassandra-reaper.io/docs/configuration/reaper_specific/).

Let me know if that suits your needs.

**Comment by jfharden** [comment]
Ah yeah, sorry. I'm configuring with docker at the moment, but I can easily change to building a config file instead of using the env vars. Thanks.
