### ISSUE TITLE
SegmentRunner declined to repair segment 

### ISSUE THREAD

**Issue by pawe-000** [thelastpickle/cassandra-reaper#760]
Hi,

we have been a repair job running for 3 days and primary 1 segment of 20 are repaired. I f found following in the logs. 
INFO   [2019-09-30 10:07:39,095] [productioncluster:1112:75727] c.s.r.s.SegmentRunner - Postponing segment 75727 
INFO   [2019-09-30 10:08:08,281] [productioncluster:1112] c.s.r.s.RepairRunner - Next segment to run : 75726 
INFO   [2019-09-30 10:08:09,217] [productioncluster:1112:75726] c.s.r.s.SegmentRunner - SegmentRunner declined to repair segment 75726 because only one segment is allowed at once for incremental repairs 
INFO   [2019-09-30 10:08:09,221] [productioncluster:1112:75726] c.s.r.s.SegmentRunner - Postponing segment 75726 
INFO   [2019-09-30 10:08:38,283] [productioncluster:1112] c.s.r.s.RepairRunner - Next segment to run : 75722 
INFO   [2019-09-30 10:08:38,950] [productioncluster:1112:75722] c.s.r.s.SegmentRunner - SegmentRunner declined to repair segment 75722 because only one segment is allowed at once for incremental repairs 

Can anyone support me. Many thanks!

**Comment by pawe-000** [comment]
I found an ERROR in the logs which could be related to that 
ERROR  [2019-09-28 11:00:51,128] [productioncluster:1112:75712] c.s.r.s.RepairRunner - Executing SegmentRunner failed: ReadableInstant objects must not be null

**Comment by adejanovski** [comment]
Hi @um-paho,

incremental repair indeed allows only a single running segment at a time to avoid conflicts in sstables access.
Reaper seems to think (rightfully or not) that a segment is running already for this cluster. Either there's one segment at `RUNNING` state for this repair, or there's a repair that is running on one of the nodes (or reported as such).
Could you check in the UI that no segment is running? (Click on the `View segments` button of the repair screen for this repair).
The error trace shows that one of `startTime` or `endTime` is set to null although it shouldn't be.
We will need more logs to fully analyze the issue: Could you send us your full reaper logs at reaper[at]thelastpickle.com?
Also, which version of Cassandra and Reaper are you running?

Thanks

**Comment by pawe-000** [comment]
Hi,

we have creaper 0.6.0 and cassandra 3.10.  I didn't install this creaper version, but I think it's quite old . 
Unfortunately i cannot find  the "view segement" button.  Could it be that this button is available in a newer version.

**Comment by adejanovski** [comment]
OK, then let's not spend time on debugging this :) 
You need to upgrade to the latest 1.4.6 because 0.6.0 is veeeeeery old and won't get any fix anyway (and is probably full of bugs).

I'll close this ticket for now. Feel free to reopen it if you still have this problem with the latest stable release.

**Comment by Jabbl** [comment]
Hello,

I seem to still have this problem.\
I suspected it was from an earlier instance of reaper that had an erroneous config, so I updated Reaper from 1.3.0 to 1.4.8 as a similar issue was fixed in that update.

The host (10.42.12.8) has been restarted multiple times, just in case some flag could be reset by doing so.

It looks like all the remaining segments have this issue, which means Reaper is stuck in some kind of loop trying to abort them all.

```
INFO [2019-11-19 11:15:02,307] [cassandra:7feccef0-09e8-11ea-ab11-95940b8565cd] i.c.s.RepairRunner - Next segment to run : 7fed4420-09e8-11ea-ab11-95940b8565cd
INFO [2019-11-19 11:15:02,418] [cassandra:7feccef0-09e8-11ea-ab11-95940b8565cd:7fed4420-09e8-11ea-ab11-95940b8565cd] i.c.s.SegmentRunner - SegmentRunner declined to repair segment 7fed4420-09e8-11ea-ab11-95940b8565cd because one of the hosts (10.42.12.8) was already involved in a repair
WARN [2019-11-19 11:15:02,474] [cassandra:7feccef0-09e8-11ea-ab11-95940b8565cd:7fed4420-09e8-11ea-ab11-95940b8565cd] i.c.s.SegmentRunner - A host (10.42.12.8) reported that it is involved in a repair, but there is no record of any ongoing repair involving the host. Sending command to abort all repairs on the host.
INFO [2019-11-19 11:15:02,480] [cassandra:7feccef0-09e8-11ea-ab11-95940b8565cd:7fed4420-09e8-11ea-ab11-95940b8565cd] i.c.s.SegmentRunner - Cannot run segment 7fed4420-09e8-11ea-ab11-95940b8565cd for repair 7feccef0-09e8-11ea-ab11-95940b8565cd at the moment. Will try again later
```

Cassandra version: 3.11.4
Reaper version: 1.4.8
Reaper backend: Cassandra
Number of reaper instances: 1
