### ISSUE TITLE
Connect multiple Cluster by Configuration

### ISSUE THREAD

**Issue by Shawcs** [thelastpickle/cassandra-reaper#768]
I would like to know if there is a way to setup multiple cassandra cluster monitoring with cassa-reaper.yml configuration file.

I need to use reaper with docker and configure it by default to connect 2 diffrents cluster with 2 set of credential. 

Is that possible ? is that planned ?

Regards

**Comment by adejanovski** [comment]
Hi, 

the feature exists already (check the `jmxCredentials` section [here](http://cassandra-reaper.io/docs/configuration/reaper_specific/)), but there's no Docker variable for it.
We would gladly accept a contribution on this :)
You'll need to check `src/server/src/main/docker` and find the appropriate way to add the missing section : https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/docker/cassandra-reaper.yml

**Comment by Shawcs** [comment]
@adejanovski  Well at first I would like to make jmxCredentials work. In the doc it's not verry explicit. I added my cluster name like this :  
```jmxCredentials:  
  uatcluster1:  
    username: user  
    password: uatpass  
  productioncluster1:  
    username: user  
    password: prodpass
```
First thing the doc say 

> The cluster name must match the one defined in the cassandra.yaml file

So if my cluster are named **UAT Cluster 1** do I need to write it like this ? :
```jmxCredentials:   
  UAT Cluster 1:  
    username: user  
    password: uatpass  
```

Second part it's said 

> Adding a new cluster with specific credentials requires to add the seed node in the following format : host@cluster
To match the example above, it could be something like : 10.0.10.5@clusterProduction1

So this is when I add a cluster from the webUI or somewhere else ? in my case would be:

`**seed node:** MY_HOST_NAME@UAT Cluster 1 **JMX Port:** default`

**Comment by kitsirota** [comment]
Im actually looking for the same thing, except we would like to specify both the cluster seed nodes and credentials in the config file.  The goal is to be able to deploy reaper with all the config values baked in so users dont have to perform any manual steps in the UI after reaper is deployed into a particular environment.

I noticed seedNodes is exposed via the API, but I didnt see any references for how I could set these in cassandra-reaper.yaml.  Is there some other way I can set node/creds parameters on a fresh deployment?  I could setup something to hit the rest api to add these after the service is running, but ideally I would love to just inject the configuration for runtime as part of the deployment.

For context, I'm putting together a bosh release (https://bosh.io/docs/release/) for cassandra reaper to accommodate our bosh-based deployment orchestration.  Ive got the initial release in a decent place, but right now when reaper is deployed, someone has to add the cassandra cluster in that VPC manually.  Ideally, reaper would go off the config file so our deployments could all be "infrastructure-as-code" friendly.  The plan is to opensource the bosh release as soon as we have something stable, I will make a separate ticket to get feedback from this community.

Update:
Im just going to use spreaper add-cluster for now in a post-deploy script.

Thank you!

**Comment by rzvoncek** [comment]
Hello @Shawcs , @kitsirota,

I'm now done with working on this. Here's what I've done:
- With https://github.com/thelastpickle/cassandra-reaper/pull/903, the JMX credentials are now configurable via an env variable when running the docker image.
- With https://github.com/thelastpickle/cassandra-reaper/pull/905, it's now possible to use the Reaper's docker image to automatically register a cluster and start a repair.
- I've added docs on how to do this auto registration to http://cassandra-reaper.io/docs/download/docker/.
- I've also added docs on the JMX credentials [here](http://cassandra-reaper.io/docs/configuration/reaper_specific/#jmxcredentials).

I hope this helps you at least initially. If I missed something that's broken, or we need to tweak how all this works, please open new issues and ping me directly.
