### ISSUE TITLE
1.4.7 on Ubuntu 14.04 issues a lengthy `find` command

### ISSUE THREAD

**Issue by rborer** [thelastpickle/cassandra-reaper#770]
Hi,

Ubuntu 14.04, I just upgraded from reaper 1.4.4 to 1.4.7 and now it takes a few minutes to start, obviously due to the system-wide `find` command from there: https://github.com/thelastpickle/cassandra-reaper/blob/b891afb7003df0530de666f37dd045b801a30e21/src/packaging/bin/cassandra-reaper#L17

Coming from #731 .

`cassandra-reaper.log` is full of lines like the following:

```
find: `./home/docker': Permission denied
find: `./home/ansible/.ansible': Permission denied
```

Which obviously means that the find command is issued from `/`.

I couldn't understand from the PR what the purpose of this PR is. As a quick fix I can think of adding `maxdepth 4` to it so it doesn't scan the whole disk (imagine a server connected to a slow NFS disk, it'll take ages to start).

What do you think?

**Comment by adejanovski** [comment]
I think it makes sense to do so. Would you be willing to send a PR for this? It would be much appreciated.
