### ISSUE TITLE
Nodetool cleanup functionality

### ISSUE THREAD

**Issue by sbilello** [thelastpickle/cassandra-reaper#776]
Hi everyone,

Do you think that it would be an easy change to use the reaper to perform a `nodetool cleanup`  in rolling fashion and eventually by node and column family?

If not I would start to read the code and see if I would be able to make the change to let it work.

Thanks,

Sergio

**Comment by adejanovski** [comment]
At some point we tried to implement cleanup, upgradesstables and such, but the JMX endpoints that trigger this operation are non blocking and do not return any id that would help us check on the completion status.
We have no way, currently, to implement this in a rolling fashion.
The sidecar mode might bring some solutions but it still needs a bit of work.

At the moment, your best option to achieve this is [cstar](https://github.com/spotify/cstar). It was designed to run this kind of commands in a rolling/topology fashion on Cassandra clusters.
