### ISSUE TITLE
Can't mix sequential repair and incremental repairs

### ISSUE THREAD

**Issue by sguenfred** [thelastpickle/cassandra-reaper#786]
For our cassandra cluster we want to schedule :
 -non incremental repair every week 
 -incremental repair every days

issue :
after defining the weekly repairs i try to define the daily one and
the webadmin doesn't allow that and throw a "Can't mix sequential repair and incremental repairs"

is it plan to support both type of repairs together?

**Comment by michaelsembwever** [comment]
@sguenfred you are aware of the number of bugs in incremental repairs, and especially when in combination with full repairs, in Cassandra versions before 4.0?
(incremental is not recommended before 4.0, if you can help it, and mixing really isn't recommended. though there are always exceptions, we don't want to provide a tool that encourages and triggers some of those serious bugs.)

**Comment by sguenfred** [comment]
I wasn't specially aware that mixing incremental repairs and full repairs is discouraged in c3 < 4.
at a first sight (as for backup) i though it was a good idea to mix then.
I understand the logic of  "don't want to provide a tool that encourages and triggers some of those serious bugs"
as it appear that this limitation comes from c3 i gonna close this one.
however if some thing about this limitation could be written in the faq it will be great
