### ISSUE TITLE
Repair recommendations for multi-DC with different topologies

### ISSUE THREAD

**Issue by scurvy** [thelastpickle/cassandra-reaper#787]
Looking for advice on the best route to take for a cluster ring like ours. Our main DC has a RF of 3 with 9 nodes. Our disaster recovery DC has a RF 1 of with 3 nodes. We have lots of bandwidth between the datacenters.

Should we run DC-Aware repairs? Should it be parallel instead of sequential? With a RF of 1, I'm afraid that a DC-confined repair in the DR facility would not know what it's missing. Or is that unfounded and Cassandra would magically go to the other DC to get missing keys?

Thanks for this wonderful tool!

**Comment by adejanovski** [comment]
DC-Aware is one of the possible values for repair parallelism. This setting doesn't control which datacenters will be repaired or not, it just controls the parallelism of merkle tree computations (validation compactions).

- Sequential : only one replica at a time, throughout the whole cluster, will compute the merkle trees (using snapshots)
- Parallel : all replicas will compute the Merkle trees at the same time (no snapshot)
- DC Aware : same as sequential, but per DC. One replica in each DC will compute the Merkle trees at once (using snapshots)

Whatever your choice here, all data will be repaired in both DCs, it's not a confinement setting (this is done by specifying only one datacenter in the Advanced Settings of the repair run/schedule creation in the UI).

**Comment by scurvy** [comment]
Thanks for the clarification here. This is what we thought, but it's always good to get a concise answer!
