### ISSUE TITLE
Notification Email - Enhancement

### ISSUE THREAD

**Issue by JIppolito** [thelastpickle/cassandra-reaper#79]
Add a field to enter an email address to notify when a repair starts/stops/fails.  Currently have a crude ruby script which runs via cron and checks to see if a repair is running and to send an email out

**Comment by rustyrazorblade** [comment]
Interesting, but we're looking to make something a little more flexible than email.  Take a look at #11.  I think we're looking to go down an HTTP callback route.  In the spirit of flexible design, we'll probably make the callback part pluggable & provide an HTTP implementation.

**Comment by JIppolito** [comment]
probably should have worded that better as the current script i have is going to plugin to graphite/grafana that we use, not just email. Didnt see the pluggable observers issue/enhancement.

**Comment by adejanovski** [comment]
Let's close this as duplicate of #11
