### ISSUE TITLE
UI - broken nodes list visualization

### ISSUE THREAD

**Issue by enricocavallin** [thelastpickle/cassandra-reaper#795]
Upgrading from 1.3.0 to 1.4.8, logs show no errors, JS console shows no errors, but nodes rendering is broken as per attached screenshot.
Same goes for 1.4.7.
Downgrading to 1.4.5 nodes are showing normally.
Install and downgrade done via yum on stable repo.

![reaper-screen](https://user-images.githubusercontent.com/2354045/69043748-eca28c00-09f3-11ea-82b7-e79a6f179826.JPG)

**Comment by adejanovski** [comment]
Hi, could you be more specific as to what's broken?
We gave up on relative sizing of the nodes in 1.4.6. They are now displayed as squares of the same size, but with different shades of color to show imbalances (the darker, the more load).
Check #753 for more details.

**Comment by enricocavallin** [comment]
My bad, I missed this revamp. I close this issue.
Thanks!
