### ISSUE TITLE
problem starting incremental repair when full repair was executed earlier or vice-versa

### ISSUE THREAD

**Issue by aggarwalabhi23** [thelastpickle/cassandra-reaper#8]
while creating new run, if the passed value of incremental repair flag is different from the existing value  then it should allow to create new repair_unit instead of getting repair_unit based on cluster name/ keyspace /column combination.

so, if the full run was executed for the clustername/keyspace/column was executed earlier, not able to start new incremental run for the same combination. Reverse is also true.

So as per current solution if i delete the repair_unit then due to referential constraints i need to delete repair_segment and repair_run as well which will delete the run history corresponds to the repaid_unit.

**Comment by zznate** [comment]
Given the potential performance impact (run-time and per repair) of flipping to and from incremental, treating this as a completely new `repair_unit` seems reasonable to me.

**Comment by adejanovski** [comment]
@aggarwalabhi23 : I've fixed this in PR #9 
Can you check that the fix works for you before we merge ?

**Comment by adejanovski** [comment]
Fix merged
