### ISSUE TITLE
Create 0.6.0 Release

### ISSUE THREAD

**Issue by chrislbs** [thelastpickle/cassandra-reaper#80]
I'd like to get a 0.6.0 release to take advantage of the dropwizard version upgrade.

**Comment by MALPI** [comment]
See PR #81

**Comment by rustyrazorblade** [comment]
I believe the next release will be considered a 1.0.  Need to discuss w/ @adejanovski when he's back from vacation.

**Comment by adejanovski** [comment]
@chrislbs, since we're not quite ready yet for 1.0, I'll soon create a 0.6.0 release as you requested.

**Comment by MALPI** [comment]
@adejanovski this can be closed or not?

**Comment by adejanovski** [comment]
@chrislbs : 0.6.0 was released on Friday.
