### ISSUE TITLE
Cannot update cluster seed hosts list when previous IPs are unavailable

### ISSUE THREAD

**Issue by atallahade** [thelastpickle/cassandra-reaper#813]
I manage some Cassandra clusters that are on Kubernetes and nodes often come and go.
New nodes will have different IP addresses.
In some cases, the whole cluster can be recycled with new nodes, which means the seed hosts list for this cluster becomes outdated.
I have a job that periodically updates the seed hosts ([`PUT /cluster/$cluster_name?seedHost=$ip`](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/resources/ClusterResource.java#L155-L168)) for all our clusters but in the previous case it won't work since [Reaper tries to get the list of all previous nodes (using the outdated seed hosts)](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/server/src/main/java/io/cassandrareaper/resources/ClusterResource.java#L284) and fails (throws a "no host could be reached through JMX" error)

**Comment by adejanovski** [comment]
@atallahade, I've opened #815 to fix this behavior. Feel free to test and give us some feedback.
Thanks!

**Comment by jsanda** [comment]
Hi @atallahade 

Are you deploying Cassandra as a StatefulSet? If so, how come you cannot use the network ids provided by the StatefulSet controller? e.g., `cassandra-0.default.svc.local`, `cassandra-1.default.svc.local`?

**Comment by atallahade** [comment]
@jsanda We use a discovery system ([smartstack](https://github.com/airbnb/synapse)) on all our services regardless of their deployment method (on k8s, EC2...) so we have to update the seed host list whenever our discovery files change, with the new list of IP addresses. I do not intend to go around that.

**Comment by adejanovski** [comment]
@atallahade, do Cassandra nodes change IP but keep their hostnames?

@jsanda suggested offline that we could add a flag in the Docker container to store hostnames instead of IPs in the seed host list so that fully changing IPs stops being a problem for Reaper.

Do you think that would work in your case?

**Comment by atallahade** [comment]
@adejanovski In my case, hostnames of the Cassandra nodes (that can be used by reaper) are based on the IP address.
To make the issue less likely to happen, I've changed the periodicity of the job to update the seed host list every 5min (with the IP addresses found in the discovery files).

**Comment by jsanda** [comment]
Hi @atallahade 

Are you using a k8s service with your Cassandra cluster?

**Comment by atallahade** [comment]
@jsanda no we don't. We tried to make the transition from EC2 instances to kubernetes as smooth as possible so we just reuse our own discovery system where IP addresses are exposed on json files.

**Comment by puneetloya** [comment]
@adejanovski I have been using reaper with cassandra and as suggested above its a pain when it cannot handle dynamic ips, the solution of tracking everything by HostID(uuid from cassandra) would work for most cases. Other than when you are dealing with replacing a cassandra pod along with its storage, but I think thats a bigger problem than dealing with deleting history of old repairs. Let me know what you guys think?

**Comment by puneetloya** [comment]
> @jsanda suggested offline that we could add a flag in the Docker container to store hostnames instead of IPs in the seed host list so that fully changing IPs stops being a problem for Reaper.

What flag are you guys talking about? It sounds really helpful

**Comment by jsanda** [comment]
Hey @puneetloya 

I previously explained to @adejanovski that in a k8s deployment, you really do not want to store IPs. Instead it would be better to store the name of the Cassandra headless service since it tracks the Cassandra pod IP and since we can get all of the IPs from the service.

It has been a while since we discussed it. I do not recall specifically what code was involved. If you are interested I would be happy to look into it again. I have doing some work with running Reaper in k8s so the changes would be useful to me as well :)

**Comment by puneetloya** [comment]
@jsanda sounds great. As headless services do provide a hostname(dns record within the k8s cluster) to each cassandra pod, so having a docker flag to either use hostnames/IPs would be really helpful for running reaper in k8s.

**Comment by puneetloya** [comment]
@jsanda any luck with this?

**Comment by jsanda** [comment]
Hi @puneetloya 

I have not had a chance to work on this yet but plan to this week.

**Comment by jsanda** [comment]
Hi @puneetloya,

A couple questions:

* What are you currently specifying for the seeds?
* Are you already using a headless service with Cassandra?
    * If yes, have you tried specifying the headless service as a seed?

**Comment by puneetloya** [comment]
I currently have cassandra with two datacenters and each with 5 nodes. Each datacenter has a headless service.

To answer  your question, yes, I do supply my headless service of one the datacenters currently and it discovers all the nodes of both datacenters with their IPs. 

I do see that reaper uses getLiveNodes  in jmxproxy and add their IPs as a list. I tried to do a dirty hack in reaper of replacing those ips by doing a reverse lookup using java.net getHostName() but clearly that nots it ;) 
 I verified that when you use java net HostName() function it returns the whole FQDN of a statefulset. Eg:
Statefulset Name: cassandra 
Namespace: qa
headless service: cassandra
With pod-0 java returns hostname as: cassandra-0.cassandra.svc.cluster.local
pod-1: cassandra-0.cassandra.svc.cluster.local
and so on.

Sorry for the extra information.

**Comment by jsanda** [comment]
@puneetloya 

Have you tried setting `enableDynamicSeedList: false` in your Reaper config? Disabling it will cause the headless service to get stored instead of the pod IPs when adding a cluster.

**Comment by puneetloya** [comment]
@jsanda will try as you suggested. I did try that option but seeing the UI still showed up IPs of the cassandra nodes and not hostnames, may be I wrongly concluded that it wont work. Will try again today and let you know. BTW any easy way to show up hostnames/pod-names instead of IPs on the UI?

**Comment by jsanda** [comment]
Setting `enableDynamicSeedList: false` is necessary but not sufficient. There are some additional changes needed that I am working on/testing.

**Comment by jsanda** [comment]
>BTW any easy way to show up hostnames/pod-names instead of IPs on the UI?

I don't think that this is something that can (or should be) done through Reaper. AFAIK Reaper is just reporting the names/addresses returned from Cassandra via JMX.

Right now I am testing with a three node cluster whose pod/hostnames are:

* cluster-1-dc1-rack1-0
* cluster-1-dc1-rack1-1
* cluster-1-dc1-rack1-2

Here is what `nodetool status` reports:

```
$ kubectl exec -it cluster-2-dc1-rack1-2 nodetool status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.16.1.3   289.83 KiB  256          66.0%             bb82e5a5-007b-4638-92c3-61f6abb52d6a  rack1
UN  10.16.0.6   277.21 KiB  256          67.1%             94555840-ab60-4478-a871-de8f40db1e66  rack1
UN  10.16.1.10  271.41 KiB  256          66.8%             6c603af3-30d2-44d5-b376-f4b57969ed11  rack1
```

I think some changes for DNS configuration with the pods may be required.

**Comment by puneetloya** [comment]
> I don't think that this is something that can (or should be) done through Reaper. AFAIK Reaper is just reporting the names/addresses returned from Cassandra via JMX.

You are right that reaper might not show the pod-names, but a cassandra pod/node may have a valid FQDN which can be shown if available right? So that looking up a cassandra pod/node thats in trouble does not involve an extra step of resolving ip -> dns name

**Comment by adejanovski** [comment]
We now have a working solution in `master` for k8s clusters through #870

I'll close the ticket.
