### ISSUE TITLE
Allow dynamic JMX credentials when adding clusters

### ISSUE THREAD

**Issue by rzvoncek** [thelastpickle/cassandra-reaper#814]
When a cluster is being added to Reaper, and this cluster happens to use JMX authentication, then Reaper uses credentials from `jmxAuth` in its yaml file.

This is not practical when different clusters use different JMX credentials. 

One suggestion of solving this is removing the `jmxAuth` from the yaml file and adding username and password field into the API call that adds a cluster. From there, the the credentials should end up stored inside the node/cluster properties column (together with the JMX port), for example as a part of #809.

**Comment by adejanovski** [comment]
Done and available in 2.0+ versions of Reaper.
