### ISSUE TITLE
Debian packages out of date

### ISSUE THREAD

**Issue by gtaylor** [thelastpickle/cassandra-reaper#82]
We've started playing around with your fork of cassandra-reaper over at Reddit and set out to get things all nicely packaged with the included debian definitions. It looks like these are out of date now. Are these going to be maintained long term? If so, are updates in the plans?

**Comment by rustyrazorblade** [comment]
I had begun the transition to FPM to simplify things but only got it halfway finished.  Check out https://github.com/thelastpickle/cassandra-reaper/blob/master/Makefile#L21, where it calls out to FPM to build the debian package.

**Comment by gtaylor** [comment]
Mystery solved. Thanks, @rustyrazorblade! Should I close this issue?

**Comment by rustyrazorblade** [comment]
Awesome, good to hear.  Closing it out.
