### ISSUE TITLE
ipv6 problem with jmx connection

### ISSUE THREAD

**Issue by ypen19** [thelastpickle/cassandra-reaper#828]
When cassandra ip address is in ipv6 address format only, the JmxConnectionFactory.java connection will failed because the code simply concatenates the port to the address without adding "[" and "]" around the ipv6 address.

My temp fix is something like:
  protected JmxProxy connectImpl(Node node) throws ReaperException, InterruptedException {
    // use configured jmx port for host if provided
    String host = node.getHostname();
    if (jmxPorts != null && jmxPorts.containsKey(host) && !host.contains(":")) {
      host = host + ":" + jmxPorts.get(host);
      LOG.debug("Connecting to {} with specific port", host);
    } else if (JmxAddresses.isNumericIPv6Address(host)) {
      host = "[" + host + "]:" + node.getJmxPort();
      LOG.debug("Connecting to ipv6 {} with custom port", host);
    } else {
      host = host + ":" + node.getJmxPort();
      LOG.debug("Connecting to {} with custom port", host);
    }

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-419) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-419

**Comment by adejanovski** [comment]
Hi @ypen19,

would you mind submitting a PR with this fix?
That would be much appreciated.

**Comment by Rooks103** [comment]
This should be fixed with MR #1056. @ypen19 Thanks for the tip on how to fix this!
