### ISSUE TITLE
viewability issue when having multiple datacenters for a cluster in the cluster overview

### ISSUE THREAD

**Issue by hack2learn** [thelastpickle/cassandra-reaper#831]
we have some viewability issue when you have multiple datacenters for a given cluster in the cluster overview.

![Screen Shot 2020-01-09 at 1 24 30 PM](https://user-images.githubusercontent.com/822679/72094141-c0b0d200-32e3-11ea-9663-9712808da8ba.png)

It's a minor issue, but would be great to address it at some point.

**Comment by adejanovski** [comment]
The UI doesn't deal nicely with large imbalances.
We will fix this though a UI revamp that will most likely remove the detailed view of the cluster in favor of a more compact display with key metrics/informations.
We'll track this work in #872 and I'll close this issue.
