### ISSUE TITLE
Ability to edit schedules in the UI

### ISSUE THREAD

**Issue by hack2learn** [thelastpickle/cassandra-reaper#834]
It would be great to edit schedules in the UI directly.
We noticed that sometimes it can happen that repairs run in parallel. I was able to fix it, while editing the database directly, but it would be nice to just edit the schedules via UI.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-420) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-420

**Comment by adejanovski** [comment]
Yes, that would be a good thing to have 😅 and a pretty basic one actually...

**Comment by adejanovski** [comment]
This was implemented and shipped already.
