### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by MALPI** [thelastpickle/cassandra-reaper#84]
Hi there,

is this repo actively maintained? I see there many open PR's. Also one by me.

Don't get me wrong but it's nearly two weeks ago that I opened the PR?

**Comment by arodrime** [comment]
Hi, we are still maintaining this repo actively.

@adejanovski (who is actively working on reaper) took holidays and was already out when you created your PR. We also have to run core business, helping people around.

We should be able to have a look soon though.

C*heers!

**Comment by MALPI** [comment]
Ok, thanks for update @arodrime!

**Comment by adejanovski** [comment]
Hi @MALPI,

don't worry, the project is still active and the open PR's are just pending review or completion.
Opening a PR is a way to start working on a feature while getting feedback from Travis or Sonar, and allow a discussion. It is not necessarily meant to be mergerd/closed right away.

I'll take a look at the open PRs now and update their status.

Cheers
