### ISSUE TITLE
Cannot start manual repair on keyspace if scheduled repair exists

### ISSUE THREAD

**Issue by gaborauth** [thelastpickle/cassandra-reaper#849]
```
java.lang.IllegalArgumentException: unit conflicts with existing in clustername:keyspacename
```

**Comment by michaelsembwever** [comment]
This is intentional, so to avoid another user coming in and repairing a table in a different way that messes it up. (We are thinking about how to improve it though.)

Go to the schedule for that keyspace and hit `Run Now`.

**Comment by gaborauth** [comment]
Okay, but the "Run now" changes the scheduled time to "now" and I can't edit it to the original time with the UI, need to update it directly in the database, if I want it to run in the future at the original schedule.

Is it possible that "Run now" does not change the next_activation time?

**Comment by michaelsembwever** [comment]
> Is it possible that "Run now" does not change the next_activation time?

No. We are aware of this unfortunate side-effect of using the "Run Now" button. We are open to any fixes/improvements where it honours the original schedule cycle.

**Comment by gaborauth** [comment]
I do not know the depths of Cassandra repair nor Reaper, but could it not be possible to rewrite the original next_activation value after the repair started with "Run now"? This is exactly what I do with my hands and I haven't seen any side effects yet... :)

**Comment by michaelsembwever** [comment]
Yes. Or just not update `next_activation` when doing the "Run Now"… 

In theory it is simple, just the code and the method signatures are a bit off i believe.
