### ISSUE TITLE
Cassandra-reaper grafana dashboard

### ISSUE THREAD

**Issue by therb1** [thelastpickle/cassandra-reaper#857]
Do you have cassandra-reaper prometheus dashboard?
based on `servername:8081/prometheusMetrics`

**Comment by adejanovski** [comment]
I think @rzvoncek and @arodrime are planning on building one in [tlp-dashboards](https://github.com/thelastpickle/tlp-dashboards).

**Comment by rzvoncek** [comment]
Indeed, we'll track this in https://github.com/thelastpickle/tlp-dashboards/issues/8
