### ISSUE TITLE
support cleanup

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#86]
We should be able to kick off a cleanup that works on 1 node at a time.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-423) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-423

**Comment by rsaffi** [comment]
Is there any news on this (much desired) feature @rustyrazorblade?

**Comment by rustyrazorblade** [comment]
Nothing yet.  Priorities are set by either people hacking in the code or the folks we work with that need features.  Ambitious goals, so little time.

**Comment by yusufaytas** [comment]
@rustyrazorblade I can take on this? What's the procedure to do so?

**Comment by rustyrazorblade** [comment]
@yusufaytas That's a question for @mck and @adejanovski .

**Comment by jmooo** [comment]
Until cleanup is automated, would the proper sequence for bootstrapping new nodes and using reaper be:

- Bring new nodes online 1-by-1 until all nodes report `UP`
- Use reaper to run a repair on each keyspace in the cluster
- Manually run `nodetool cleanup` on every node in the cluster

**Comment by adejanovski** [comment]
There are other tools that handle such coordinated operations such as cstar for non k8s deployments or cass-operator for k8s deployments, so it doesn't seem relevant to implement this in Reaper itself.
I'll close the ticket.
