### ISSUE TITLE
Freeze repairs on version 2.0.2

### ISSUE THREAD

**Issue by therb1** [thelastpickle/cassandra-reaper#868]
Hi, my repair was freezed like in https://github.com/thelastpickle/cassandra-reaper/issues/863. I delete all freezed repairs jobs.
After that, i start repair again. All gonna fine, but one of the repairs gonna say this nothing when i push "Activate" button and dont wanna activate it.

That what i see in UI
![image](https://user-images.githubusercontent.com/9654476/77238952-64710500-6be6-11ea-88ba-b7ad771bdc38.png)

That i see in console
![image](https://user-images.githubusercontent.com/9654476/77239062-5374c380-6be7-11ea-9eaf-102e5dfbb881.png)

This is text from console
```
repair.js?81b5718b6b66b2884710:40 PUT https://cassandra-reaper.domain.org/repair_run/5f100fd0-6bcc-11ea-87ef-29317804cd55/state/RUNNING 409 (Conflict)
send @ repair.js?81b5718b6b66b2884710:40
ajax @ repair.js?81b5718b6b66b2884710:40
(anonymous) @ repair.js?81b5718b6b66b2884710:54
Oe @ repair.js?81b5718b6b66b2884710:62
yn.onNext @ repair.js?81b5718b6b66b2884710:62
onNext @ repair.js?81b5718b6b66b2884710:62
_onToggleStatus @ repair.js?81b5718b6b66b2884710:40
o @ repair.js?81b5718b6b66b2884710:40
s @ repair.js?81b5718b6b66b2884710:40
executeDispatchesInOrder @ repair.js?81b5718b6b66b2884710:40
d @ repair.js?81b5718b6b66b2884710:40
p @ repair.js?81b5718b6b66b2884710:40
e.exports @ repair.js?81b5718b6b66b2884710:54
processEventQueue @ repair.js?81b5718b6b66b2884710:40
(anonymous) @ repair.js?81b5718b6b66b2884710:62
handleTopLevel @ repair.js?81b5718b6b66b2884710:62
p @ repair.js?81b5718b6b66b2884710:62
perform @ repair.js?81b5718b6b66b2884710:40
batchedUpdates @ repair.js?81b5718b6b66b2884710:62
batchedUpdates @ repair.js?81b5718b6b66b2884710:16
dispatchEvent @ repair.js?81b5718b6b66b2884710:62
repair.js?81b5718b6b66b2884710:54 Deleting repair run with id: 5f100fd0-6bcc-11ea-87ef-29317804cd55
repair.js?81b5718b6b66b2884710:54 Starting repair for cluster: common-fallback-cas
repair.js?81b5718b6b66b2884710:54 Updating repair run c646f1a0-6bcc-11ea-87ef-29317804cd55 status with state RUNNING
```
What i can give to you? to fix this

**Comment by adejanovski** [comment]
This error pops up when another repair at RUNNING state already exists for the same repair unit (definition). 
Maybe the database ended up in a funny state for some reason, but it would be good to see if we have other repair runs that were running with the same `repair_unit_id` as run `c646f1a0-6bcc-11ea-87ef-29317804cd55`.
Do you still have data for investigation?
If not, please close this ticket and let's reopen it in case the issue pops up again.
Thanks
