### ISSUE TITLE
trying to add a seed node ,however getting error no cluster in seed node , please hel pon this ?

### ISSUE THREAD

**Issue by Sarahshee** [thelastpickle/cassandra-reaper#869]
**Spotted on 2.0.3 (4e6725d)**

**Comment by adejanovski** [comment]
Hi, could you provide more informations on what's happening?
Error messages, screenshots, log extracts?

Thanks

**Comment by Sarahshee** [comment]
fixed the issue after JMX auth enabled on cassandra cluster..  thanks for the response.
