### ISSUE TITLE
support snapshot

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#87]
It would be cool if reaper could take a snapshot on all nodes.

**Comment by MALPI** [comment]
In addition to that it would be great if it would offer the possibility to export the snapshots to an external volume for example S3.

**Comment by rustyrazorblade** [comment]
The challenging part there is now we need to add a new transport layer into the mix.  Not saying it can't be done, it would just be a pretty major architectural decision to start SSH'ing into boxes vs using remote JMX commands.

**Comment by MALPI** [comment]
Yes you are right. I didn't think about that to be honest. I just had in mind that the snapshots will eat up diskspace. On the one hand reaper is reducing maintenance efforts then by regularly repairs. On the other you have to keep track of your snapshots and the disk space that is eaten up by them and increasing efforts again.

**Comment by MALPI** [comment]
Should it be possible to schedule snapshots for EBS Volumes with reaper as well?

**Comment by rustyrazorblade** [comment]
> Should it be possible to schedule snapshots for EBS Volumes with reaper as well?

This is very specific to AWS, so probably not.

**Comment by rustyrazorblade** [comment]
Generally if it's not a JMX command, the answer is "probably not".

**Comment by MALPI** [comment]
I get the point that this is a different protocol and AWS specific, but nonetheless it is a valid usecase or not? And since I already have an instance running which is taking care about scheduling cassandra specific taks why not offer this feature as well?

**Comment by rustyrazorblade** [comment]
We won't be adding AWS snapshotting to Reaper.  It's a tool for Cassandra.  This issue is for taking Cassandra snapshots via JMX.  AWS snapshots belong in an AWS management & configuration tool.

**Comment by adejanovski** [comment]
Snapshots are now supported in master. (will be 1.2.0 once released)
