### ISSUE TITLE
Reaper UI squashes cluster information

### ISSUE THREAD

**Issue by elsmorian** [thelastpickle/cassandra-reaper#872]
**Spotted on 2.0.2 (3d4ac2f)**

In Safari Version 13.0.5 (14608.5.12)

<img width="1366" alt="Screenshot 2020-03-30 at 17 22 02" src="https://user-images.githubusercontent.com/64268/77938936-5db15480-72ae-11ea-89be-1ecbda75fbb7.png">

**Comment by adejanovski** [comment]
Closing this issue as we'll deal with it in #827
