### ISSUE TITLE
2.0.3 release missing on Docker Hub

### ISSUE THREAD

**Issue by derek9gag** [thelastpickle/cassandra-reaper#873]
The latest image on Docker Hub is 2 months old, and 2.0.3 is not published. Is it still supported? If so can you publish the latest version to DockerHub?

https://hub.docker.com/r/thelastpickle/cassandra-reaper/tags

Thank you!

**Comment by adejanovski** [comment]
Hi @derek9gag,

there may be a problem in the new GHA based release workflow.
I'll check this with the 2.0.4 release that's running now and fix what needs fixing.
Thanks for reporting the issue.

**Comment by adejanovski** [comment]
I guess having the `docker push` commands commented doesn't help 😅 
I've pushed `2.0.4` and `latest`, and have opened a PR to fix this.

**Comment by derek9gag** [comment]
Thank you!
