### ISSUE TITLE
Streaming progress bars hide detail text until the are progressed enough!

### ISSUE THREAD

**Issue by elsmorian** [thelastpickle/cassandra-reaper#874]
**Spotted on 2.0.2 (3d4ac2f)**

In the node detail popover, the streaming information in a progress bar only shows as the progress bar increases!

<img width="1336" alt="Screenshot 2020-04-01 at 20 06 54" src="https://user-images.githubusercontent.com/64268/78183572-09e66d00-7460-11ea-8182-264284f244bc.png">

**Comment by rzvoncek** [comment]
Will look into this once https://github.com/thelastpickle/cassandra-reaper/issues/823 gets done.

**Comment by elsmorian** [comment]
🎉🎉🎉

**Comment by elsmorian** [comment]
Thanks for addressing this!
