### ISSUE TITLE
support upgradesstables

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/cassandra-reaper#88]
reaper should be able to upgradesstables in a rolling fashion.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-426) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-426

**Comment by adejanovski** [comment]
We recommend using cstar or cass-operator for that feature.
