### ISSUE TITLE
Yaml config file gets overwritten during RPM update

### ISSUE THREAD

**Issue by moneytoo** [thelastpickle/cassandra-reaper#89]
When I update reaper using built RPM, config file ``/etc/spotify/cassandra-reaper.yaml`` with local changes gets overwritten from the one from RPM (instead of being saved as ``.rpmsave``/``.rpmnew``).
As the RPM was build by fpm, this should resolved by using the option ``--config-files``.

**Comment by adejanovski** [comment]
Hi @moneytoo,

I agree this would be a cool improvement to handle upgrades.
My knowledge of fpm is pretty minimal : would you be willing to contribute and send a PR that handles this ?

Thanks !

**Comment by kotaroyamazaki** [comment]
This ticket seems to be  already done.

https://github.com/thelastpickle/cassandra-reaper/commit/c0cf00310ac5947a378381ae9babb2e4ec17624c#diff-2bb7d1c81ea630104d155ab892ba72e9R35
