### ISSUE TITLE
Build mockups of the new Reaper landing page and cluster drill down

### ISSUE THREAD

**Issue by adejanovski** [thelastpickle/cassandra-reaper#892]

**Comment by ossarga** [comment]
@adejanovski this is my first cut of the landing page and cluster drill down.

[Reaper_cluster_ui_proposal_wireframes.pdf](https://github.com/thelastpickle/cassandra-reaper/files/4935920/Reaper_cluster_ui_proposal_wireframes.pdf)

 I have other ideas for the cluster drill down however I think the are a very different to what we have at the moment and more complex to implement.

**Comment by adejanovski** [comment]
Landing page (formerly called "Clusters"): 
It would be good to make obvious how many nodes are down/up.
The menu button at the top right should be turned into a cross to forget the cluster (and ask for a confirmation first).
Remove the status bubble and add a status box within the cluster details showing the number of down nodes (hidden if all nodes are up). Highlight the box in red/orange/... 
Clicking on the number of running repairs (or the repair progress bar), we go straight to the repair page, filtered on this cluster.
Clicking on the cluster name takes us to the cluster view, filtered on this cluster.

Cluster view:
A new screen should be added (with its menu tab) for cluster details. This allows to match the UX of the other pages and still use a modal for the node detailed view.
Cluster view will have a filter drop down. No cluster details are shown until a cluster is selected.


Logout button should be shown only if the authentication cookie is there (JSESSIONID).

**Comment by ossarga** [comment]
Updated wireframes as per the comments above.

[Reaper_cluster_ui_proposal_wireframes_v2.pdf](https://github.com/thelastpickle/cassandra-reaper/files/4981795/Reaper_cluster_ui_proposal_wireframes_v2.pdf)

As discussed with @adejanovski now that the wireframe is updated we can close the ticket and being updating the Reaper UI. 

# Details

**Tabs Menu Bar**
The tab menu bar replaces the side bar. The idea is to give the Reaper UI more horizontal screen realestate. In addition, the menu bar will persists across all screens and when scrolling down the page. This will allow for large numbers of clusters or repairs be scrolled through on a page while providing the ability to navigate else where if desired.
The logout menu item has been removed from the menu and turned into a button. This will allow it to be disabled and hidden if the there is no authentication cookie (JSESSIONID) present.

**Home Page**
The landing page is currently called "Home" in the wireframes. The naming of this page can be changed. We could for example call it "Summary". The "Home" page contains a status summary of each cluster known to Reaper. Each cluster is still represented by a panel in a list. However, the detailed state of each node in the cluster has been moved to the "Cluster View" page. The panel now contains badges with various details about the cluster. When a panel is clicked on the user is taken to the "Cluster View" page which has a more detailed view filtered to the cluster is was licked one.. The repair status bar and running repair count badge still exist in the cluster panel. When either is clicked on they are taken to the "Repair" page filtered to the cluster that was clicked on. 
The proposed status bubble has been removed and a status badge showing the number of down nodes has been added. This badge will appear when the number of down nodes in a cluster is > 0.
The "Nodes" badge on the original UI has been removed and replaced by badge showing the number of nodes that are up.
The "Forget" button on the original UI has been replaced with a cross on the right hand corner. When clicked a model will pop up and the user will be prompted to confirm the deletion by typing in the cluster name.
The panel to add a cluster has been removed and only the "Add Cluster" button remains. When this button is clicked a model will appear that prompts the user to fill out the required details to add a cluster.

**Cluster View**
A new page has been added called "Cluster View". This page is a detailed view of a cluster. Only a single cluster at a time can be displayed on this page. A drop down box at the top allows the desired cluster to be selected. Clicking on a cluster pane in the "Home" screen will navigate to this page showing the cluster it was clicked on.
