### ISSUE TITLE
Question about SLEEP_TIME_AFTER_POSTPONE_IN_MS parameter in SegmentRunner class

### ISSUE THREAD

**Issue by shyfu** [thelastpickle/cassandra-reaper#907]
Hello,

We're having issues with too long repair runs for our Cassandra tables. We were researching reaper code and found out that there's this parameter SLEEP_TIME_AFTER_POSTPONE_IN_MS  which is defaulted to 10 seconds and this sleep happens after each postpone. Is there any hidden sense on necessity of this parameter and what are the ricks in reducing its value to something much smaller, e.g. 10ms.

Appreciate your help in advance!

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-432) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-432

**Comment by adejanovski** [comment]
The risk here would be to overload Reaper and its backend with unnecessary calls if segments cannot be scheduled. We have other scheduled calls in the segment scheduler that use similar intervals, and reducing them would trigger a lot of unnecessary reads on the storage backend.
