### ISSUE TITLE
Update copyright notice on files

### ISSUE THREAD

**Issue by ossarga** [thelastpickle/cassandra-reaper#910]
Now that Datastax owns the Reaper code base we should change the copyright notice on all the files in the repository.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-435) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-435

**Comment by michaelsembwever** [comment]
Good question. Anyone feel like doing some research as to what a) is valid, and b) what is precedent and smart to do?

**Comment by michaelsembwever** [comment]
Note, no copyright is getting "changed" here.

All files that were touched in 2020 by anyone employed at DataStax will get the line *added*
```
Copyright 2020- DataStax, Inc.
```

(this might require an update to the checkstyle rule)
