### ISSUE TITLE
Typo in documentation: postrges

### ISSUE THREAD

**Issue by JensRantil** [thelastpickle/cassandra-reaper#913]
"postrges" in http://cassandra-reaper.io/docs/backends/.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-436) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-436

**Comment by adejanovski** [comment]
Postgres references were now removed from that page. Closing the issue.
