### ISSUE TITLE
Can't delete repair

### ISSUE THREAD

**Issue by TaiSHiNet** [thelastpickle/cassandra-reaper#920]
**Spotted on 2.0.4 (fe78e6b)**

o/

Tried deleting an aborted run from the interface and was unable to do so. Tried as well with spreaper, I do see this in the logs:

```
INFO   [2020-05-13 10:42:17,610] [dw-65 - DELETE /repair_run/00000000-0000-0003-0000-000000000000?owner=Carlos] i.c.r.RepairRunResource - delete repair run called with runId: 00000000-0000-0003-0000-000000000000, and owner: Optional[Carlos]
```

Any pointers are greatly appreciated

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-441) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-441

**Comment by adejanovski** [comment]
Hi,

Are you using Cassandra as storage backend for reaper?

**Comment by TaiSHiNet** [comment]
Hey, no, local H2 for now

**Comment by adejanovski** [comment]
I'll close this issue due to inactivity.
Let us know if you're still experiencing this problem.
