### ISSUE TITLE
Reaper Web UI cannot find the reaper server after ~30 seconds

### ISSUE THREAD

**Issue by mpurgahn123** [thelastpickle/cassandra-reaper#931]
![image](https://user-images.githubusercontent.com/66804550/84443592-ebde7b00-ac0d-11ea-84fb-74bc53809be8.png)

I have successfully connected multiple clusters to my reaper server and they show up in the web UI. But after about 30-60 seconds I get the error message above. When I take a look at the reaper logs it is just metrics output. Nothing that seems to correlate with the error I am seeing in the UI. Reaper has access to ports 7199, 9042, and 9160 on my Cassandra nodes. Is there anyway for me to debug this further?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-444) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-444

**Comment by adejanovski** [comment]
@mpurgahn123 did you ever manage to fix this issue?

I'll close it because it's been inactive for a while, but feel free to reopen if this is still a problem.
