### ISSUE TITLE
How does one specify the configuration file location?

### ISSUE THREAD

**Issue by abstract-base-method** [thelastpickle/cassandra-reaper#932]
Howdy! I am trying to get Reaper installed and I want to point the application at my YAML file within a directory on my machine. I haven't found any documentation reference to the correct JVM flag or environment variable to do this. If there already is some documentation please point me that way -- or tell me and I'd be happy to file a PR adding it to the docs! 

Thank you for your time reading this and I appreciate any responses!

**Comment by abstract-base-method** [comment]
[it is found at the bottom of the installation page](http://cassandra-reaper.io/docs/download/install/) sorry for the notifications on this!

**Comment by michaelsembwever** [comment]
Thanks for closing the loop on this, with the info @lemoney , appreciated.
