### ISSUE TITLE
Datacenter names with underscopes are unsupported

### ISSUE THREAD

**Issue by zubchenok** [thelastpickle/cassandra-reaper#936]
If datacenter name contains an underscore, Reapear only displays part of datacenter name that is before the underscore.
At Clusters page such datacenters are merged into a single one.

Reproduces with Reaper 2.0.2

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-447) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-447

**Comment by adejanovski** [comment]
Fixed in #1129
