### ISSUE TITLE
repair session failed

### ISSUE THREAD

**Issue by vchauhan81** [thelastpickle/cassandra-reaper#945]
I am using Reaper version 1.1.0 & cassandra version is 3.11.0. 
I am having 2 DC setup and each DC having 3 nodes. 
In the reaper log we are continuously seeing following errors. 

**I have referred :** 
https://github.com/thelastpickle/cassandra-reaper/issues/133
https://github.com/thelastpickle/cassandra-reaper/issues/565
http://cassandra-reaper.io/docs/configuration/reaper_specific/

Based on the documentation and the above article I tried adjusting both these parameters – but I am still seeing those errors. 

1)	segmentCountPerNode – default value is 16. I tested with value 8, 6, 150, 200. I can still sees the same errors.
2)	hangingRepairTimeoutMins – default value is 30. I tested with 40 and 50 and  I can still sees the same errors.

**Errors in reaper log :** 

WARN   [2020-08-05 00:01:58,205] [mytestcluster:60ea5be0-d679-11ea-a3d8-3903d8a66ccf:60eaab5c-d679-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id '60eaab5c-d679-11ea-a3d8-3903d8a66ccf' and repair number '38522' 
ERROR  [2020-08-05 00:02:08,389] [mytestcluster:60ea5be0-d679-11ea-a3d8-3903d8a66ccf:60eaab5c-d679-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment 60eaab5c-d679-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:02:08,446] [mytestcluster:60ea5be0-d679-11ea-a3d8-3903d8a66ccf:60eaab5c-d679-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment 60eaab5c-d679-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:02:23,594] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97d1a8e-d676-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id 'b97d1a8e-d676-11ea-a3d8-3903d8a66ccf' and repair number '38525' 
WARN   [2020-08-05 00:02:23,617] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f211673a-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id 'f211673a-d66c-11ea-a3d8-3903d8a66ccf' and repair number '165528' 
ERROR  [2020-08-05 00:02:33,667] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f211673a-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment f211673a-d66c-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:02:33,684] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f211673a-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment f211673a-d66c-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:02:33,697] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97d1a8e-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment b97d1a8e-d676-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:02:33,704] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97d1a8e-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment b97d1a8e-d676-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:04:45,422] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f2118d80-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - A host (10.15.100.209) reported that it is involved in a repair, but there is no record of any ongoing repair involving the host. Sending command to abort all repairs on the host. 
WARN   [2020-08-05 00:04:45,685] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97cccdb-d676-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id 'b97cccdb-d676-11ea-a3d8-3903d8a66ccf' and repair number '165471' 
ERROR  [2020-08-05 00:04:55,827] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97cccdb-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment b97cccdb-d676-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:04:55,845] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97cccdb-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment b97cccdb-d676-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:04:55,846] [mytestcluster:9d3921b0-d67b-11ea-a3d8-3903d8a66ccf:9d39be38-d67b-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id '9d39be38-d67b-11ea-a3d8-3903d8a66ccf' and repair number '165472' 
ERROR  [2020-08-05 00:05:06,009] [mytestcluster:9d3921b0-d67b-11ea-a3d8-3903d8a66ccf:9d39be38-d67b-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment 9d39be38-d67b-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:05:06,024] [mytestcluster:9d3921b0-d67b-11ea-a3d8-3903d8a66ccf:9d39be38-d67b-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment 9d39be38-d67b-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:05:06,051] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97ccd22-d676-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id 'b97ccd22-d676-11ea-a3d8-3903d8a66ccf' and repair number '165540' 
ERROR  [2020-08-05 00:05:16,123] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97ccd22-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment b97ccd22-d676-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:05:16,162] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97ccd22-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment b97ccd22-d676-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:06:47,181] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97ccbba-d676-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id 'b97ccbba-d676-11ea-a3d8-3903d8a66ccf' and repair number '164991' 
ERROR  [2020-08-05 00:06:57,430] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97ccbba-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment b97ccbba-d676-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:06:57,478] [mytestcluster:b97ca4a0-d676-11ea-a3d8-3903d8a66ccf:b97ccbba-d676-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment b97ccbba-d676-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:17:05,188] [mytestcluster:2c3dd540-d67c-11ea-a3d8-3903d8a66ccf:2c3dd65b-d67c-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - A host (10.15.100.210) reported that it is involved in a repair, but there is no record of any ongoing repair involving the host. Sending command to abort all repairs on the host. 
WARN   [2020-08-05 00:17:05,377] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f211194a-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id 'f211194a-d66c-11ea-a3d8-3903d8a66ccf' and repair number '143221' 
ERROR  [2020-08-05 00:17:15,451] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f211194a-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment f211194a-d66c-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:17:15,488] [mytestcluster:f210f0f0-d66c-11ea-a3d8-3903d8a66ccf:f211194a-d66c-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment f211194a-d66c-11ea-a3d8-3903d8a66ccf 
WARN   [2020-08-05 00:18:38,980] [mytestcluster:9d3921b0-d67b-11ea-a3d8-3903d8a66ccf:9d39e50c-d67b-11ea-a3d8-3903d8a66ccf] i.c.s.SegmentRunner - repair session failed for segment with id '9d39e50c-d67b-11ea-a3d8-3903d8a66ccf' and repair number '38632' 
ERROR  [2020-08-05 00:18:49,098] [mytestcluster:9d3921b0-d67b-11ea-a3d8-3903d8a66ccf:9d39e50c-d67b-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Failed to renew lead on segment 9d39e50c-d67b-11ea-a3d8-3903d8a66ccf 
ERROR  [2020-08-05 00:18:49,103] [mytestcluster:9d3921b0-d67b-11ea-a3d8-3903d8a66ccf:9d39e50c-d67b-11ea-a3d8-3903d8a66ccf] i.c.s.CassandraStorage - Could not release lead on segment 9d39e50c-d67b-11ea-a3d8-3903d8a66ccf

**Comment by vchauhan81** [comment]
@adejanovski 
Can you please review this and provide some pointers to move ahead ? 
We are stuck due to this issue.

Thanks in advance,
Vijay.

**Comment by adejanovski** [comment]
Hi, 

your version of Reaper is fairly outdated.
I'd recommend to upgrade at least to Reaper 1.4.8 and see if the error persists.
You cannot directly upgrade from 1.1 to 2.0.5 by the way and will need to go through the 1.4.8 upgrade first anyway.

**Comment by vchauhan81** [comment]
@adejanovski 
Thanks for the inputs, I'll try the upgrade path and confirm.

Thanks a lot.

**Comment by adejanovski** [comment]
Hi @vchauhan81,

did you get a chance to perform the upgrade?

**Comment by vchauhan81** [comment]
@adejanovski
I upgraded to 1.4.8 and I no longer see the errors. 
Thanks a lot for prompt response. 

Based on this I have further query - you mentioned we can not directly upgrade from 1.1 to 2.0.5. Do we have any instructions available for this 2 step upgrade ? I tried to search, but didn't find anything.

**Comment by jnalawad** [comment]
@adejanovski
As Vijay (vchauhan81) mentioned we are going to upgrade to 2.0.5 and probably 2.1.3 which is latest stable version.

Based on the upgrade note from 
http://cassandra-reaper.io/docs/download/

**Upgrading from 1.2.0/1.2.1 to 1.2.2
We unfortunately had to break schema migrations for upgrades to 1.2.2 from 1.2.0 and 1.2.1. Here is the upgrade procedure for each Reaper backend**

So does this note applies to upgrade from 1.1.0 to 2.0.5 (2.1.3)?
Do we have steps which we can refer for such upgrade scenario?

**Comment by adejanovski** [comment]
No, it only applies to 1.2.0/1.2.1 upgrades to 1.2.2.
In your case, it'll be necessary to perform a first upgrade to either 1.2.2 or 1.4.8 and then jump to 2.1.3.
Upgrading from pre-1.2.2 to 2.0+ is impossible because we merged some schema migrations to reduce their number (it was getting fairly big and delayed the first startup quite a lot).

**Comment by jnalawad** [comment]
Just to simplify the upgrade, do you see any issues if we follow below route
1. We will stop all instances of Reaper 1.1.0 (graceful shutdown)
2. Drop the keyspace reaper_db from Cassandra. So no trace of repair left now.
3. Install Reaper 2.1.3. Keep some of the configuration parameters from previous version (1.1.0) on Reaper 2.1.3

**Comment by adejanovski** [comment]
If you drop the reaper_db keyspace you're not really doing an upgrade then but rather a full reinstall (from Reaper's perspective at least as there will be no existing schema migration). Package upgrades are not a problem from any version to any other.

You'll be fine then 👍

**Comment by jnalawad** [comment]
Thanks a lot for the confirmation. This is useful.

**Comment by adejanovski** [comment]
I'll close this ticket due to inactivity.
Feel free to reopen if you're still experiencing this issue.
