### ISSUE TITLE
Auto-scheduler wrongly deleting schedules

### ISSUE THREAD

**Issue by atallahade** [thelastpickle/cassandra-reaper#950]
The auto-scheduler seems to be deleting some schedules by mistake. These schedules get eventually re-created with the default repair options.
I think most users won't notice the issue if all schedules are created by the auto-scheduler, since the repair options won't change, but this isn't my case.

In my case, all schedules are created by the auto-scheduler but a few are deleted and manually re-created so that different repair settings can be used. I'm not aware of any ways of editing a schedule nor ways to make the auto-scheduler give different repair options to different keyspaces, but this is another issue.

This bug will delete any schedules, whether they have been created by the auto-scheduler or manually.
This is what I found in the Reaper output: (I had 39 occurrence in a single day but most of them around the same time)
> [AutoSchedulingManagerTimer] i.c.s.ClusterRepairScheduler - Scheduled repair deleted: RepairSchedule[98cd4e90-e0ac-11ea-96c8-2757f25e76d3]

It seems to me that something could be off [around here](https://github.com/thelastpickle/cassandra-reaper/blob/2.0.5/src/server/src/main/java/io/cassandrareaper/service/ClusterRepairScheduler.java#L153-L159).
The `keyspacesDeleted` would contain a keyspace if a repair schedule exist with this keyspace but the keyspace couldn't be found in the cluster. Maybe something is off with the way the list of keyspaces is fetched from a cluster.

I can try to do more investigation in a few weeks by running a fork of reaper and adding some logging.
I could also check if this issue happen when nodes in a cluster are restarted/down or after Reaper has restarted.

Reaper version I use: 2.0.4

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-452) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-452

**Comment by adejanovski** [comment]
Hi @atallahade,

could it be that one IP which was previously for a node in cluster A was reused in cluster B? I seem to remember that you run Cassandra on k8s, and that your IP addresses had quite a turnover.
This could explain the behavior you're observing.

Let me know if you have more information.

**Comment by atallahade** [comment]
Thanks @adejanovski, I think you got it right, I've indeed observed the issue happening during cluster restarts, where pods are being replaced by new ones, along with the IP address being used by Cassandra. I've seen IP addresses being used on different clusters (at different time).
Do you think this is something that could be handled by Reaper? In any case, I think it's best for us to avoid this situation, so we'll also work on preventing the issue on our end.

**Comment by atallahade** [comment]
My guess would be that an IP from the cluster seed list is being used to fetch the list of keyspaces, while this IP got re-assigned to a node from another cluster (due to pod restarts). We have a script to update the seed list, but it only runs at fixed interval, not as soon as IPs are changing.

**Comment by adejanovski** [comment]
Best practices are to use k8s services as contact points and prevent auto refresh in configuration.
I'll close this ticket @atallahade, let me know if you want to re-open it.
