### ISSUE TITLE
How to set primary   --partitioner-range on reaper UI?

### ISSUE THREAD

**Issue by DanielZhangQingLong** [thelastpickle/cassandra-reaper#954]
What is equivalent setting on UI  to ‘nodetool repair -full graphy_production ip -j 4 -pr -seq’ command line ?

![Xnip2020-09-09!UNITO-UNDERSCORE!09-37-48](https://user-images.githubusercontent.com/5125999/92544880-88ea9780-f281-11ea-922b-22431b0384a7.jpg)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-453) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-453

**Comment by adejanovski** [comment]
Setting -pr isn't relevant to Reaper as it processes repairs per token range, not per node.
