### ISSUE TITLE
failed to find cluster with seed host cassandra-test-1@TestCluster. 

### ISSUE THREAD

**Issue by sandpwr** [thelastpickle/cassandra-reaper#958]
**Spotted on 1.4.0 (4c225e6)** and in latest versions also. 

**Errors:**

**Console error:**

failed to find cluster with seed host cassandra-test-1TestCluster. 

**Reaper is throwing below error in log file**

POST addOrUpdateCluster called with seedHost: xx.xx.xxx.xxTestCluster
Caused by: io.cassandrareaper.ReaperException: Failure when establishing JMX connection to xx.xx.xxx.xx:7199 

jmxCredentials details with first letter of each initial word capitalised in cluster name is causing above error. 

**Note**: 

* Cluster names with smaller case with dashes (test-cluster) works fine. 
* All required ACL's are in place so no issues with firewall. 
* jmxCredentials looks like below 

jmxCredentials:
   TestCluster:
         username: xxx
         password: xxx
   test-cluster: 
         username: xxx
         password: xxx

As I mentioned above, first set of credentials are not working when cluster name is configured with upper case letter in each word. 

May I know why upper case cluster names are causing this issue? By any chance reaper code is normalising these names to smaller case at the time of reading? or I'm I doing something wrong?

Thanks in advance.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-455) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-455

**Comment by jlemuth** [comment]
I'm having this same issue, but I'm able to get it to connect if I have the jmxCredentials use the lowercase name of the cluster. Using the provided information. 'TestCluster' should be 'testcluster'.

jmxCredentials:
testcluster:
username: xxx
password: xxx
test-cluster:
username: xxx
password: xxx

I'm able to establish jmx authentication, but it does still show my cluster as lowercase in the reaper gui.

This can also be confusing as the official documentation gives an example of a cluster using camel case.

> Adding a new cluster with specific credentials requires to add the seed node in the following format : host@cluster To match the example above, it could be something like : 10.0.10.5@clusterProduction1 (http://cassandra-reaper.io/docs/configuration/reaper_specific/)

I've noticed that using the reaper api as well, the cluster needs to match exactly what is in reaper, which can cause some confusion when writing scripts to work with the api.

**Comment by sandpwr** [comment]
@alexleventer not sure if I can tag people like this but any update on above issue and plans to fix it?

Thanks,

**Comment by adejanovski** [comment]
My advice here would be to store the credentials in the database directly when registering clusters in Reaper. This requires to set up encryption as described under the `cryptograph` section on [this page](http://cassandra-reaper.io/docs/configuration/reaper_specific/).

Storing jmx credentials in the config file will soon be deprecated and removed.
