### ISSUE TITLE
repairProgress metric not updating for subsequent runs.

### ISSUE THREAD

**Issue by coosh** [thelastpickle/cassandra-reaper#959]
This may be something I am missing, however, I cannot find a reason for it. The first repair of `FILTEREDKEYSPACENAME` properly shows the repairProgress gauge of 0.0-1.0. Subsequent repairs is never updated (while using manually triggered repairs in cassandra reaper). I searched inside `/prometheusMetrics` however the only repairProgress I see is for the old run id with a 1 (100%) value. Which clearly is not true of the active running repair.  Looking in `/metrics?pretty=true` is the same result.

[Docs](http://cassandra-reaper.io/docs/metrics/dashboards/) pointing to using this metric 

Using cassandra-reaper 2.0.5

Paste of the raw metrics which is the only existent one for `io_cassandrareaper_service_RepairRunner_repairProgress_c5134_FILTEREDKEYSPACENAME`

```
# HELP io_cassandrareaper_service_RepairRunner_repairProgress_c5134_FILTEREDKEYSPACENAME_8c21ab30dccb11ea828babd573712197 Generated from Dropwizard metric import (metric=io.cassandrareaper.service.RepairRunner.repairProgress.c5134.FILTEREDKEYSPACENAME.8c21ab30dccb11ea828babd573712197, type=io.cassandrareaper.service.RepairRunner$$Lambda$249/274061983)
# TYPE io_cassandrareaper_service_RepairRunner_repairProgress_c5134_FILTEREDKEYSPACENAME_8c21ab30dccb11ea828babd573712197 gauge
io_cassandrareaper_service_RepairRunner_repairProgress_c5134_FILTEREDKEYSPACENAME_8c21ab30dccb11ea828babd573712197 1.0
```

(cluster/keyspace/runid obfuscated)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-456) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-456

**Comment by Skunnyk** [comment]
I can confirm the bug is still present in 2.3.1. This is not related to prometheus metrics, dropwizard metrics too are impacted (on host:8081/metrics). 
None of the `io.cassandrareaper.service.RepairRunner` metrics seems to be updated on subsequent runs.
