### ISSUE TITLE
Unable to create a schedule when multiple clusters have the same keyspace name.

### ISSUE THREAD

**Issue by ossarga** [thelastpickle/cassandra-reaper#964]
If two clusters contain the exact same set of keyspaces, the user is never able to add a schedule for the keyspace second cluster. From the UI perspective the "Add Schedule" button does nothing in this case. According to the Cassandra log, the cluster name remains unchanged. The user is still able to add and remove schedules for the first cluster.

This looks to be a bug in the UI.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-459) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-459

**Comment by NelsonJeppesen** [comment]
I have two C* clusters with different keyspaces, but only see the keyspaces in the first cluster from keyspace dropdown when trying to create a repair regardless of which cluster is selected. Sounds like the same issue

**Comment by ossarga** [comment]
PR #981 which fixes this issue is now merged.
