### ISSUE TITLE
Unable to schedule repair for specific keyspace.

### ISSUE THREAD

**Issue by shumak80** [thelastpickle/cassandra-reaper#979]
**Spotted on 2.1 (756cc4a)**
I'm trying to schedule a repair and if I choose cluster, there are not listed keyspaces for specified cluster. I'm not able to see any keyspace related to choosen cluster. I just see keyspaces related to default cluster. The Keyspace list is not refreshed on the cluster selection.

**Comment by shumak80** [comment]
Using postgres 10.14 as backend

**Comment by adejanovski** [comment]
Hi @shumak80,

what happens if you go to the cluster page and then click on the cluster name for the one you're trying to run a repair? Do the list of keyspaces appear this way?

Also, do you see anything in the developer console of Chrome (or the equivalent in Firefox) that would help us identify the problem? Errors in the javascript console or failed network calls that are used to list the keyspaces?

Thanks!

**Comment by shumak80** [comment]
When i click the cluster in cluster page, It goes to repair page but I still see the default cluster name (alphabetically the first one). This is the same for repair and schedules page. The dev console is not my cup of tea. But when I select, let say cluster name B in repair screen, the repair.js is touching tables from cluster A (which is the first in alphabet order). Like GET /cluster/A/tables instead of GET /cluster/B/tables.
I can not see any network problems or javascript errors.

**Comment by shumak80** [comment]
The WebUI behaves like I'm not choosing nothing from cluster field and using still same value.

**Comment by shumak80** [comment]
I've filter out some errors, not sure if this will useful:
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. webui:2191:156
Unknown property ‘-moz-text-decoration’.  Declaration dropped. webui:2191:605
Unknown property ‘orphans’.  Declaration dropped. webui:2191:2822
Unknown property ‘widows’.  Declaration dropped. webui:2191:2831
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. webui:2191:318225
Unknown property ‘-moz-text-decoration’.  Declaration dropped. webui:2191:330324
Error in parsing value for ‘outline’.  Declaration dropped. webui:2191:330422
Found invalid value for media feature. webui:2191:334966
Error in parsing value for ‘outline’.  Declaration dropped. webui:2191:352826
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. webui:2191:354197
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. webui:2191:354302
Error in parsing value for ‘margin-top’.  Declaration dropped. webui:2191:355994
Error in parsing value for ‘outline’.  Declaration dropped. webui:2191:364616
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:364989
Unknown property ‘-moz-text-decoration’.  Declaration dropped. webui:2191:374171
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:377660
Unrecognized at-rule or error parsing at-rule ‘@-o-keyframes’. webui:2191:411648
Unknown property ‘zoom’.  Declaration dropped. webui:2191:416062
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:436115
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:436238
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:437741
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:437794
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:439140
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:439186
Expected media feature name but found ‘transform-3d’. webui:2191:443631
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:445196
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:445611
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:446154
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:2191:446414
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’. webui:2191:449731
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. deps.js:33:81941
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. webui:4:769406
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:4:770426
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:4:770589
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:4:770755
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:4:770926
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:4:771099
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. webui:10:300

**Comment by shumak80** [comment]
Here are logs for XHR ... click on b-cassandra-test in cluster page, on next page GET for data in cluster a-cassandra-test is done

XHR GET https://cassandra-reaper.tool/cluster
[HTTP/1.1 200 OK 202ms]

XHR GET https://cassandra-reaper.tool/repair_run?clusterName=b-cassandra-test&limit=10
[HTTP/1.1 200 OK 202ms]

Pinging reaper server.. repair.js:40:24588
XHR GET https://cassandra-reaper.tool/ping
[HTTP/1.1 204 No Content 206ms]

XHR GET https://cassandra-reaper.tool/cluster
[HTTP/1.1 200 OK 203ms]

XHR GET https://cassandra-reaper.tool/cluster/a-cassandra-test
[HTTP/1.1 200 OK 207ms]

XHR GET https://cassandra-reaper.tool/cluster/a-cassandra-test/tables
[HTTP/1.1 200 OK 206ms]

**Comment by adejanovski** [comment]
Thanks @shumak80, I confirm the issue and will work on a fix ASAP.

**Comment by adejanovski** [comment]
@ossarga,

I made some tests and the cluster name change doesn't get picked up in the React state it seems and the `/cluster/{clusterName}/tables` call always goes to the same cluster:
![Capture d’écran 2020-10-27 à 16 54 52](https://user-images.githubusercontent.com/5096002/97327786-9da4de00-1875-11eb-9684-3265b3f78440.png)

Would you mind taking a look at this?
This could also affect other drop downs that use the same code path.

Thanks!

**Comment by adejanovski** [comment]
I pushed a PR to fix this issue: #981 
Waiting for a review from @ossarga in order to merge it and then release v2.1.2

**Comment by therb1** [comment]
@adejanovski is there any workaround here?

**Comment by ossarga** [comment]
@adejanovski PR #981 is now merged.

@therb1 until this fix makes it into an official release the only two work arounds I can think of are:
1. Compile a new binary from the `master` branch.
1. Use the [`spreaper`](https://github.com/thelastpickle/cassandra-reaper/blob/master/src/packaging/bin/spreaper) commandline tool.

**Comment by adejanovski** [comment]
The fix was released in 2.1.2.

**Comment by shumak80** [comment]
Thank you guys for quick fix.
