### ISSUE TITLE
Wrong status code returned on PUT /cluster/{cluster_name}

### ISSUE THREAD

**Issue by jsanda** [thelastpickle/cassandra-reaper#980]
This is somewhat of a minor issue. I am working with the REST API in a Kubernetes environment. My backend Cassandra cluster does _not_ have remote JMX properly configured at the moment. I tried adding the cluster as follows:

```
$ curl -v -H "Content-Type: application/json" -X PUT http://localhost:8080/cluster/reaper-test?seedHost=reaper-test-reaper-test-service
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> PUT /cluster/reaper-test?seedHost=reaper-test-reaper-test-service HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 400 Bad Request
< Date: Wed, 28 Oct 2020 02:55:43 GMT
< Content-Type: application/json
< Content-Length: 69
<
* Connection #0 to host localhost left intact
no cluster reaper-test with seed host reaper-test-reaper-test-service* Closing connection 0
```

The 400 response is incorrect and misleading. As far as I know, it is a perfectly valid request.  The response should return a 5xx status code. Reaper logs this error:

```
ERROR  [2020-10-28 02:55:43,080] [dw-26 - PUT /cluster/reaper-test?seedHost=reaper-test-reaper-test-service] i.c.r.ClusterResource - failed to find cluster with seed hosts: [reaper-test-reaper-test-service]
io.cassandrareaper.ReaperException: no host could be reached through JMX
	at io.cassandrareaper.jmx.JmxConnectionFactory.connectAny(JmxConnectionFactory.java:147)
	at io.cassandrareaper.jmx.ClusterFacade.connectImpl(ClusterFacade.java:809)
	at io.cassandrareaper.jmx.ClusterFacade.connect(ClusterFacade.java:793)
	at io.cassandrareaper.jmx.ClusterFacade.getClusterName(ClusterFacade.java:139)
	at io.cassandrareaper.resources.ClusterResource.findClusterWithSeedHost(ClusterResource.java:250)
	at io.cassandrareaper.resources.ClusterResource.addOrUpdateCluster(ClusterResource.java:181)
	at io.cassandrareaper.resources.ClusterResource.addOrUpdateCluster(ClusterResource.java:167)
```

`ClusterResource.getClusterName` should handle the exception and return a better error message along with a 5xx status code.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-263) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-263

**Comment by michaelsembwever** [comment]
@jsanda the url isn't correct. (it is not a reaper internal/500 error.)

The error message `no cluster reaper-test with seed host reaper-test-reaper-test-service` does explain it.

The cluster name `reaper-test` is specified in the url path, and the seedHost parameter with argument `reaper-test-reaper-test-service`.

I do believe that the `seedHost` can be either hostname or ip. I suspect here hostname is unresolvable? 

Open to suggestions to how to improve the error message… It may be just to retry with an ip.

It has been chosen as a 400 error, as the error is not internal to the Reaper server.
It is either an incorrect http request, or the servers/dns/resolv.conf have not been configured correctly. The latter falls into a grey-zone on what the definition of "client-side" and "server-side" is, but here it is based on server-side being internal to Reaper. For example it may extend to a storage connection failure between Reaper and a Cassandra storage backend would be a 500, but a first-time jmx connection failure to a yet unverified hostname is deemed to be best presented instead as the operator's fault.

**Comment by jsanda** [comment]
Actually the URL is correct and the seed I specified is resolvable. I have used this exact `curl` command in the past and just verified again that it works:

```
$ curl -v -H "Content-Type: application/json" -X PUT http://localhost:8080/cluster/reaper-test?seedHost=reaper-test-reaper-test-service
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> PUT /cluster/reaper-test?seedHost=reaper-test-reaper-test-service HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 201 Created
< Date: Wed, 28 Oct 2020 15:51:07 GMT
< Location: http://localhost:8080/cluster/reaper-test
< Content-Length: 0
<
* Connection #0 to host localhost left intact
* Closing connection 0
```

The reason that the original request failed is due to the fact that remote JMX is not enabled in the Cassandra cluster. This is reported in the `ReaperException` that I previously listed. Here is the relevant part:

```
ERROR  [2020-10-28 02:55:43,080] [dw-26 - PUT /cluster/reaper-test?seedHost=reaper-test-reaper-test-service] i.c.r.ClusterResource - failed to find cluster with seed hosts: [reaper-test-reaper-test-service]
io.cassandrareaper.ReaperException: no host could be reached through JMX
```
The request is perfectly valid which makes the 400 misleading. The error is 100% server-side in so far as Reaper cannot make the JMX connection on the server side, hence why I say Reaper should be returning a 500 status code here.

As I mentioned before `ClusterResource.getClusterName` should handle the exception and return a better error message along with the 500 status code.

**Comment by jsanda** [comment]
I should also note that this issue applies to `POST /cluster/{clusterName}` as well since both are handled by the same method in ClusterResource.java.

**Comment by michaelsembwever** [comment]
> The request is perfectly valid which makes the 400 misleading. The error is 100% server-side in so far as Reaper cannot make the JMX connection on the server side, hence why I say Reaper should be returning a 500 status code here.

That's not a fault of Reaper.

The operator has not configured the Cassandra cluster to be compatible with Reaper.
The operator has made a request that is invalid against their Cassandra clusters.
The Cassandra operator, not the Reaper operator, is required to fix this issue.
This is my reasoning for it being a 400 error.

The error message can and should be clearer.
The error here can be any of the following
 - the seed host hostname is not resolvable to an ip
 - reaper has no network connection/route to the seed host
 - the seed host Cassandra node has not configured remote JMX
 - other JMX connection failures related to the configuration of the Cassandra node or arguments provided to the Reaper request to add/update the cluster.

**Comment by adejanovski** [comment]
@jsanda, can we close this ticket or is it still something you'd want to have addressed?

**Comment by jsanda** [comment]
We can close it.
