### ISSUE TITLE
Add "millis since last repair"-metric for repair schedules.

### ISSUE THREAD

**Issue by jvv-trackunit** [thelastpickle/cassandra-reaper#982]
### Use case
We have two schedules per cluster. One for incremental repairs and one for non-incremental repairs.

We wish to obtain metrics regarding the repairs triggered by each schedule, so that we can alert if one of the schedules has not run successfully for a while.

We use Prometheus for monitoring. The existing metrics provided details regarding ongoing repairs, but the metrics did not reveal which schedule they came from.

### Proposed enhancement
This PR adds a "millisSinceLastRepairForSchedule" for each repair schedule. For schedules that have never successfully run, the metric returns the number of milliseconds passed since epoch.

PR: https://github.com/thelastpickle/cassandra-reaper/pull/974

(This PR also implements a mapping of Dropwizard metrics to Prometheus metrics with nice labels. This means that users do not need to create custom relabeling rules as described in the documentation. I have added a MapperConfig for some of the metrics, but not all.)

adejanovski

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-262) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-262

**Comment by adejanovski** [comment]
@bradfordcp this issue and the associated PR should help us getting proper metrics for Prometheus to scrape.
