### ISSUE TITLE
Docker image: Configure max pending compactions configuration using environment variable 

### ISSUE THREAD

**Issue by jvv-trackunit** [thelastpickle/cassandra-reaper#983]
I need to modify the maxPendingCompactions configuration, but was unable to do so while using the docker image.

My current workaround is to building a custom cassandra-reaper docker image with a modified configuration file, but I would prefer to see this configuration option supported by default.

PR: https://github.com/thelastpickle/cassandra-reaper/pull/973

@adejanovski

**Comment by adejanovski** [comment]
PR merged. Thanks!
