### ISSUE TITLE
It does not allow to schedule a cluster for different periods for the same day.

### ISSUE THREAD

**Issue by muthugomu** [thelastpickle/cassandra-reaper#991]
**Spotted on 2.1.2 (969eb6e)**

I have a requirement where I am required to schedule the Repair for given cluster into two periods as shown:

1. 4AM
1. 9PM

However it only allows me to schedule the same for one period either at 4AM or 9PM and not both. Would appreciate if this feature could be added in the upcoming release.  I have tried setting the interval set to 0, then again with 1 as well, it did not work.  It only allows to add one schedule as it may be not be recognizing the frequency change as a new schedule.

![image](https://user-images.githubusercontent.com/26508662/98871332-5bb19580-243a-11eb-8e6a-da06b621ded8.png)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-254) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-254

**Comment by adejanovski** [comment]
Sadly the scheduler won't support such a use case. The start date/hour gets updated regularly throughout the lifetime of a schedule and cannot be used as part of the primary key.
